// libs/angular/src/lib/drawer/atl-drawer.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  effect,
  inject,
  Injector,
  input,
  model,
  signal,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';
import { A11yModule } from '@angular/cdk/a11y';
import { ATL_DRAWER } from './atl-drawer.token';
import { isNgDevMode } from '../a11y-dev-warn';
import { AtlIcon } from '../icon/atl-icon';

let nextId = 0;

/**
 * Slide-in drawer panel using the native `<dialog>` element.
 * Supports left, right, top, and bottom positions with focus trap,
 * Escape to close, and backdrop click to close.
 * Compose with `atl-drawer-header`, `atl-drawer-content`, and `atl-drawer-footer`.
 *
 * Usage:
 * ```html
 * <atl-button (click)="isOpen = true">Open</atl-button>
 * <atl-drawer [(open)]="isOpen" position="right">
 *   <atl-drawer-header>Settings</atl-drawer-header>
 *   <atl-drawer-content>Content here.</atl-drawer-content>
 *   <atl-drawer-footer>
 *     <atl-button variant="primary" (click)="isOpen = false">Save</atl-button>
 *   </atl-drawer-footer>
 * </atl-drawer>
 * ```
 */
@Component({
  selector: 'atl-drawer',
  standalone: true,
  imports: [A11yModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: ATL_DRAWER,
      useFactory: (drawer: AtlDrawer) => ({
        headerId: drawer.headerId,
        close: () => drawer.open.set(false),
      }),
      deps: [AtlDrawer],
    },
  ],
  template: `
    <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events, @angular-eslint/template/interactive-supports-focus -->
    <dialog
      #dialogEl
      [attr.aria-labelledby]="headerId"
      aria-modal="true"
      [cdkTrapFocus]="open()"
      (cancel)="onCancel($event)"
      (close)="open.set(false)"
      (click)="onBackdropClick($event)"
    >
      <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events, @angular-eslint/template/interactive-supports-focus -->
      <div class="panel" (click)="$event.stopPropagation()">
        <ng-content />
      </div>
    </dialog>
  `,
  // Class-rooted CSS shared with React and Vue (libs/styles): the root class below
  // is what scopes it, so Emulated encapsulation is switched off.
  // eslint-disable-next-line @angular-eslint/use-component-view-encapsulation
  encapsulation: ViewEncapsulation.None,
  styleUrl: '../../../../styles/src/drawer/atl-drawer.css',
  host: {
    class: 'atl-drawer',
    '[class]': 'hostClasses()',
  },
})
export class AtlDrawer {
  /** Whether the drawer is open. Supports two-way binding: [(open)]="isOpen". */
  readonly open = model(false);

  /** Which edge the drawer slides in from. */
  readonly position = input<'left' | 'right' | 'top' | 'bottom'>('right');

  /** Width (for left/right) or height (for top/bottom) of the panel. */
  readonly size = input<'sm' | 'md' | 'lg' | 'full'>('md');

  /** Whether clicking the backdrop closes the drawer. */
  readonly closeOnBackdrop = input(true);

  /** @internal — referenced by AtlDrawerHeader via ATL_DRAWER token */
  readonly headerId = `atl-drawer-header-${nextId}`;

  protected readonly drawerId = `atl-drawer-${nextId++}`;
  protected readonly dialogRef =
    viewChild<ElementRef<HTMLDialogElement>>('dialogEl');
  private readonly triggerEl = signal<HTMLElement | null>(null);
  private readonly injector = inject(Injector);
  private warnedUnnamed = false;

  protected readonly hostClasses = computed(
    () =>
      `position-${this.position()} size-${this.size()}${this.open() ? ' is-open' : ''}`,
  );

  constructor() {
    effect(() => {
      const dialog = this.dialogRef()?.nativeElement;
      if (!dialog) return;
      if (this.open()) {
        this.triggerEl.set(document.activeElement as HTMLElement);
        dialog.showModal();
        this.warnIfUnnamed(dialog);
      } else {
        if (dialog.open) dialog.close();
        this.triggerEl()?.focus();
        this.triggerEl.set(null);
      }
    });
  }

  /**
   * Dev-mode warning, once per instance, when the dialog opens with nothing
   * naming it. Checked after render so a header projected later (or an
   * `aria-label` bound dynamically) has settled by then.
   */
  private warnIfUnnamed(dialog: HTMLDialogElement): void {
    if (!isNgDevMode() || this.warnedUnnamed) return;
    this.warnedUnnamed = true;
    afterNextRender(
      () => {
        const named = dialog.querySelector(`[id="${this.headerId}"]`) !== null;
        if (!named) {
          console.warn(
            '[AtlDrawer] opened with no accessible name — ' +
              'add an <atl-drawer-header> so screen readers announce its purpose.',
            dialog,
          );
        }
      },
      { injector: this.injector },
    );
  }

  protected onCancel(event: Event): void {
    event.preventDefault();
    this.open.set(false);
  }

  protected onBackdropClick(event: MouseEvent): void {
    if (
      this.closeOnBackdrop() &&
      event.target === this.dialogRef()?.nativeElement
    ) {
      this.open.set(false);
    }
  }
}

/**
 * Header slot for `atl-drawer`. Contains the title and a close button.
 * Automatically receives the correct `id` for `aria-labelledby` association.
 */
@Component({
  selector: 'atl-drawer-header',
  standalone: true,
  imports: [AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-content />
    <button
      class="close-btn"
      type="button"
      aria-label="Close drawer"
      (click)="context.close()"
    >
      <atl-icon name="close" size="sm" />
    </button>
  `,
  // Class-rooted CSS shared with React and Vue (libs/styles): the root class below
  // is what scopes it, so Emulated encapsulation is switched off.
  // eslint-disable-next-line @angular-eslint/use-component-view-encapsulation
  encapsulation: ViewEncapsulation.None,
  styleUrl: '../../../../styles/src/drawer/atl-drawer.css',
  host: {
    class: 'atl-drawer-header',
    '[attr.id]': 'context.headerId',
  },
})
export class AtlDrawerHeader {
  protected readonly context = inject(ATL_DRAWER);
}

/**
 * Content slot for `atl-drawer`. Scrollable primary content area.
 */
@Component({
  selector: 'atl-drawer-content',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  // Class-rooted CSS shared with React and Vue (libs/styles): the root class below
  // is what scopes it, so Emulated encapsulation is switched off.
  // eslint-disable-next-line @angular-eslint/use-component-view-encapsulation
  encapsulation: ViewEncapsulation.None,
  styleUrl: '../../../../styles/src/drawer/atl-drawer.css',
  host: { class: 'atl-drawer-content' },
})
export class AtlDrawerContent {}

/**
 * Footer slot for `atl-drawer`. Renders at the bottom with action buttons.
 */
@Component({
  selector: 'atl-drawer-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  // Class-rooted CSS shared with React and Vue (libs/styles): the root class below
  // is what scopes it, so Emulated encapsulation is switched off.
  // eslint-disable-next-line @angular-eslint/use-component-view-encapsulation
  encapsulation: ViewEncapsulation.None,
  styleUrl: '../../../../styles/src/drawer/atl-drawer.css',
  host: { class: 'atl-drawer-footer' },
})
export class AtlDrawerFooter {}

// libs/vue/src/lib/drawer/atl-drawer.vue
<script lang="ts">
import type { InjectionKey } from 'vue';

export interface AtlDrawerContext {
  headerId: string;
  close: () => void;
}

export const AtlDrawerKey: InjectionKey<AtlDrawerContext> = Symbol('AtlDrawer');

export interface AtlDrawerProps {
  /** Whether the drawer is open. Two-way bound via `v-model:open` (emits `update:open`). */
  open?: boolean;
  /** Which edge the drawer slides in from. */
  position?: 'left' | 'right' | 'top' | 'bottom';
  /** Width (for left/right) or height (for top/bottom) of the panel. */
  size?: 'sm' | 'md' | 'lg' | 'full';
  /** Whether clicking the backdrop closes the drawer. */
  closeOnBackdrop?: boolean;
}
</script>

<script setup lang="ts">
import { computed, nextTick, onMounted, provide, ref, useId, watch } from 'vue';
import { isDevBuild } from '../a11y-dev-warn';
import '@atelier-ui/styles/drawer/atl-drawer.css';

defineOptions({ name: 'AtlDrawer' });

const props = withDefaults(defineProps<AtlDrawerProps>(), {
  open: false,
  position: 'right',
  size: 'md',
  closeOnBackdrop: true,
});

const emit = defineEmits<{
  'update:open': [open: boolean];
}>();

const dialogRef = ref<HTMLDialogElement | null>(null);
const headerId = useId();

let warnedUnnamed = false;

// Dev-mode warning, once per instance, when the dialog opens with nothing naming
// it: no header in the slot and no aria-label / aria-labelledby override. Checked
// after the next tick so a header rendered later has settled.
function warnIfUnnamed() {
  const dialog = dialogRef.value;
  if (!isDevBuild() || warnedUnnamed || !dialog) return;
  warnedUnnamed = true;
  void nextTick(() => {
    const named =
      dialog.getAttribute('aria-labelledby') !== headerId ||
      dialog.querySelector(`[id="${headerId}"]`) !== null;
    if (!named) {
      console.warn(
        '[AtlDrawer] opened with no accessible name — ' +
          'add an <atl-drawer-header> so screen readers announce its purpose.',
        dialog,
      );
    }
  });
}

function close() {
  emit('update:open', false);
}

provide(AtlDrawerKey, {
  headerId,
  close,
});

onMounted(() => {
  if (props.open && dialogRef.value) {
    dialogRef.value.showModal();
    warnIfUnnamed();
  }
});

watch(
  () => props.open,
  (isOpen) => {
    const dialog = dialogRef.value;
    if (!dialog) return;
    if (isOpen) {
      if (!dialog.open) dialog.showModal();
      warnIfUnnamed();
    } else {
      if (dialog.open) dialog.close();
    }
  },
  { flush: 'post' },
);

function onDialogClose() {
  emit('update:open', false);
}

function onDialogCancel(event: Event) {
  event.preventDefault();
  emit('update:open', false);
}

function onBackdropClick(event: MouseEvent) {
  if (props.closeOnBackdrop && event.target === dialogRef.value) {
    emit('update:open', false);
  }
}

const hostClasses = computed(() => [
  'atl-drawer',
  `position-${props.position}`,
  `size-${props.size}`,
  props.open && 'is-open',
]);
</script>

<template>
  <!-- The host classes sit on a wrapper (display: contents), not on the
  <dialog>: the shared CSS styles `.atl-drawer > dialog`, as in React. -->
  <div :class="hostClasses">
    <!-- Backdrop-click-to-close on a native <dialog>: keyboard users already
    have a keyboard-equivalent close path via the native Escape key, wired
    through @cancel/@close below — the click handler is a pointer-only
    convenience on top of that, not the only way to dismiss the dialog. -->
    <!-- eslint-disable-next-line vuejs-accessibility/click-events-have-key-events, vuejs-accessibility/no-static-element-interactions -->
    <dialog
      ref="dialogRef"
      :aria-labelledby="headerId"
      aria-modal="true"
      @close="onDialogClose"
      @cancel="onDialogCancel"
      @click="onBackdropClick"
    >
      <div class="panel" @click.stop>
        <slot />
      </div>
    </dialog>
  </div>
</template>
