// libs/angular/src/lib/radio/atl-radio.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  OnDestroy,
  OnInit,
} from '@angular/core';
import {
  ATL_RADIO_GROUP,
  type RadioItem,
} from '../radio-group/atl-radio-group.token';

let nextId = 0;

/**
 * Individual radio button. Must be placed inside an `atl-radio-group`.
 *
 * Usage:
 * ```html
 * <atl-radio-group [(value)]="selected" name="plan">
 *   <atl-radio radioValue="free">Free</atl-radio>
 *   <atl-radio radioValue="pro">Pro</atl-radio>
 * </atl-radio-group>
 * ```
 */
@Component({
  selector: 'atl-radio',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [attr.for]="inputId">
      <input
        type="radio"
        [id]="inputId"
        [value]="radioValue()"
        [checked]="isChecked()"
        [disabled]="isDisabled()"
        [attr.name]="effectiveName() || null"
        (click)="onClick($event)"
        (change)="onChange()"
        (blur)="onBlur()"
      />
      <ng-content />
    </label>
  `,
  styleUrl: './atl-radio.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class AtlRadio implements RadioItem, OnInit, OnDestroy {
  /** The value this radio option represents within the group. */
  readonly radioValue = input.required<string>();

  /** Whether this specific radio is individually disabled (stacked with group disabled). */
  // eslint-disable-next-line @angular-eslint/no-input-rename
  readonly disabledInput = input(false, { alias: 'disabled' });

  /** @internal */
  private readonly group = inject(ATL_RADIO_GROUP, { optional: true });

  /** @internal */
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);

  /** @internal */
  protected readonly inputId = `atl-radio-${nextId++}`;

  /** @internal */
  protected readonly isChecked = computed(
    () => this.group?.value() === this.radioValue(),
  );

  /** @internal */
  readonly isDisabled = computed(
    () => this.disabledInput() || (this.group?.disabled() ?? false),
  );

  /** @internal */
  protected readonly effectiveName = computed(() => this.group?.name() ?? '');

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.isChecked()) classes.push('is-checked');
    if (this.isDisabled()) classes.push('is-disabled');
    if (this.group?.invalid()) classes.push('is-invalid');
    return classes.join(' ');
  });

  /** @internal — for FocusKeyManager */
  get disabled(): boolean {
    return this.isDisabled();
  }

  /** @internal — for FocusKeyManager */
  focus(): void {
    this.el.nativeElement.querySelector<HTMLInputElement>('input')?.focus();
  }

  ngOnInit(): void {
    this.group?.registerItem(this);
  }

  ngOnDestroy(): void {
    this.group?.unregisterItem(this);
  }

  /** @internal */
  /**
   * readonly is enforced by cancelling the click, not only by the group's
   * `select()` guard: HTML ignores `readonly` on a radio, so the input would flip
   * its own DOM state while the model stayed put — and with OnPush nothing
   * re-renders to correct it. See ADR-0045.
   */
  protected onClick(event: Event): void {
    if (this.group?.readonly()) event.preventDefault();
  }

  protected onChange(): void {
    this.group?.select(this.radioValue());
  }

  /** @internal */
  protected onBlur(): void {
    this.group?.markTouched();
  }
}

// libs/vue/src/lib/radio/atl-radio.vue
<script setup lang="ts">
import { computed, inject } from 'vue';
import { AtlRadioGroupKey } from '../radio-group/atl-radio-group.vue';
import '@atelier-ui/styles/radio/atl-radio.css';

defineOptions({ name: 'AtlRadio' });

interface AtlRadioProps {
  /** The value this radio option represents within the group. */
  radioValue: string;
  /** Whether this radio is individually disabled (in addition to a disabled group). */
  disabled?: boolean;
}

const props = withDefaults(defineProps<AtlRadioProps>(), {
  disabled: false,
});

const ctx = inject(AtlRadioGroupKey, {
  value: '',
  name: '',
  disabled: false,
  readonly: false,
  invalid: false,
  onSelect: () => undefined,
});

const isDisabled = computed(() => props.disabled || ctx.disabled);
const isChecked = computed(() => ctx.value === props.radioValue);

const classes = computed(() =>
  [
    'atl-radio',
    isDisabled.value && 'is-disabled',
    isChecked.value && 'is-checked',
    ctx.invalid && 'is-invalid',
  ].filter(Boolean),
);

function onChange() {
  if (!isDisabled.value && !ctx.readonly) {
    ctx.onSelect(props.radioValue);
  }
}

// HTML ignores `readonly` on a radio, so the guard above stops the model but not
// the input's own DOM state — and nothing re-renders to correct it, since nothing
// changed. Cancelling the click makes the browser restore the previous selection
// (verified in chromium). See ADR-0045.
function onClick(event: MouseEvent) {
  if (ctx.readonly) event.preventDefault();
}
</script>

<template>
  <label :class="classes">
    <input
      type="radio"
      :name="ctx.name || undefined"
      :value="radioValue"
      :checked="isChecked"
      :disabled="isDisabled"
      class="radio-input"
      @click="onClick"
      @change="onChange"
    />
    <span class="radio-indicator" aria-hidden="true" />
    <span v-if="$slots.default" class="radio-text">
      <slot />
    </span>
  </label>
</template>
