// libs/react/src/lib/radio/llm-radio.tsx
import { ReactNode } from 'react';
import type { LlmRadioSpec } from '../spec';
import { useRadioGroup } from '../radio-group/llm-radio-group';
import './llm-radio.css';

/**
 * Properties for the LlmRadio component.
 */
export interface LlmRadioProps extends LlmRadioSpec {
  /**
   * The value of the radio button.
   */
  radioValue: string;
  /**
   * Whether the radio button is disabled.
   */
  disabled?: boolean;
  /**
   * The content to be rendered as the label for the radio button.
   */
  children?: ReactNode;
}

/**
 * An individual radio button component, meant to be used within LlmRadioGroup.
 */
export function LlmRadio({ radioValue, disabled = false, children }: LlmRadioProps) {
  const ctx = useRadioGroup();
  const isDisabled = disabled || ctx.disabled;
  const isReadOnly = ctx.readOnly;
  const isChecked = ctx.value === radioValue;

  const classes = [
    'llm-radio',
    isDisabled && 'is-disabled',
    isReadOnly && 'is-readonly',
    isChecked && 'is-checked',
    ctx.invalid && 'is-invalid',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <label className={classes}>
      <input
        type="radio"
        name={ctx.name || undefined}
        value={radioValue}
        checked={isChecked}
        disabled={isDisabled}
        readOnly={isReadOnly}
        onChange={() => !isDisabled && !isReadOnly && ctx.onSelect(radioValue)}
        onBlur={() => ctx.onBlur()}
      />
      {children && <span className="radio-text">{children}</span>}
    </label>
  );
}

// libs/vue/src/lib/radio/llm-radio.vue
<script setup lang="ts">
import { computed, inject } from 'vue';
import { LlmRadioGroupKey } from '../radio-group/llm-radio-group.vue';
import './llm-radio.css';

defineOptions({ name: 'LlmRadio' });

interface LlmRadioProps {
  radioValue: string;
  disabled?: boolean;
}

const props = withDefaults(defineProps<LlmRadioProps>(), {
  disabled: false,
});

const ctx = inject(LlmRadioGroupKey, {
  value: '',
  name: '',
  disabled: false,
  readonly: false,
  invalid: false,
  onSelect: () => undefined,
});

const isDisabled = computed(() => props.disabled || ctx.disabled);
const isChecked = computed(() => ctx.value === props.radioValue);

const classes = computed(() => [
  'llm-radio',
  isDisabled.value && 'is-disabled',
  isChecked.value && 'is-checked',
  ctx.invalid && 'is-invalid',
].filter(Boolean));

function onChange() {
  if (!isDisabled.value && !ctx.readonly) {
    ctx.onSelect(props.radioValue);
  }
}
</script>

<template>
  <label :class="classes">
    <input
      type="radio"
      :name="ctx.name || undefined"
      :value="radioValue"
      :checked="isChecked"
      :disabled="isDisabled"
      class="radio-input"
      @change="onChange"
    />
    <span class="radio-indicator" aria-hidden="true" />
    <span v-if="$slots.default" class="radio-text">
      <slot />
    </span>
  </label>
</template>
