// libs/vue/src/lib/select/llm-select.vue
<script setup lang="ts">
import { computed, useId } from 'vue';
import './llm-select.css';

defineOptions({ name: 'LlmSelect' });

interface LlmSelectProps {
  value?: string;
  placeholder?: string;
  invalid?: boolean;
  errors?: string[];
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  label?: string;
  name?: string;
}

const props = withDefaults(defineProps<LlmSelectProps>(), {
  value: '',
  placeholder: undefined,
  invalid: false,
  errors: () => [],
  disabled: false,
  readonly: false,
  required: false,
  label: undefined,
  name: undefined,
});

const emit = defineEmits<{
  'update:value': [value: string];
}>();

const selectId = useId();
const errorsId = useId();

const wrapperClasses = computed(() => [
  'llm-select',
  props.invalid && 'is-invalid',
  props.disabled && 'is-disabled',
]);

function onChange(event: Event) {
  if (props.readonly || props.disabled) return;
  emit('update:value', (event.target as HTMLSelectElement).value);
}
</script>

<template>
  <div :class="wrapperClasses">
    <label v-if="label" :for="selectId" class="select-label">{{ label }}</label>
    <div class="select-wrapper">
      <select
        :id="selectId"
        :name="name"
        :value="value"
        :disabled="disabled"
        :required="required"
        :aria-invalid="invalid || undefined"
        :aria-describedby="errors.length > 0 ? errorsId : undefined"
        class="select-native"
        @change="onChange"
      >
        <option v-if="placeholder" value="" disabled hidden>{{ placeholder }}</option>
        <slot />
      </select>
      <span class="select-arrow" aria-hidden="true">▾</span>
    </div>
    <div v-if="errors.length > 0" :id="errorsId" class="errors" role="alert">
      <p v-for="(error, index) in errors" :key="index" class="error-message">{{ error }}</p>
    </div>
  </div>
</template>

// libs/llm-components-react/src/lib/select/llm-select.tsx
import { ReactNode, SelectHTMLAttributes, OptionHTMLAttributes } from 'react';
import './llm-select.css';

export interface LlmSelectProps
  extends Omit<SelectHTMLAttributes<HTMLSelectElement>, 'value' | 'onChange'> {
  value?: string;
  onValueChange?: (value: string) => void;
  placeholder?: string;
  invalid?: boolean;
  errors?: string[];
  label?: string;
}

export function LlmSelect({
  value = '',
  onValueChange,
  placeholder,
  invalid = false,
  errors = [],
  disabled = false,
  required = false,
  label,
  children,
  className,
  id,
  ...rest
}: LlmSelectProps) {
  const selectId =
    id || (label ? `select-${label.toLowerCase().replace(/\s+/g, '-')}` : undefined);
  const classes = [
    'llm-select',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes}>
      {label && <label htmlFor={selectId}>{label}</label>}
      <div className="select-wrapper">
        <select
          id={selectId}
          value={value}
          onChange={(e) => onValueChange?.(e.target.value)}
          disabled={disabled}
          required={required}
          aria-invalid={invalid || undefined}
          {...rest}
        >
          {placeholder && (
            <option value="" disabled hidden>
              {placeholder}
            </option>
          )}
          {children}
        </select>
        <span className="select-arrow" aria-hidden="true">
          ▾
        </span>
      </div>
      {errors.length > 0 && (
        <div className="errors" role="alert" aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

export interface LlmOptionProps extends OptionHTMLAttributes<HTMLOptionElement> {
  optionValue: string;
  children?: ReactNode;
}

export function LlmOption({ optionValue, children, ...rest }: LlmOptionProps) {
  return (
    <option value={optionValue} {...rest}>
      {children}
    </option>
  );
}
