// libs/vue/src/lib/card/llm-card.vue
<script setup lang="ts">
import { computed } from 'vue';
import './llm-card.css';

defineOptions({ name: 'LlmCard' });

interface LlmCardProps {
  variant?: 'elevated' | 'outlined' | 'flat';
  padding?: 'none' | 'sm' | 'md' | 'lg';
  /**
   * Opt-in landmark role. Default is no role.
   *
   * - `'article'` — self-contained content (blog post, comment).
   * - `'region'`  — perceivable area that needs a screen-reader stop;
   *                 pair with `aria-label`.
   * - `'section'` — mirrors an HTML `<section>`.
   *
   * Most cards group content visually and shouldn't add a landmark.
   * Leave unset by default.
   */
  role?: 'article' | 'region' | 'section';
}

const props = withDefaults(defineProps<LlmCardProps>(), {
  variant: 'elevated',
  padding: 'md',
  role: undefined,
});

const classes = computed(() => [
  'llm-card',
  `variant-${props.variant}`,
  `padding-${props.padding}`,
]);
</script>

<template>
  <div :class="classes" :role="role">
    <slot />
  </div>
</template>

// libs/react/src/lib/card/llm-card.tsx
import { HTMLAttributes, ReactNode } from 'react';
import type { LlmCardSpec, LlmCardRole } from '../spec';
import './llm-card.css';

/**
 * Properties for the LlmCard component.
 */
export interface LlmCardProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'role'>,
    LlmCardSpec {
  /**
   * The visual style variant of the card.
   */
  variant?: 'elevated' | 'outlined' | 'flat';
  /**
   * The padding size within the card.
   */
  padding?: 'none' | 'sm' | 'md' | 'lg';
  /**
   * Opt-in landmark role. Default is no role (plain `<div>`).
   * Pick `'article'` for self-contained content, `'region'` for a
   * perceivable area that needs a screen-reader stop (pair with
   * aria-label), or `'section'` to mirror an HTML `<section>`.
   */
  role?: LlmCardRole;
  /**
   * The content to be rendered inside the card.
   */
  children?: ReactNode;
}

/**
 * A card component for grouping related content.
 */
export function LlmCard({
  variant = 'elevated',
  padding = 'md',
  children,
  className,
  ...rest
}: LlmCardProps) {
  const classes = ['llm-card', `variant-${variant}`, `padding-${padding}`, className]
    .filter(Boolean)
    .join(' ');
  return (
    <div className={classes} {...rest}>
      {children}
    </div>
  );
}

/**
 * The header component for an LlmCard.
 */
export function LlmCardHeader({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & {
  /**
   * The content of the card header.
   */
  children?: ReactNode;
}) {
  return (
    <div className={['llm-card-header', className].filter(Boolean).join(' ')} {...rest}>
      {children}
    </div>
  );
}

/**
 * The main content component for an LlmCard.
 */
export function LlmCardContent({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & {
  /**
   * The main content of the card.
   */
  children?: ReactNode;
}) {
  return (
    <div className={['llm-card-content', className].filter(Boolean).join(' ')} {...rest}>
      {children}
    </div>
  );
}

/**
 * The footer component for an LlmCard.
 */
export function LlmCardFooter({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & {
  /**
   * The content of the card footer.
   */
  children?: ReactNode;
}) {
  return (
    <div className={['llm-card-footer', className].filter(Boolean).join(' ')} {...rest}>
      {children}
    </div>
  );
}
