// libs/angular/src/lib/input/atl-input.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
} from '@angular/core';
import type { FormValueControl } from '@angular/forms/signals';
import { type ValidationError, type WithOptionalFieldTree } from '@angular/forms/signals';
import { AtlIcon } from '../icon/atl-icon';

let nextId = 0;

/**
 * Accessible text input component for use with Angular Signal Forms.
 *
 * Usage:
 * ```html
 * <atl-input type="email" placeholder="you@example.com" [(value)]="email" />
 * <atl-input [formField]="loginForm.email" placeholder="Email" />
 * ```
 */
@Component({
  selector: 'atl-input',
  standalone: true,
  imports: [AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="input-field">
      <input
        [type]="type()"
        [value]="value()"
        (input)="onInput($event)"
        (blur)="touched.set(true)"
        [disabled]="disabled()"
        [readOnly]="readonly()"
        [placeholder]="placeholder()"
        [attr.name]="name() || null"
        [attr.aria-invalid]="invalid() || null"
        [attr.aria-required]="required() || null"
        [attr.aria-describedby]="showErrors() ? errorId : null"
      />
      @if (invalid()) {
        <atl-icon name="danger" size="sm" class="invalid-icon" />
      }
    </div>
    @if (showErrors()) {
      <div class="errors" [id]="errorId" aria-live="polite">
        @for (error of errors(); track error.kind) {
          <p class="error-message">{{ error.message }}</p>
        }
      </div>
    }
  `,
  styleUrl: './atl-input.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class AtlInput implements FormValueControl<string> {
  /** The current input value. Bound by [formField] directive. Supports [(value)] two-way binding. */
  readonly value = model('');

  /** The type of input field. */
  readonly type = input<'text' | 'email' | 'password' | 'number' | 'tel' | 'url'>('text');

  /** Placeholder text shown when the input is empty. */
  readonly placeholder = input('');

  /** Whether the input is disabled. Bound by [formField] directive. */
  readonly disabled = input(false);

  /** Whether the input is read-only. Bound by [formField] directive. */
  readonly readonly = input(false);

  /** Whether the input has validation errors. Bound by [formField] directive. */
  readonly invalid = input(false);

  /** Validation errors from the form system. Bound by [formField] directive. */
  readonly errors = input<readonly WithOptionalFieldTree<ValidationError>[]>([]);

  /** Whether the user has interacted with the input. Bound by [formField] directive. */
  readonly touched = model(false);

  /** Whether the input is required. Bound by [formField] directive. */
  readonly required = input(false);

  /** The input's name attribute. Bound by [formField] directive. */
  readonly name = input('');

  /** @internal */
  protected readonly errorId = `atl-input-errors-${nextId++}`;

  /** @internal */
  protected readonly showErrors = computed(
    () => this.touched() && this.invalid() && this.errors().length > 0
  );

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.disabled()) classes.push('is-disabled');
    if (this.invalid()) classes.push('is-invalid');
    if (this.readonly()) classes.push('is-readonly');
    if (this.touched()) classes.push('is-touched');
    return classes.join(' ');
  });

  /** @internal */
  protected onInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.value.set(target.value);
  }
}

// libs/react/src/lib/input/atl-input.tsx
import { InputHTMLAttributes, useId } from 'react';
import type { AtlInputSpec } from '../spec';
import '@atelier-ui/styles/input/atl-input.css';
import { AtlIcon } from '../icon/atl-icon';

/**
 * Properties for the AtlInput component.
 */
export interface AtlInputProps
  extends
    Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'readOnly'>,
    AtlInputSpec {
  /**
   * Whether the input is disabled.
   */
  disabled?: boolean;
  /**
   * Whether the input is required.
   */
  required?: boolean;
  /**
   * The input's name attribute, used for form submission.
   */
  name?: string;
  /**
   * Lowercase alias of `readOnly`: whether the input is read-only. `readOnly` wins when both are set.
   */
  readonly?: boolean;
  /**
   * Placeholder text shown when the input is empty.
   */
  placeholder?: string;
  /**
   * The type of input to render.
   */
  type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
  /**
   * The current value of the input.
   */
  value?: string;
  /**
   * Callback triggered when the value changes.
   */
  onValueChange?: (value: string) => void;
  /**
   * Whether the input is in an invalid state.
   */
  invalid?: boolean;
  /**
   * Array of error messages to display.
   */
  errors?: string[];
  /**
   * The label for the input.
   */
  label?: string;
  /**
   * Whether the input is read-only.
   */
  readOnly?: boolean;
}

/**
 * A versatile input component for text entry.
 */
export function AtlInput({
  type = 'text',
  value,
  onChange,
  onValueChange,
  invalid = false,
  errors = [],
  disabled = false,
  readOnly: reactReadOnly,
  readonly: specReadOnly,
  required = false,
  label,
  className,
  id,
  ...rest
}: AtlInputProps) {
  const readOnly = reactReadOnly ?? specReadOnly ?? false;
  // useId(), not a slug derived from the label text: two inputs with the same
  // label used to collide on one id and break the for/id association.
  const generatedId = useId();
  const inputId = id || (label ? `input-${generatedId}` : undefined);
  const classes = [
    'atl-input',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    readOnly && 'is-readonly',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onChange?.(e);
    onValueChange?.(e.target.value);
  };

  const errorId = inputId ? `${inputId}-errors` : undefined;

  return (
    <div className={classes}>
      {label && <label htmlFor={inputId}>{label}</label>}
      <div className="input-field">
        <input
          id={inputId}
          type={type}
          value={value}
          onChange={handleChange}
          disabled={disabled}
          readOnly={readOnly}
          required={required}
          aria-invalid={invalid || undefined}
          aria-required={required || undefined}
          aria-describedby={errors.length > 0 ? errorId : undefined}
          {...rest}
        />
        {invalid && (
          <AtlIcon name="danger" size="sm" className="invalid-icon" />
        )}
      </div>
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}
