// libs/angular/src/lib/chat/atl-chat.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  afterNextRender,
  computed,
  effect,
  inject,
  input,
  model,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { A11yModule } from '@angular/cdk/a11y';
import { NgTemplateOutlet } from '@angular/common';
import type {
  AtlChatMessageRole,
  AtlChatStatus,
  AtlChatVariant,
} from '../spec';
import { ATL_CHAT } from './atl-chat.token';
import { AtlIcon } from '../icon/atl-icon';

let nextId = 0;

/**
 * AI assistant surface. Three layout variants share the same content slots
 * and can be swapped without changing the children.
 *
 * Variants:
 * - `drawer`: Right-anchored slide-in panel, full viewport height.
 * - `popup`: Floating bubble (bottom-right) + compact chat window.
 * - `inline`: Embedded card, sits inline with page content.
 *
 * Compose with `atl-chat-header`, `atl-chat-messages`, `atl-chat-input`.
 *
 * Usage:
 * ```html
 * <atl-chat variant="drawer" [(open)]="isOpen" status="idle">
 *   <atl-chat-header>AI Assistant</atl-chat-header>
 *   <atl-chat-messages>
 *     <atl-chat-message role="assistant">Hi! How can I help?</atl-chat-message>
 *     <atl-chat-message role="user">Show me a sorting function.</atl-chat-message>
 *   </atl-chat-messages>
 *   <atl-chat-input placeholder="Ask anything…" (send)="onSend($event)" />
 * </atl-chat>
 * ```
 */
@Component({
  selector: 'atl-chat',
  standalone: true,
  imports: [A11yModule, NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: ATL_CHAT,
      useFactory: (chat: AtlChat) => ({
        headerId: chat.headerId,
        variant: chat.variant,
        status: chat.status,
        close: () => chat.open.set(false),
        toggle: () => chat.open.set(!chat.open()),
      }),
      deps: [AtlChat],
    },
  ],
  template: `
    <ng-template #content><ng-content /></ng-template>
    @switch (variant()) {
      @case ('drawer') {
        <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events, @angular-eslint/template/interactive-supports-focus -->
        <dialog
          #dialogEl
          [attr.aria-labelledby]="headerId"
          aria-modal="true"
          [cdkTrapFocus]="open()"
          (cancel)="onCancel($event)"
          (close)="open.set(false)"
          (click)="onBackdropClick($event)"
        >
          <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events, @angular-eslint/template/interactive-supports-focus -->
          <div
            class="surface drawer-surface"
            (click)="$event.stopPropagation()"
          >
            <ng-container [ngTemplateOutlet]="content" />
          </div>
        </dialog>
      }
      @case ('popup') {
        @if (open()) {
          <div
            class="surface popup-surface"
            [attr.aria-labelledby]="headerId"
            role="dialog"
          >
            <ng-container [ngTemplateOutlet]="content" />
          </div>
        }
        <button
          type="button"
          class="fab-bubble"
          [attr.aria-label]="
            open() ? 'Close AI assistant' : 'Open AI assistant'
          "
          [attr.aria-expanded]="open()"
          (click)="open.set(!open())"
        >
          <span aria-hidden="true">AI</span>
        </button>
      }
      @default {
        <section
          class="surface inline-surface"
          [attr.aria-labelledby]="headerId"
        >
          <ng-container [ngTemplateOutlet]="content" />
        </section>
      }
    }
  `,
  styleUrl: './atl-chat.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class AtlChat {
  /** Layout variant. */
  readonly variant = input<AtlChatVariant>('drawer');

  /** Whether the chat is open. Used by drawer/popup; ignored by inline. Two-way bindable via [(open)]. */
  readonly open = model(false);

  /** Connection / response status. Drives badge color in header and disables input while streaming. */
  readonly status = input<AtlChatStatus>('idle');

  /** @internal — referenced by AtlChatHeader via ATL_CHAT token for aria-labelledby. */
  readonly headerId = `atl-chat-header-${nextId++}`;

  protected readonly dialogRef =
    viewChild<ElementRef<HTMLDialogElement>>('dialogEl');
  private readonly host: ElementRef<HTMLElement> = inject(ElementRef);
  private readonly triggerEl = signal<HTMLElement | null>(null);

  protected readonly hostClasses = computed(
    () =>
      `variant-${this.variant()} status-${this.status()}${this.open() ? ' is-open' : ''}`,
  );

  constructor() {
    // Drawer variant uses native <dialog> open/close lifecycle.
    effect(() => {
      if (this.variant() !== 'drawer') return;
      const dialog = this.dialogRef()?.nativeElement;
      if (!dialog) return;
      if (this.open()) {
        this.triggerEl.set(document.activeElement as HTMLElement);
        dialog.showModal();
      } else {
        if (dialog.open) dialog.close();
        this.triggerEl()?.focus();
        this.triggerEl.set(null);
      }
    });

    // Auto-focus the input on open for drawer / popup. Inline variant keeps
    // user focus where it was.
    effect(() => {
      if (!this.open()) return;
      if (this.variant() === 'inline') return;
      // Wait for the surface to be in the DOM (showModal / @if (open) render).
      requestAnimationFrame(() => {
        this.host.nativeElement
          .querySelector<HTMLTextAreaElement>('textarea')
          ?.focus();
      });
    });
  }

  protected onCancel(event: Event): void {
    event.preventDefault();
    this.open.set(false);
  }

  protected onBackdropClick(event: MouseEvent): void {
    if (event.target === this.dialogRef()?.nativeElement) {
      this.open.set(false);
    }
  }
}

/**
 * Header slot for `atl-chat`. Holds the title, status indicator, and close button.
 * Children are projected into the title area; the close button is rendered automatically.
 */
@Component({
  selector: 'atl-chat-header',
  standalone: true,
  imports: [AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="title-block">
      <ng-content />
    </div>
    @if (context.variant() !== 'inline') {
      <button
        type="button"
        class="close-btn"
        aria-label="Close chat"
        (click)="context.close()"
      >
        <atl-icon name="close" size="sm" />
      </button>
    }
  `,
  styleUrl: './atl-chat.css',
  host: {
    '[attr.id]': 'context.headerId',
  },
})
export class AtlChatHeader {
  protected readonly context = inject(ATL_CHAT);
}

/**
 * Scrollable message list for `atl-chat`. Project `atl-chat-message`,
 * `atl-chat-typing`, or `atl-chat-suggestion` children inside. Auto-scrolls
 * to the bottom whenever children are added or content changes — important
 * for streaming responses where new tokens are appended live.
 *
 * Renders `role="log"` (named, `aria-label="Conversation"`) with
 * `aria-live="polite"` on the host — the live region that announces new
 * messages without interrupting whatever the user is doing. `log` is not
 * `list`: an element carries exactly one role, so the projected
 * `atl-chat-message` `listitem`s get their required list parent from a
 * second, nested element (`.messages-list`, `role="list"`) rather than from
 * the log host itself. That wrapper is `display: contents` so it never
 * affects the flex/gap layout of the messages — verified (Chromium, Firefox,
 * WebKit): the gap between messages is unchanged, and Chromium's native
 * accessibility tree shows `log "Conversation" > list "Messages" > listitem, listitem`.
 */
@Component({
  selector: 'atl-chat-messages',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="messages-list" role="list" aria-label="Messages">
    <ng-content />
  </div>`,
  styleUrl: './atl-chat.css',
  host: {
    '[attr.role]': '"log"',
    '[attr.aria-live]': '"polite"',
    '[attr.aria-label]': '"Conversation"',
  },
})
export class AtlChatMessages {
  private readonly host: ElementRef<HTMLElement> = inject(ElementRef);
  private readonly destroyRef = inject(DestroyRef);

  constructor() {
    afterNextRender(() => {
      const el = this.host.nativeElement;
      const stickToBottom = (): void => {
        el.scrollTop = el.scrollHeight;
      };
      stickToBottom();
      const observer = new MutationObserver(stickToBottom);
      observer.observe(el, {
        childList: true,
        subtree: true,
        characterData: true,
      });
      this.destroyRef.onDestroy(() => observer.disconnect());
    });
  }
}

/**
 * A single chat message. Role drives bubble alignment and color.
 *
 * Usage:
 * ```html
 * <atl-chat-message role="assistant">Sure, here you go.</atl-chat-message>
 * <atl-chat-message role="user">Thanks!</atl-chat-message>
 * <atl-chat-message role="assistant" [failed]="true">Couldn't reach the assistant.</atl-chat-message>
 * ```
 */
@Component({
  selector: 'atl-chat-message',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  styleUrl: './atl-chat.css',
  host: {
    '[class]': 'hostClasses()',
    '[attr.role]': '"listitem"',
  },
})
export class AtlChatMessage {
  /** Sender of the message. Drives bubble alignment and color. */
  readonly role = input<AtlChatMessageRole>('assistant');

  /** Marks the message as failed (red dashed border, used in error state). */
  readonly failed = input(false);

  protected readonly hostClasses = computed(
    () => `role-${this.role()}${this.failed() ? ' is-failed' : ''}`,
  );
}

/**
 * Typing indicator (three animated dots).
 *
 * Two display modes:
 * - **Standalone bubble** (default) — render as the last child of
 *   `AtlChatMessages` to show "the assistant is starting to respond"
 *   before any tokens arrive.
 * - **Inline cursor** (`inline`) — render as the LAST child INSIDE
 *   `AtlChatMessage role="assistant"` to show the dots after the
 *   currently-streaming text. The bubble background is dropped so the
 *   dots read as a typing caret at the end of the partial response.
 */
@Component({
  selector: 'atl-chat-typing',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="sr-only">Assistant is typing</span>
  `,
  styleUrl: './atl-chat.css',
  host: {
    '[class]': 'hostClasses()',
    '[attr.role]': '"status"',
    '[attr.aria-live]': '"polite"',
  },
})
export class AtlChatTyping {
  /** When true, renders as an inline cursor without bubble chrome. */
  readonly inline = input(false);

  protected readonly hostClasses = computed(() =>
    this.inline() ? 'is-inline' : '',
  );
}

/**
 * Tappable suggestion chip used in the empty state to seed a conversation.
 *
 * Usage:
 * ```html
 * <atl-chat-suggestion label="Explain a code snippet" hint="Tap to start →" (selected)="prompt.set($event)" />
 * ```
 */
@Component({
  selector: 'atl-chat-suggestion',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button type="button" class="chip" (click)="selected.emit(label())">
      <span class="chip-label">{{ label() }}</span>
      @if (hint()) {
        <span class="chip-hint">{{ hint() }}</span>
      }
    </button>
  `,
  styleUrl: './atl-chat.css',
})
export class AtlChatSuggestion {
  /** Primary label of the suggestion. */
  readonly label = input.required<string>();

  /** Optional secondary hint text shown below the label. */
  readonly hint = input<string>('');

  /** Fires the label string when the chip is activated. */
  readonly selected = output<string>();
}

/**
 * Composable input footer for `atl-chat`. Wraps a text field and emits
 * `send` (or `stop` while the assistant is streaming).
 *
 * The button automatically switches to a `danger` "Stop" button when the
 * parent chat's `status` is `'streaming'`.
 *
 * Usage:
 * ```html
 * <atl-chat-input placeholder="Ask anything…" (send)="onSend($event)" (stop)="onStop()" />
 * ```
 */
@Component({
  selector: 'atl-chat-input',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <textarea
      class="field"
      [value]="value()"
      [placeholder]="effectivePlaceholder()"
      [disabled]="isStreaming()"
      [attr.aria-label]="ariaLabel()"
      (input)="onInput($event)"
      (keydown.enter)="onEnter($event)"
      rows="1"
    ></textarea>
    @if (isStreaming()) {
      <button
        type="button"
        class="action-btn variant-danger size-md"
        (click)="stop.emit()"
      >
        Stop
      </button>
    } @else {
      <button
        type="button"
        class="action-btn variant-primary size-md"
        [disabled]="!value().trim()"
        (click)="emitSend()"
      >
        Send
      </button>
    }
  `,
  styleUrl: './atl-chat.css',
})
export class AtlChatInput {
  /** Placeholder shown in the empty input. Defaults change per parent status. */
  readonly placeholder = input<string>('');

  /** Accessible label for the input field. */
  readonly ariaLabel = input<string>('Message your AI assistant');

  /** Two-way bindable text content. */
  readonly value = model<string>('');

  /** Fires when Enter is pressed (without Shift) or the Send button is clicked. */
  readonly send = output<string>();

  /** Fires when the Stop button is clicked while the parent chat is streaming. */
  readonly stop = output<void>();

  protected readonly context = inject(ATL_CHAT);

  protected readonly isStreaming = computed(
    () => this.context.status() === 'streaming',
  );

  protected readonly effectivePlaceholder = computed(() => {
    const explicit = this.placeholder();
    if (explicit) return explicit;
    switch (this.context.status()) {
      case 'streaming':
        return 'Waiting for response…';
      case 'error':
        return 'Try again…';
      default:
        return 'Message your AI assistant…';
    }
  });

  protected onInput(event: Event): void {
    const target = event.target as HTMLTextAreaElement;
    this.value.set(target.value);
  }

  protected onEnter(event: Event): void {
    const ke = event as KeyboardEvent;
    if (ke.shiftKey) return;
    ke.preventDefault();
    this.emitSend();
  }

  protected emitSend(): void {
    const text = this.value().trim();
    if (!text || this.isStreaming()) return;
    this.send.emit(text);
    this.value.set('');
  }
}

// libs/react/src/lib/chat/atl-chat.tsx
import {
  ChangeEvent,
  HTMLAttributes,
  KeyboardEvent,
  MouseEvent,
  ReactNode,
  TextareaHTMLAttributes,
  createContext,
  useContext,
  useEffect,
  useId,
  useRef,
  useState,
} from 'react';
import type {
  AtlChatMessageRole,
  AtlChatStatus,
  AtlChatVariant,
} from '../spec';
import './atl-chat.css';
import { AtlIcon } from '../icon/atl-icon';

interface ChatContextValue {
  headerId: string;
  status: AtlChatStatus;
  close: () => void;
  toggle: () => void;
}

const ChatContext = createContext<ChatContextValue>({
  headerId: '',
  status: 'idle',
  close: () => undefined,
  toggle: () => undefined,
});

/**
 * Properties for the AtlChat component.
 */
export interface AtlChatProps {
  /** Layout variant. */
  variant?: AtlChatVariant;
  /** Connection / response status. */
  status?: AtlChatStatus;
  /** Whether the chat is open (drawer / popup variants). */
  open?: boolean;
  /** Callback when open state should change. */
  onOpenChange?: (open: boolean) => void;
  children?: ReactNode;
}

/**
 * AI assistant surface. Three layout variants share the same content slots:
 * `drawer` (slide-in panel), `popup` (floating bubble + window), `inline`
 * (embedded card). Compose with `AtlChatHeader`, `AtlChatMessages`,
 * `AtlChatMessage`, `AtlChatTyping`, `AtlChatSuggestion`, `AtlChatInput`.
 */
export function AtlChat({
  variant = 'drawer',
  status = 'idle',
  open = false,
  onOpenChange,
  children,
}: AtlChatProps) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const headerId = useId();
  const triggerElRef = useRef<Element | null>(null);

  useEffect(() => {
    if (variant !== 'drawer') return;
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (open) {
      triggerElRef.current = document.activeElement;
      if (!dialog.open) dialog.showModal();
    } else {
      if (dialog.open) dialog.close();
      (triggerElRef.current as HTMLElement | null)?.focus();
      triggerElRef.current = null;
    }
  }, [open, variant]);

  // Auto-focus the input on open for drawer / popup. Inline keeps user focus.
  const hostRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!open) return;
    if (variant === 'inline') return;
    const host = hostRef.current;
    if (!host) return;
    requestAnimationFrame(() => {
      host.querySelector<HTMLTextAreaElement>('textarea')?.focus();
    });
  }, [open, variant]);

  useEffect(() => {
    if (variant !== 'drawer') return;
    const dialog = dialogRef.current;
    if (!dialog) return;
    const onClose = () => onOpenChange?.(false);
    const onCancel = (e: Event) => {
      e.preventDefault();
      onOpenChange?.(false);
    };
    dialog.addEventListener('close', onClose);
    dialog.addEventListener('cancel', onCancel);
    return () => {
      dialog.removeEventListener('close', onClose);
      dialog.removeEventListener('cancel', onCancel);
    };
  }, [onOpenChange, variant]);

  const handleBackdropClick = (e: MouseEvent<HTMLDialogElement>) => {
    if (e.target === dialogRef.current) onOpenChange?.(false);
  };

  const hostClass = [
    'atl-chat',
    `variant-${variant}`,
    `status-${status}`,
    open && 'is-open',
  ]
    .filter(Boolean)
    .join(' ');

  const ctx: ChatContextValue = {
    headerId,
    status,
    close: () => onOpenChange?.(false),
    toggle: () => onOpenChange?.(!open),
  };

  return (
    <ChatContext.Provider value={ctx}>
      <div ref={hostRef} className={hostClass}>
        {variant === 'drawer' && (
          <dialog
            ref={dialogRef}
            aria-labelledby={headerId}
            aria-modal="true"
            onClick={handleBackdropClick}
          >
            <div
              className="surface drawer-surface"
              onClick={(e) => e.stopPropagation()}
            >
              {children}
            </div>
          </dialog>
        )}
        {variant === 'popup' && (
          <>
            {open && (
              <div
                className="surface popup-surface"
                role="dialog"
                aria-labelledby={headerId}
              >
                {children}
              </div>
            )}
            <button
              type="button"
              className="fab-bubble"
              aria-label={open ? 'Close AI assistant' : 'Open AI assistant'}
              aria-expanded={open}
              onClick={() => onOpenChange?.(!open)}
            >
              <span aria-hidden="true">AI</span>
            </button>
          </>
        )}
        {variant === 'inline' && (
          <section
            className="surface inline-surface"
            aria-labelledby={headerId}
          >
            {children}
          </section>
        )}
      </div>
    </ChatContext.Provider>
  );
}

/**
 * Header slot for `AtlChat`. Holds the title block; the close button
 * is rendered automatically (hidden on the inline variant via CSS).
 */
export function AtlChatHeader({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement>) {
  const ctx = useContext(ChatContext);
  return (
    <div
      id={ctx.headerId}
      className={['atl-chat-header', className].filter(Boolean).join(' ')}
      {...rest}
    >
      <div className="title-block">{children}</div>
      <button
        type="button"
        className="close-btn"
        aria-label="Close chat"
        onClick={ctx.close}
      >
        <AtlIcon name="close" size="sm" />
      </button>
    </div>
  );
}

/**
 * Scrollable message list. Project `AtlChatMessage`, `AtlChatTyping`, or
 * `AtlChatSuggestion` children inside. Auto-scrolls to the bottom whenever
 * children are added or content changes — important for streaming responses
 * where new tokens are appended live.
 *
 * Renders `role="log"` (named, `aria-label="Conversation"`) with
 * `aria-live="polite"` on the root — the live region that announces new
 * messages without interrupting whatever the user is doing. `log` is not
 * `list`: an element carries exactly one role, so the projected
 * `AtlChatMessage` `listitem`s get their required list parent from a second,
 * nested element (`.messages-list`, `role="list"`) rather than from the log
 * root itself. That wrapper is `display: contents` so it never affects the
 * flex/gap layout of the messages — verified (Chromium, Firefox, WebKit): the
 * gap between messages is unchanged, and Chromium's native accessibility tree
 * shows `log "Conversation" > list "Messages" > listitem, listitem`.
 */
export function AtlChatMessages({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement>) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const stickToBottom = () => {
      el.scrollTop = el.scrollHeight;
    };
    stickToBottom();
    const observer = new MutationObserver(stickToBottom);
    observer.observe(el, {
      childList: true,
      subtree: true,
      characterData: true,
    });
    return () => observer.disconnect();
  }, []);
  return (
    <div
      ref={ref}
      role="log"
      aria-live="polite"
      aria-label="Conversation"
      className={['atl-chat-messages', className].filter(Boolean).join(' ')}
      {...rest}
    >
      <div className="messages-list" role="list" aria-label="Messages">
        {children}
      </div>
    </div>
  );
}

/**
 * A single chat message. Role drives bubble alignment and color.
 */
export interface AtlChatMessageProps extends HTMLAttributes<HTMLDivElement> {
  /** Sender of the message. */
  role?: AtlChatMessageRole;
  /** Marks the message as failed (red dashed border). */
  failed?: boolean;
}

export function AtlChatMessage({
  role = 'assistant',
  failed = false,
  children,
  className,
  ...rest
}: AtlChatMessageProps) {
  const classes = [
    'atl-chat-message',
    `role-${role}`,
    failed && 'is-failed',
    className,
  ]
    .filter(Boolean)
    .join(' ');
  return (
    <div role="listitem" className={classes} {...rest}>
      {children}
    </div>
  );
}

/**
 * Typing indicator (three animated dots).
 *
 * Two display modes:
 * - **Standalone bubble** (default) — render at the end of the message
 *   list to show "the assistant is starting to respond".
 * - **Inline cursor** (`inline`) — render as the LAST child INSIDE the
 *   currently-streaming `AtlChatMessage` so the dots read as a typing
 *   caret at the end of the partial text.
 */
export interface AtlChatTypingProps extends HTMLAttributes<HTMLDivElement> {
  /** When true, renders as an inline cursor without bubble chrome. */
  inline?: boolean;
}

export function AtlChatTyping({
  inline = false,
  className,
  ...rest
}: AtlChatTypingProps) {
  const classes = ['atl-chat-typing', inline && 'is-inline', className]
    .filter(Boolean)
    .join(' ');
  return (
    <div role="status" aria-live="polite" className={classes} {...rest}>
      <span className="dot" />
      <span className="dot" />
      <span className="dot" />
      <span className="sr-only">Assistant is typing</span>
    </div>
  );
}

/**
 * Tappable suggestion chip used in the empty state to seed a conversation.
 */
export interface AtlChatSuggestionProps {
  /** Primary label of the suggestion. */
  label: string;
  /** Optional secondary hint text. */
  hint?: string;
  /** Fires the label string when activated. */
  onSelected?: (label: string) => void;
  className?: string;
}

export function AtlChatSuggestion({
  label,
  hint,
  onSelected,
  className,
}: AtlChatSuggestionProps) {
  return (
    <div
      className={['atl-chat-suggestion', className].filter(Boolean).join(' ')}
    >
      <button
        type="button"
        className="chip"
        onClick={() => onSelected?.(label)}
      >
        <span className="chip-label">{label}</span>
        {hint && <span className="chip-hint">{hint}</span>}
      </button>
    </div>
  );
}

/**
 * Composable input footer for `AtlChat`. Wraps a textarea and emits
 * `onSend` (or `onStop` when the chat status is `'streaming'`).
 *
 * The action button automatically switches between primary "Send" and
 * danger "Stop" based on the parent chat's status.
 */
export interface AtlChatInputProps extends Omit<
  TextareaHTMLAttributes<HTMLTextAreaElement>,
  'onChange'
> {
  value?: string;
  onValueChange?: (value: string) => void;
  onSend?: (text: string) => void;
  onStop?: () => void;
  /** Accessible label for the input field. */
  ariaLabel?: string;
}

export function AtlChatInput({
  value,
  onValueChange,
  onSend,
  onStop,
  placeholder,
  ariaLabel = 'Message your AI assistant',
  ...rest
}: AtlChatInputProps) {
  const ctx = useContext(ChatContext);
  const isStreaming = ctx.status === 'streaming';
  const [internal, setInternal] = useState('');
  const isControlled = value !== undefined;
  const current = isControlled ? value : internal;

  const setCurrent = (next: string) => {
    if (!isControlled) setInternal(next);
    onValueChange?.(next);
  };

  const effectivePlaceholder =
    placeholder ??
    (isStreaming
      ? 'Waiting for response…'
      : ctx.status === 'error'
        ? 'Try again…'
        : 'Message your AI assistant…');

  const emitSend = () => {
    const text = current.trim();
    if (!text || isStreaming) return;
    onSend?.(text);
    setCurrent('');
  };

  const handleChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setCurrent(e.target.value);
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      emitSend();
    }
  };

  return (
    <div className="atl-chat-input">
      <textarea
        className="field"
        rows={1}
        value={current}
        placeholder={effectivePlaceholder}
        disabled={isStreaming}
        aria-label={ariaLabel}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        {...rest}
      />
      {isStreaming ? (
        <button
          type="button"
          className="action-btn variant-danger size-md"
          onClick={onStop}
        >
          Stop
        </button>
      ) : (
        <button
          type="button"
          className="action-btn variant-primary size-md"
          disabled={!current.trim()}
          onClick={emitSend}
        >
          Send
        </button>
      )}
    </div>
  );
}
