// libs/vue/src/lib/radio-group/llm-radio-group.vue
<script lang="ts">
import type { InjectionKey } from 'vue';

export interface LlmRadioGroupContext {
  value: string;
  name: string;
  disabled: boolean;
  readonly: boolean;
  invalid: boolean;
  onSelect: (value: string) => void;
}

export const LlmRadioGroupKey: InjectionKey<LlmRadioGroupContext> = Symbol('LlmRadioGroup');

export interface LlmRadioGroupProps {
  value?: string;
  name?: string;
  disabled?: boolean;
  readonly?: boolean;
  invalid?: boolean;
  required?: boolean;
  errors?: string[];
}
</script>

<script setup lang="ts">
import { computed, provide } from 'vue';
import './llm-radio-group.css';

defineOptions({ name: 'LlmRadioGroup' });

const props = withDefaults(defineProps<LlmRadioGroupProps>(), {
  value: '',
  name: '',
  disabled: false,
  readonly: false,
  invalid: false,
  required: false,
  errors: () => [],
});

const emit = defineEmits<{
  'update:value': [value: string];
}>();

provide(LlmRadioGroupKey, {
  get value() { return props.value ?? ''; },
  get name() { return props.name ?? ''; },
  get disabled() { return props.disabled ?? false; },
  get readonly() { return props.readonly ?? false; },
  get invalid() { return props.invalid ?? false; },
  onSelect(v: string) {
    if (!props.disabled && !props.readonly) {
      emit('update:value', v);
    }
  },
});

const classes = computed(() => [
  'llm-radio-group',
  props.invalid && 'is-invalid',
  props.disabled && 'is-disabled',
]);
</script>

<template>
  <div
    :class="classes"
    role="radiogroup"
    :aria-invalid="invalid || undefined"
    :aria-required="required || undefined"
  >
    <slot />
    <div v-if="errors.length > 0" class="errors" role="alert">
      <p v-for="(error, index) in errors" :key="index" class="error-message">{{ error }}</p>
    </div>
  </div>
</template>

// libs/llm-components-react/src/lib/radio-group/llm-radio-group.tsx
import { createContext, useContext, InputHTMLAttributes, ReactNode } from 'react';
import './llm-radio-group.css';

export interface RadioGroupContextValue {
  value: string;
  name: string;
  disabled: boolean;
  invalid: boolean;
  onSelect: (value: string) => void;
  onBlur: () => void;
}

export const RadioGroupContext = createContext<RadioGroupContextValue>({
  value: '',
  name: '',
  disabled: false,
  invalid: false,
  onSelect: () => {},
  onBlur: () => {},
});

export interface LlmRadioGroupProps extends Omit<InputHTMLAttributes<HTMLDivElement>, 'onChange'> {
  value?: string;
  onValueChange?: (value: string) => void;
  name?: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  errors?: string[];
  children?: ReactNode;
}

export function LlmRadioGroup({
  value = '',
  onValueChange,
  name = '',
  disabled = false,
  invalid = false,
  required = false,
  errors = [],
  children,
  className,
  ...rest
}: LlmRadioGroupProps) {
  const classes = [
    'llm-radio-group',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <RadioGroupContext.Provider
      value={{
        value,
        name,
        disabled,
        invalid,
        onSelect: (v) => !disabled && onValueChange?.(v),
        onBlur: () => {},
      }}
    >
      <div
        className={classes}
        role="radiogroup"
        aria-invalid={invalid || undefined}
        aria-required={required || undefined}
        {...rest}
      >
        {children}
        {errors.length > 0 && (
          <div className="errors" role="alert" aria-live="polite">
            {errors.map((err, i) => (
              <p key={i} className="error-message">
                {err}
              </p>
            ))}
          </div>
        )}
      </div>
    </RadioGroupContext.Provider>
  );
}

export function useRadioGroup(): RadioGroupContextValue {
  return useContext(RadioGroupContext);
}
