// libs/react/src/lib/skeleton/llm-skeleton.tsx
import { CSSProperties, HTMLAttributes } from 'react';
import type { LlmSkeletonSpec } from '../spec';
import './llm-skeleton.css';

/**
 * Properties for the LlmSkeleton component.
 */
export interface LlmSkeletonProps
  extends HTMLAttributes<HTMLDivElement>,
    LlmSkeletonSpec {
  /**
   * The visual style variant of the skeleton.
   */
  variant?: 'text' | 'circular' | 'rectangular';
  /**
   * The width of the skeleton.
   */
  width?: string;
  /**
   * The height of the skeleton.
   */
  height?: string;
  /**
   * Whether the skeleton should be animated.
   */
  animated?: boolean;
}

function computeHeight(variant: string, width: string, height?: string): string {
  if (height) return height;
  switch (variant) {
    case 'text':
      return '1em';
    case 'circular':
      return width;
    case 'rectangular':
      return '100px';
    default:
      return '1em';
  }
}

/**
 * A placeholder component used to represent content while it's loading.
 */
export function LlmSkeleton({
  variant = 'text',
  width = '100%',
  height,
  animated = true,
  className,
  style,
  ...rest
}: LlmSkeletonProps) {
  const classes = ['llm-skeleton', `variant-${variant}`, animated && 'is-animated', className]
    .filter(Boolean).join(' ');
  const computedHeight = computeHeight(variant, width, height);
  const inlineStyle: CSSProperties = { ...style, width, height: computedHeight };
  return <div className={classes} style={inlineStyle} aria-hidden="true" {...rest} />;
}

// libs/llm-components-angular/src/lib/skeleton/llm-skeleton.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

/**
 * Loading placeholder that mimics the shape of content while it loads.
 *
 * Usage:
 * ```html
 * <llm-skeleton />
 * <llm-skeleton variant="circular" width="40px" />
 * <llm-skeleton variant="rectangular" height="200px" />
 * ```
 */
@Component({
  selector: 'llm-skeleton',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: ``,
  styleUrl: './llm-skeleton.css',
  host: {
    '[class]': 'hostClasses()',
    '[style.width]': 'width()',
    '[style.height]': 'computedHeight()',
    'aria-hidden': 'true',
  },
})
export class LlmSkeleton {
  /** Shape variant of the skeleton placeholder. */
  readonly variant = input<'text' | 'circular' | 'rectangular'>('text');

  /** CSS width of the skeleton. */
  readonly width = input('100%');

  /** CSS height — when empty, a sensible default is chosen per variant. */
  readonly height = input('');

  /** Whether the shimmer animation is active. */
  readonly animated = input(true);

  protected readonly computedHeight = computed(() => {
    if (this.height()) return this.height();
    switch (this.variant()) {
      case 'text':
        return '1em';
      case 'circular':
        return this.width();
      case 'rectangular':
        return '100px';
    }
  });

  protected readonly hostClasses = computed(() => {
    const classes = [`variant-${this.variant()}`];
    if (this.animated()) classes.push('is-animated');
    return classes.join(' ');
  });
}
