// libs/angular/src/lib/dialog/atl-dialog.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  effect,
  inject,
  Injector,
  input,
  model,
  signal,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';
import { A11yModule } from '@angular/cdk/a11y';
import { ATL_DIALOG } from './atl-dialog.token';
import { isNgDevMode } from '../a11y-dev-warn';
import { AtlIcon } from '../icon/atl-icon';

let nextId = 0;

/**
 * Accessible modal dialog using the native `<dialog>` element.
 * Includes focus trap, Escape to close, backdrop click to close, and animation.
 * Compose with `atl-dialog-header`, `atl-dialog-content`, and `atl-dialog-footer`.
 *
 * Usage:
 * ```html
 * <atl-dialog [(open)]="isOpen">
 *   <atl-dialog-header>Dialog Title</atl-dialog-header>
 *   <atl-dialog-content>Dialog body content.</atl-dialog-content>
 *   <atl-dialog-footer>
 *     <atl-button variant="primary" (click)="isOpen = false">Confirm</atl-button>
 *   </atl-dialog-footer>
 * </atl-dialog>
 * ```
 */
@Component({
  selector: 'atl-dialog',
  standalone: true,
  imports: [A11yModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: ATL_DIALOG,
      useFactory: (dialog: AtlDialog) => ({
        headerId: dialog.headerId,
        close: () => dialog.open.set(false),
      }),
      deps: [AtlDialog],
    },
  ],
  template: `
    <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events, @angular-eslint/template/interactive-supports-focus -->
    <dialog
      #dialogEl
      class="atl-dialog"
      [attr.aria-label]="ariaLabel() || null"
      [attr.aria-labelledby]="ariaLabel() ? null : ariaLabelledby() || headerId"
      aria-modal="true"
      [cdkTrapFocus]="open()"
      (cancel)="onCancel($event)"
      (click)="onBackdropClick($event)"
    >
      <div [class]="panelClass()">
        <ng-content />
      </div>
    </dialog>
  `,
  // Class-rooted CSS shared with React and Vue (libs/styles). Unlike the other
  // components the root class `atl-dialog` is NOT put on this host: it belongs to
  // the inner <dialog class="atl-dialog"> (as in React and Vue), and the same
  // rules would turn this wrapper into `display: none; position: fixed`.
  // The header/content/footer slots below carry their own root classes and rely
  // on this component, which always contains them, to load the stylesheet.
  // eslint-disable-next-line @angular-eslint/use-component-view-encapsulation
  encapsulation: ViewEncapsulation.None,
  styleUrl: '../../../../styles/src/dialog/atl-dialog.css',
  host: {
    '[class]': 'hostClasses()',
    // Same defect as atl-input.ts's identical guards: a static aria-label="…"
    // or aria-labelledby="…" attribute on <atl-dialog> matches the aliased
    // input below AND stays on this host element too (Angular keeps static
    // attributes even when they also bind an input). The host is roleless
    // today, so an undefended attribute here is currently a no-op rather than
    // a live defect — but force it absent anyway so it stays that way once
    // this host ever gains a role, and so the aliased input unambiguously
    // means "the inner <dialog>'s accessible name" (ADR-0091).
    '[attr.aria-label]': 'null',
    '[attr.aria-labelledby]': 'null',
  },
})
export class AtlDialog {
  /** Whether the dialog is open. Supports two-way binding: [(open)]="isOpen". */
  readonly open = model(false);

  /** Whether clicking the backdrop closes the dialog. */
  readonly closeOnBackdrop = input(true);

  /** Size of the dialog panel. */
  readonly size = input<'sm' | 'md' | 'lg' | 'xl' | 'full'>('md');

  /** Accessible label for the dialog (use instead of aria-labelledby when no header is present). */
  readonly ariaLabel = input('', { alias: 'aria-label' });

  /** ID of the element that labels the dialog (defaults to the atl-dialog-header id). */
  readonly ariaLabelledby = input('', { alias: 'aria-labelledby' });

  /** @internal — referenced by AtlDialogHeader via ATL_DIALOG token */
  readonly headerId = `atl-dialog-header-${nextId}`;

  protected readonly dialogId = `atl-dialog-${nextId++}`;
  protected readonly dialogRef =
    viewChild<ElementRef<HTMLDialogElement>>('dialogEl');
  private readonly triggerEl = signal<HTMLElement | null>(null);
  private readonly injector = inject(Injector);
  private warnedUnnamed = false;

  protected readonly panelClass = computed(() => `panel size-${this.size()}`);
  protected readonly hostClasses = computed(() =>
    this.open() ? 'is-open' : '',
  );

  constructor() {
    effect(() => {
      const dialog = this.dialogRef()?.nativeElement;
      if (!dialog) return;
      if (this.open()) {
        this.triggerEl.set(document.activeElement as HTMLElement);
        dialog.showModal();
        this.warnIfUnnamed(dialog);
      } else {
        if (dialog.open) dialog.close();
        this.triggerEl()?.focus();
        this.triggerEl.set(null);
      }
    });
  }

  /**
   * Dev-mode warning, once per instance, when the dialog opens with nothing
   * naming it. Checked after render so a header projected later (or an
   * `aria-label` bound dynamically) has settled by then.
   */
  private warnIfUnnamed(dialog: HTMLDialogElement): void {
    if (!isNgDevMode() || this.warnedUnnamed) return;
    this.warnedUnnamed = true;
    afterNextRender(
      () => {
        const named =
          this.ariaLabel() !== '' ||
          this.ariaLabelledby() !== '' ||
          dialog.querySelector(`[id="${this.headerId}"]`) !== null;
        if (!named) {
          console.warn(
            '[AtlDialog] opened with no accessible name — ' +
              'add an <atl-dialog-header> or set [aria-label] / [aria-labelledby] so screen readers announce its purpose.',
            dialog,
          );
        }
      },
      { injector: this.injector },
    );
  }

  protected onCancel(event: Event): void {
    event.preventDefault();
    this.open.set(false);
  }

  protected onBackdropClick(event: MouseEvent): void {
    if (
      this.closeOnBackdrop() &&
      event.target === this.dialogRef()?.nativeElement
    ) {
      this.open.set(false);
    }
  }
}

/**
 * Header slot for `atl-dialog`. Renders above content with a bottom separator.
 * Automatically receives the correct `id` for `aria-labelledby` association.
 */
@Component({
  selector: 'atl-dialog-header',
  standalone: true,
  imports: [AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-content />
    <button
      class="close-btn"
      type="button"
      aria-label="Close dialog"
      (click)="context.close()"
    >
      <atl-icon name="close" size="sm" />
    </button>
  `,
  host: {
    class: 'atl-dialog-header',
    '[attr.id]': 'context.headerId',
  },
})
export class AtlDialogHeader {
  protected readonly context = inject(ATL_DIALOG);
}

/**
 * Content slot for `atl-dialog`. Scrollable primary content area.
 */
@Component({
  selector: 'atl-dialog-content',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'atl-dialog-content' },
})
export class AtlDialogContent {}

/**
 * Footer slot for `atl-dialog`. Renders below content, typically holds action buttons.
 */
@Component({
  selector: 'atl-dialog-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: { class: 'atl-dialog-footer' },
})
export class AtlDialogFooter {}

// libs/vue/src/lib/dialog/atl-dialog.vue
<script lang="ts">
import type { InjectionKey } from 'vue';

export interface AtlDialogContext {
  headerId: string;
  close: () => void;
}

export const AtlDialogKey: InjectionKey<AtlDialogContext> = Symbol('AtlDialog');

export interface AtlDialogProps {
  /** Whether the dialog is open. Two-way bound via `v-model:open` (emits `update:open`). */
  open?: boolean;
  /** Whether clicking the backdrop closes the dialog. */
  closeOnBackdrop?: boolean;
  /** Size of the dialog panel. */
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  /** Accessible label for the dialog; use it instead of a header when none is present. When set, it replaces the header as the dialog's accessible name. */
  ariaLabel?: string;
  // `aria-labelledby` is deliberately not declared: a caller's `aria-labelledby` attribute
  // falls through to the <dialog> and overrides the header id used as the default, the
  // way Angular's `aria-labelledby` input and React's `aria-labelledby` prop do.
}
</script>

<script setup lang="ts">
import { computed, nextTick, onMounted, provide, ref, useId, watch } from 'vue';
import { isDevBuild } from '../a11y-dev-warn';
import '@atelier-ui/styles/dialog/atl-dialog.css';

defineOptions({ name: 'AtlDialog' });

const props = withDefaults(defineProps<AtlDialogProps>(), {
  open: false,
  closeOnBackdrop: true,
  size: 'md',
  ariaLabel: undefined,
});

const emit = defineEmits<{
  'update:open': [open: boolean];
}>();

const dialogRef = ref<HTMLDialogElement | null>(null);
const headerId = useId();

let warnedUnnamed = false;

// Dev-mode warning, once per instance, when the dialog opens with nothing naming
// it: no header in the slot and no aria-label / aria-labelledby override. Checked
// after the next tick so a header rendered later has settled.
function warnIfUnnamed() {
  const dialog = dialogRef.value;
  if (!isDevBuild() || warnedUnnamed || !dialog) return;
  warnedUnnamed = true;
  void nextTick(() => {
    const named =
      props.ariaLabel ||
      dialog.getAttribute('aria-labelledby') !== headerId ||
      dialog.querySelector(`[id="${headerId}"]`) !== null;
    if (!named) {
      console.warn(
        '[AtlDialog] opened with no accessible name — ' +
          'add an <atl-dialog-header> or set aria-label / aria-labelledby so screen readers announce its purpose.',
        dialog,
      );
    }
  });
}

function close() {
  emit('update:open', false);
}

provide(AtlDialogKey, {
  headerId,
  close,
});

onMounted(() => {
  if (props.open && dialogRef.value) {
    dialogRef.value.showModal();
    warnIfUnnamed();
  }
});

watch(
  () => props.open,
  (isOpen) => {
    const dialog = dialogRef.value;
    if (!dialog) return;
    if (isOpen) {
      if (!dialog.open) dialog.showModal();
      warnIfUnnamed();
    } else {
      if (dialog.open) dialog.close();
    }
  },
  { flush: 'post' },
);

function onDialogClose() {
  emit('update:open', false);
}

function onDialogCancel(event: Event) {
  event.preventDefault();
  emit('update:open', false);
}

function onBackdropClick(event: MouseEvent) {
  if (props.closeOnBackdrop && event.target === dialogRef.value) {
    emit('update:open', false);
  }
}

const panelClasses = computed(() => ['panel', `size-${props.size}`]);
</script>

<template>
  <!-- Backdrop-click-to-close on a native <dialog>: keyboard users already
  have a keyboard-equivalent close path via the native Escape key, wired
  through @cancel/@close below — the click handler is a pointer-only
  convenience on top of that, not the only way to dismiss the dialog. -->
  <!-- eslint-disable-next-line vuejs-accessibility/click-events-have-key-events, vuejs-accessibility/no-static-element-interactions -->
  <dialog
    ref="dialogRef"
    class="atl-dialog"
    :aria-label="ariaLabel || undefined"
    :aria-labelledby="!ariaLabel ? headerId : undefined"
    aria-modal="true"
    @close="onDialogClose"
    @cancel="onDialogCancel"
    @click="onBackdropClick"
  >
    <div :class="panelClasses" @click.stop>
      <slot />
    </div>
  </dialog>
</template>
