// libs/angular/src/lib/textarea/atl-textarea.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
} from '@angular/core';
import { TextFieldModule } from '@angular/cdk/text-field';
import type { FormValueControl } from '@angular/forms/signals';
import { type ValidationError, type WithOptionalFieldTree } from '@angular/forms/signals';
import { AtlIcon } from '../icon/atl-icon';

let nextId = 0;

/**
 * Accessible multiline text input component for use with Angular Signal Forms.
 *
 * Usage:
 * ```html
 * <atl-textarea placeholder="Enter a description" [(value)]="description" />
 * <atl-textarea [formField]="form.bio" [rows]="4" />
 * ```
 */
@Component({
  selector: 'atl-textarea',
  standalone: true,
  imports: [TextFieldModule, AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="textarea-field">
      <textarea
        [value]="value()"
        (input)="onInput($event)"
        (blur)="touched.set(true)"
        [disabled]="disabled()"
        [readOnly]="readonly()"
        [placeholder]="placeholder()"
        [rows]="rows()"
        [attr.name]="name() || null"
        [attr.aria-invalid]="invalid() || null"
        [attr.aria-required]="required() || null"
        [attr.aria-describedby]="showErrors() ? errorId : null"
        [cdkTextareaAutosize]="autoResize()"
        [cdkAutosizeMinRows]="rows()"
      ></textarea>
      @if (invalid()) {
        <atl-icon name="danger" size="sm" class="invalid-icon" />
      }
    </div>
    @if (showErrors()) {
      <div class="errors" [id]="errorId" aria-live="polite">
        @for (error of errors(); track error.kind) {
          <p class="error-message">{{ error.message }}</p>
        }
      </div>
    }
  `,
  styleUrl: './atl-textarea.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class AtlTextarea implements FormValueControl<string> {
  /** The current textarea value. Supports [(value)] two-way binding. */
  readonly value = model('');

  /** Number of visible text rows. */
  readonly rows = input(3);

  /** Placeholder text shown when the textarea is empty. */
  readonly placeholder = input('');

  /** Whether the textarea is disabled. Bound by [formField] directive. */
  readonly disabled = input(false);

  /** Whether the textarea is read-only. Bound by [formField] directive. */
  readonly readonly = input(false);

  /** Whether the textarea has validation errors. Bound by [formField] directive. */
  readonly invalid = input(false);

  /** Validation errors from the form system. Bound by [formField] directive. */
  readonly errors = input<readonly WithOptionalFieldTree<ValidationError>[]>([]);

  /** Whether the user has interacted with the textarea. Bound by [formField] directive. */
  readonly touched = model(false);

  /** Whether the textarea is required. Bound by [formField] directive. */
  readonly required = input(false);

  /** The textarea's name attribute. Bound by [formField] directive. */
  readonly name = input('');

  /** Whether to auto-resize the textarea height to fit its content. */
  readonly autoResize = input(false);

  /** @internal */
  protected readonly errorId = `atl-textarea-errors-${nextId++}`;

  /** @internal */
  protected readonly showErrors = computed(
    () => this.touched() && this.invalid() && this.errors().length > 0
  );

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.disabled()) classes.push('is-disabled');
    if (this.invalid()) classes.push('is-invalid');
    if (this.readonly()) classes.push('is-readonly');
    if (this.touched()) classes.push('is-touched');
    if (this.autoResize()) classes.push('is-auto-resize');
    return classes.join(' ');
  });

  /** @internal */
  protected onInput(event: Event): void {
    const target = event.target as HTMLTextAreaElement;
    this.value.set(target.value);
  }
}

// libs/react/src/lib/textarea/atl-textarea.tsx
import { TextareaHTMLAttributes, useRef, useEffect, useId } from 'react';
import type { AtlTextareaSpec } from '../spec';
import '@atelier-ui/styles/textarea/atl-textarea.css';
import { AtlIcon } from '../icon/atl-icon';

/**
 * Properties for the AtlTextarea component.
 */
export interface AtlTextareaProps
  extends
    Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'readOnly'>,
    AtlTextareaSpec {
  /**
   * Whether the textarea is disabled.
   */
  disabled?: boolean;
  /**
   * Whether the textarea has validation errors.
   */
  invalid?: boolean;
  /**
   * Whether the textarea is required.
   */
  required?: boolean;
  /**
   * The textarea's name attribute, used for form submission.
   */
  name?: string;
  /**
   * Lowercase alias of `readOnly`: whether the textarea is read-only. `readOnly` wins when both are set.
   */
  readonly?: boolean;
  /**
   * Number of visible text rows.
   */
  rows?: number;
  /**
   * Placeholder text shown when the textarea is empty.
   */
  placeholder?: string;
  /**
   * Whether the textarea height grows automatically to fit its content.
   */
  autoResize?: boolean;
  /**
   * Current value of the textarea.
   */
  value?: string;
  /**
   * Whether the textarea is read-only.
   */
  readOnly?: boolean;
  /**
   * Callback fired when the value changes.
   */
  onValueChange?: (value: string) => void;
  /**
   * List of error messages to display.
   */
  errors?: string[];
  /**
   * Label text for the textarea.
   */
  label?: string;
}

/**
 * A multi-line text input component that supports automatic resizing and validation states.
 */
export function AtlTextarea({
  value,
  onChange,
  onValueChange,
  invalid = false,
  errors = [],
  disabled = false,
  readOnly: reactReadOnly,
  readonly: specReadOnly,
  required = false,
  label,
  autoResize = false,
  rows = 3,
  className,
  id,
  ...rest
}: AtlTextareaProps) {
  const readOnly = reactReadOnly ?? specReadOnly ?? false;
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  // useId(), not a slug derived from the label text: two textareas with the
  // same label used to collide on one id and break the for/id association
  // (same bug as AtlInput's — see ADR-0091).
  const generatedId = useId();
  const inputId = id || (label ? `textarea-${generatedId}` : undefined);
  const classes = [
    'atl-textarea',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    readOnly && 'is-readonly',
    autoResize && 'is-auto-resize',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  useEffect(() => {
    if (autoResize && textareaRef.current) {
      const el = textareaRef.current;
      el.style.height = 'auto';
      el.style.height = `${el.scrollHeight}px`;
    }
  }, [value, autoResize]);

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onChange?.(e);
    onValueChange?.(e.target.value);
    if (autoResize && textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  };

  const errorId = inputId ? `${inputId}-errors` : undefined;

  return (
    <div className={classes}>
      {label && <label htmlFor={inputId}>{label}</label>}
      <div className="textarea-field">
        <textarea
          ref={textareaRef}
          id={inputId}
          value={value}
          onChange={handleChange}
          disabled={disabled}
          readOnly={readOnly}
          required={required}
          rows={rows}
          aria-invalid={invalid || undefined}
          aria-required={required || undefined}
          aria-describedby={errors.length > 0 ? errorId : undefined}
          {...rest}
        />
        {invalid && (
          <AtlIcon name="danger" size="sm" className="invalid-icon" />
        )}
      </div>
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}
