// libs/vue/src/lib/textarea/atl-textarea.vue
<script setup lang="ts">
import { ref, watch, onMounted, computed, nextTick, useId } from 'vue';
import '@atelier-ui/styles/textarea/atl-textarea.css';
import { warnIfUnnamedControl } from '../a11y-dev-warn';
import AtlIcon from '../icon/atl-icon.vue';
import type { AtlErrorItem } from '../spec';
import { errorMessage } from '../error-message';

defineOptions({ name: 'AtlTextarea' });

interface AtlTextareaProps {
  /** The current textarea value. Two-way bound via `v-model:value` (emits `update:value`). */
  value?: string;
  /** Number of visible text rows. */
  rows?: number;
  /** Placeholder text shown when the textarea is empty. */
  placeholder?: string;
  /** Whether the textarea has validation errors; sets `aria-invalid`. */
  invalid?: boolean;
  /** Validation error messages shown below the control and linked to it via `aria-describedby`. */
  errors?: ReadonlyArray<string | AtlErrorItem>;
  /** Whether the textarea is disabled. */
  disabled?: boolean;
  /** Whether the textarea is read-only. */
  readonly?: boolean;
  /** Whether the textarea is required. */
  required?: boolean;
  /** Visible caption rendered as a `<label>` associated with the textarea. Omit it when the field is named some other way (an external `<label>`, or `aria-label`); without one of these the textarea has no accessible name. */
  label?: string;
  /** Whether the textarea height grows automatically to fit its content. */
  autoResize?: boolean;
  /** The textarea's `name` attribute. */
  name?: string;
  /** Explicit id for the native textarea. Wins over the auto-generated id, so an external `<label for>` or `aria-describedby` can point at it. */
  id?: string;
  /**
   * Accessible name for the native textarea, for when there is no visible
   * `label`. Declared as an explicit prop (not left to Vue's default
   * attribute fallthrough) so it lands on the native `<textarea>` — the
   * fallthrough target for an undeclared attribute is this component's
   * root `<div>`, which has no role and would leave the textarea unnamed.
   * camelCase here, like every other prop — see AtlInput's identical
   * `ariaLabel` for why (Vue camelizes both sides of prop-name matching, so
   * `props['aria-label']` in the script is never populated).
   */
  ariaLabel?: string;
}

const props = withDefaults(defineProps<AtlTextareaProps>(), {
  value: '',
  rows: 3,
  placeholder: '',
  invalid: false,
  errors: () => [],
  disabled: false,
  readonly: false,
  required: false,
  label: '',
  autoResize: false,
  name: '',
  id: '',
  ariaLabel: '',
});

const errorsId = useId();
// useId(), not Math.random(): a random id inside a computed() re-rolls on
// every re-evaluation and differs between server and client render, breaking
// SSR hydration (same bug as AtlInput's — see ADR-0091).
const generatedId = useId();

const emit = defineEmits<{
  'update:value': [value: string];
}>();

const textareaRef = ref<HTMLTextAreaElement | null>(null);

const textareaId = computed(
  () => props.id || (props.label ? `textarea-${generatedId}` : undefined),
);

function adjustHeight() {
  if (props.autoResize && textareaRef.value) {
    textareaRef.value.style.height = 'auto';
    textareaRef.value.style.height = `${textareaRef.value.scrollHeight}px`;
  }
}

watch(
  () => props.value,
  async () => {
    await nextTick();
    adjustHeight();
  },
);

onMounted(() => {
  adjustHeight();
  warnIfUnnamedControl(
    textareaRef.value,
    'AtlTextarea',
    'set label or aria-label, or associate a <label for> with the textarea id',
  );
});

function onInput(event: Event) {
  emit('update:value', (event.target as HTMLTextAreaElement).value);
  adjustHeight();
}
</script>

<template>
  <div
    class="atl-textarea"
    :class="{
      'is-invalid': invalid,
      'is-disabled': disabled,
      'is-readonly': readonly,
      'is-auto-resize': autoResize,
    }"
  >
    <label v-if="label" :for="textareaId">{{ label }}</label>
    <div class="textarea-field">
      <textarea
        :id="textareaId"
        ref="textareaRef"
        :value="value"
        :rows="rows"
        :placeholder="placeholder"
        :disabled="disabled"
        :readonly="readonly"
        :required="required"
        :name="name"
        :aria-label="ariaLabel || undefined"
        :aria-invalid="invalid || undefined"
        :aria-describedby="errors.length > 0 ? errorsId : undefined"
        @input="onInput"
      />
      <AtlIcon v-if="invalid" name="danger" size="sm" class="invalid-icon" />
    </div>
    <div v-if="errors.length" :id="errorsId" class="errors" aria-live="polite">
      <p v-for="(error, i) in errors" :key="i" class="error-message">
        {{ errorMessage(error) }}
      </p>
    </div>
  </div>
</template>

// libs/react/src/lib/textarea/atl-textarea.tsx
import { TextareaHTMLAttributes, useRef, useEffect, useId } from 'react';
import type { AtlTextareaSpec, AtlErrorItem } from '../spec';
import '@atelier-ui/styles/textarea/atl-textarea.css';
import { AtlIcon } from '../icon/atl-icon';
import { errorMessage } from '../error-message';

/**
 * Properties for the AtlTextarea component.
 */
export interface AtlTextareaProps
  extends
    Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'readOnly'>,
    AtlTextareaSpec {
  /**
   * Whether the textarea is disabled.
   */
  disabled?: boolean;
  /**
   * Whether the textarea has validation errors.
   */
  invalid?: boolean;
  /**
   * Whether the textarea is required.
   */
  required?: boolean;
  /**
   * The textarea's name attribute, used for form submission.
   */
  name?: string;
  /**
   * Lowercase alias of `readOnly`: whether the textarea is read-only. `readOnly` wins when both are set.
   */
  readonly?: boolean;
  /**
   * Number of visible text rows.
   */
  rows?: number;
  /**
   * Placeholder text shown when the textarea is empty.
   */
  placeholder?: string;
  /**
   * Whether the textarea height grows automatically to fit its content.
   */
  autoResize?: boolean;
  /**
   * Current value of the textarea.
   */
  value?: string;
  /**
   * Whether the textarea is read-only.
   */
  readOnly?: boolean;
  /**
   * Callback fired when the value changes.
   */
  onValueChange?: (value: string) => void;
  /**
   * List of error messages to display.
   */
  errors?: ReadonlyArray<string | AtlErrorItem>;
  /**
   * Label text for the textarea.
   */
  label?: string;
}

/**
 * A multi-line text input component that supports automatic resizing and validation states.
 */
export function AtlTextarea({
  value,
  onChange,
  onValueChange,
  invalid = false,
  errors = [],
  disabled = false,
  readOnly: reactReadOnly,
  readonly: specReadOnly,
  required = false,
  label,
  autoResize = false,
  rows = 3,
  className,
  id,
  ...rest
}: AtlTextareaProps) {
  const readOnly = reactReadOnly ?? specReadOnly ?? false;
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  // useId(), not a slug derived from the label text: two textareas with the
  // same label used to collide on one id and break the for/id association
  // (same bug as AtlInput's — see ADR-0091).
  const generatedId = useId();
  const inputId = id || (label ? `textarea-${generatedId}` : undefined);
  const classes = [
    'atl-textarea',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    readOnly && 'is-readonly',
    autoResize && 'is-auto-resize',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  useEffect(() => {
    if (autoResize && textareaRef.current) {
      const el = textareaRef.current;
      el.style.height = 'auto';
      el.style.height = `${el.scrollHeight}px`;
    }
  }, [value, autoResize]);

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onChange?.(e);
    onValueChange?.(e.target.value);
    if (autoResize && textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  };

  const errorId = inputId ? `${inputId}-errors` : undefined;

  return (
    <div className={classes}>
      {label && <label htmlFor={inputId}>{label}</label>}
      <div className="textarea-field">
        <textarea
          ref={textareaRef}
          id={inputId}
          value={value}
          onChange={handleChange}
          disabled={disabled}
          readOnly={readOnly}
          required={required}
          rows={rows}
          aria-invalid={invalid || undefined}
          aria-required={required || undefined}
          aria-describedby={errors.length > 0 ? errorId : undefined}
          {...rest}
        />
        {invalid && (
          <AtlIcon name="danger" size="sm" className="invalid-icon" />
        )}
      </div>
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {errorMessage(err)}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}
