// libs/vue/src/lib/progress/llm-progress.vue
<script setup lang="ts">
import { computed } from 'vue';
import './llm-progress.css';

defineOptions({ name: 'LlmProgress' });

interface LlmProgressProps {
  value?: number;
  max?: number;
  variant?: 'default' | 'success' | 'warning' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  indeterminate?: boolean;
  /**
   * Accessible name — rendered as `aria-label` on the host.
   * Required by ARIA when there is no visible label nearby.
   */
  label?: string;
}

const props = withDefaults(defineProps<LlmProgressProps>(), {
  value: 0,
  max: 100,
  variant: 'default',
  size: 'md',
  indeterminate: false,
  label: undefined,
});

const clampedValue = computed(() => Math.min(Math.max(props.value, 0), props.max));

const fillWidth = computed(() =>
  props.indeterminate ? '100%' : `${(clampedValue.value / props.max) * 100}%`
);

const classes = computed(() => [
  'llm-progress',
  `variant-${props.variant}`,
  `size-${props.size}`,
  props.indeterminate && 'is-indeterminate',
].filter(Boolean));
</script>

<template>
  <div
    :class="classes"
    role="progressbar"
    :aria-label="label"
    :aria-valuemin="0"
    :aria-valuenow="indeterminate ? undefined : clampedValue"
    :aria-valuemax="indeterminate ? undefined : max"
  >
    <div class="track">
      <div class="fill" :style="{ width: fillWidth }" />
    </div>
  </div>
</template>

// libs/angular/src/lib/progress/llm-progress.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

/**
 * Progress bar with determinate and indeterminate states.
 *
 * Usage:
 * ```html
 * <llm-progress [value]="75" />
 * <llm-progress variant="success" [value]="100" />
 * <llm-progress [indeterminate]="true" />
 * ```
 */
@Component({
  selector: 'llm-progress',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="track">
      <div class="fill" [style.width]="fillWidth()"></div>
    </div>
  `,
  styleUrl: './llm-progress.css',
  host: {
    role: 'progressbar',
    'aria-valuemin': '0',
    '[attr.aria-valuenow]': 'indeterminate() ? null : clampedValue()',
    '[attr.aria-valuemax]': 'indeterminate() ? null : max()',
    '[attr.aria-label]': 'label() || null',
    '[class]': 'hostClasses()',
  },
})
export class LlmProgress {
  /** Current value of the progress bar. */
  readonly value = input<number>(0);

  /** Maximum value. */
  readonly max = input<number>(100);

  /** Semantic color variant. */
  readonly variant = input<'default' | 'success' | 'warning' | 'danger'>('default');

  /** Height size of the track. */
  readonly size = input<'sm' | 'md' | 'lg'>('md');

  /** Shows an animated indeterminate state (loading). */
  readonly indeterminate = input(false);

  /**
   * Accessible name — rendered as `aria-label` on the host.
   * Required by ARIA when there is no visible label nearby.
   */
  readonly label = input<string | undefined>(undefined);

  protected readonly clampedValue = computed(() =>
    Math.min(Math.max(this.value(), 0), this.max())
  );

  protected readonly fillWidth = computed(() =>
    this.indeterminate()
      ? '100%'
      : `${(this.clampedValue() / this.max()) * 100}%`
  );

  protected readonly hostClasses = computed(
    () =>
      `variant-${this.variant()} size-${this.size()}${this.indeterminate() ? ' is-indeterminate' : ''}`
  );
}
