// libs/react/src/lib/combobox/llm-combobox.tsx
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import type { LlmComboboxOption, LlmComboboxSpec } from '../spec';
import './llm-combobox.css';

export type { LlmComboboxOption };

export interface LlmComboboxProps extends LlmComboboxSpec {
  value?: string;
  onValueChange?: (value: string) => void;
  errors?: string[];
}

/**
 * Filterable autocomplete combobox. Accepts an `options` array and emits the
 * selected option's `value`. The user types to narrow the list; selecting an
 * option commits the value and displays its label.
 *
 * Usage:
 * ```tsx
 * <LlmCombobox
 *   value={country}
 *   onValueChange={setCountry}
 *   options={countryOptions}
 *   placeholder="Search country…"
 * />
 * ```
 */
export function LlmCombobox({
  value = '',
  onValueChange,
  options = [],
  placeholder = '',
  disabled = false,
  readonly = false,
  invalid = false,
  required = false,
  name,
  errors = [],
}: LlmComboboxProps) {
  const [query, setQuery] = useState('');
  const [isOpen, setIsOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);

  const inputRef = useRef<HTMLInputElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const inputId = useId();
  const panelId = useId();

  const selectedLabel = useMemo(
    () => options.find((o) => o.value === value)?.label ?? '',
    [options, value],
  );

  const filteredOptions = useMemo(() => {
    if (!query) return options;
    const q = query.toLowerCase();
    return options.filter((o) => o.label.toLowerCase().includes(q));
  }, [options, query]);

  const displayValue = isOpen ? query : selectedLabel;

  // Outside-click closes panel
  useEffect(() => {
    if (!isOpen) return;
    function handleClick(e: MouseEvent) {
      if (!containerRef.current?.contains(e.target as Node)) {
        setIsOpen(false);
        setQuery(selectedLabel);
      }
    }
    document.addEventListener('click', handleClick);
    return () => document.removeEventListener('click', handleClick);
  }, [isOpen, selectedLabel]);

  function open() {
    if (disabled || readonly) return;
    setQuery(selectedLabel);
    setIsOpen(true);
    setActiveIndex(-1);
  }

  function close() {
    setIsOpen(false);
    setActiveIndex(-1);
  }

  function selectOption(option: LlmComboboxOption) {
    if (option.disabled || disabled || readonly) return;
    onValueChange?.(option.value);
    setQuery(option.label);
    close();
    inputRef.current?.focus();
  }

  function handleInput(e: React.ChangeEvent<HTMLInputElement>) {
    const q = e.target.value;
    setQuery(q);
    setActiveIndex(-1);
    if (q === '') onValueChange?.('');
    if (!isOpen) open();
  }

  function handleFocus() {
    open();
  }

  function handleBlur() {
    setQuery(selectedLabel);
  }

  function handleKeydown(e: React.KeyboardEvent) {
    switch (e.key) {
      case 'ArrowDown': {
        e.preventDefault();
        if (!isOpen) { open(); return; }
        setActiveIndex((i) => (i + 1 >= filteredOptions.length ? 0 : i + 1));
        break;
      }
      case 'ArrowUp': {
        e.preventDefault();
        if (!isOpen) { open(); return; }
        setActiveIndex((i) => (i - 1 < 0 ? filteredOptions.length - 1 : i - 1));
        break;
      }
      case 'Enter': {
        e.preventDefault();
        if (isOpen && activeIndex >= 0 && activeIndex < filteredOptions.length) {
          selectOption(filteredOptions[activeIndex]);
        }
        break;
      }
      case 'Escape': {
        e.preventDefault();
        setQuery(selectedLabel);
        close();
        break;
      }
      case 'Tab': {
        close();
        break;
      }
    }
  }

  const classes = [
    'llm-combobox',
    isOpen && 'is-open',
    disabled && 'is-disabled',
    invalid && 'is-invalid',
  ]
    .filter(Boolean)
    .join(' ');

  const activeOptionId =
    activeIndex >= 0 ? `${panelId}-option-${activeIndex}` : undefined;

  return (
    <div className={classes} ref={containerRef}>
      <div className="llm-combobox-wrapper">
        <input
          ref={inputRef}
          className="llm-combobox-input"
          type="text"
          autoComplete="off"
          role="combobox"
          id={inputId}
          aria-expanded={isOpen}
          aria-controls={panelId}
          aria-autocomplete="list"
          aria-activedescendant={activeOptionId}
          aria-invalid={invalid || undefined}
          disabled={disabled}
          readOnly={readonly}
          required={required}
          name={name}
          placeholder={placeholder}
          value={displayValue}
          onChange={handleInput}
          onFocus={handleFocus}
          onBlur={handleBlur}
          onKeyDown={handleKeydown}
        />
        <span className="llm-combobox-icon" aria-hidden="true">
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
            <path d="M2 4l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </span>
      </div>

      {isOpen && (
        <ul
          id={panelId}
          className="llm-combobox-panel"
          role="listbox"
          aria-labelledby={inputId}
        >
          {filteredOptions.length > 0 ? (
            filteredOptions.map((option, i) => (
              <li
                key={option.value}
                id={`${panelId}-option-${i}`}
                role="option"
                className={[
                  'llm-combobox-option',
                  activeIndex === i && 'is-active',
                  option.value === value && 'is-selected',
                  option.disabled && 'is-disabled',
                ]
                  .filter(Boolean)
                  .join(' ')}
                aria-selected={option.value === value}
                aria-disabled={option.disabled || undefined}
                onMouseDown={() => selectOption(option)}
                onMouseEnter={() => setActiveIndex(i)}
              >
                <span>{option.label}</span>
                {option.value === value && (
                  <svg className="llm-combobox-check" width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                    <path d="M2 7l4 4 6-7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                )}
              </li>
            ))
          ) : (
            <li className="llm-combobox-no-results" role="option" aria-selected={false} aria-disabled="true">
              No results found.
            </li>
          )}
        </ul>
      )}

      {invalid && errors.length > 0 && (
        <div className="llm-combobox-errors" role="alert" aria-live="polite">
          {errors.map((e, i) => (
            <p key={i} className="llm-combobox-error-message">{e}</p>
          ))}
        </div>
      )}
    </div>
  );
}

// libs/angular/src/lib/combobox/llm-combobox.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  inject,
  input,
  model,
  signal,
  viewChild,
} from '@angular/core';
import type { FormValueControl } from '@angular/forms/signals';
import { type ValidationError, type WithOptionalFieldTree } from '@angular/forms/signals';
import type { LlmComboboxOption } from '../spec';

let nextId = 0;

/**
 * Filterable autocomplete combobox. Accepts an `options` array and emits the
 * selected option's `value`. The user types to narrow the list; selecting an
 * option commits the value and displays its label.
 *
 * Usage:
 * ```html
 * <llm-combobox
 *   [(value)]="country"
 *   [options]="countryOptions"
 *   placeholder="Search country…"
 * />
 *
 * <!-- With Signal Forms -->
 * <llm-combobox [formField]="form.country" [options]="countryOptions" />
 * ```
 */
@Component({
  selector: 'llm-combobox',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="combobox-wrapper">
      <input
        #inputEl
        class="combobox-input"
        type="text"
        autocomplete="off"
        role="combobox"
        [id]="inputId"
        [attr.aria-expanded]="isOpen()"
        [attr.aria-controls]="panelId"
        aria-autocomplete="list"
        [attr.aria-activedescendant]="activeOptionId()"
        [attr.aria-invalid]="invalid() || null"
        [attr.disabled]="disabled() || null"
        [attr.required]="required() || null"
        [attr.name]="name() || null"
        [placeholder]="placeholder()"
        [value]="query()"
        (input)="onInput($event)"
        (focus)="onFocus()"
        (blur)="onBlur()"
        (keydown)="onKeydown($event)"
      />
      <span class="combobox-icon" aria-hidden="true">
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
          <path d="M2 4l4 4 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </span>
    </div>

    <ul
      #panel
      [id]="panelId"
      popover="manual"
      role="listbox"
      class="panel"
      [attr.aria-labelledby]="inputId"
    >
      @for (option of filteredOptions(); track option.value; let i = $index) {
        <li
          [id]="optionId(i)"
          role="option"
          class="option"
          [class.is-active]="activeIndex() === i"
          [class.is-selected]="option.value === value()"
          [class.is-disabled]="option.disabled"
          [attr.aria-selected]="option.value === value()"
          [attr.aria-disabled]="option.disabled || null"
          (mousedown)="onOptionSelect(option)"
          (mouseenter)="activeIndex.set(i)"
        >
          <span>{{ option.label }}</span>
          @if (option.value === value()) {
            <svg class="option-check" width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
              <path d="M2 7l4 4 6-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          }
        </li>
      }
      @if (filteredOptions().length === 0) {
        <li class="no-results" role="option" aria-selected="false" aria-disabled="true">No results found.</li>
      }
    </ul>

    @if (showErrors()) {
      <div class="errors" [id]="errorId" aria-live="polite">
        @for (error of errors(); track error.kind) {
          <p class="error-message">{{ error.message }}</p>
        }
      </div>
    }
  `,
  styleUrl: './llm-combobox.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class LlmCombobox implements FormValueControl<string> {
  /** The selected value. Supports [(value)] two-way binding and [formField] directive. */
  readonly value = model('');

  /** Whether the user has interacted. Bound by [formField] directive. */
  readonly touched = model(false);

  /** Options to display and filter. */
  readonly options = input<LlmComboboxOption[]>([]);

  /** Placeholder text for the input. */
  readonly placeholder = input('');

  /** Whether the combobox is disabled. */
  readonly disabled = input(false);

  /** Whether the combobox has validation errors. */
  readonly invalid = input(false);

  /** Whether the combobox is required. */
  readonly required = input(false);

  /** The input's name attribute. */
  readonly name = input('');

  /** Validation errors from the form system. */
  readonly errors = input<readonly WithOptionalFieldTree<ValidationError>[]>([]);

  /** @internal */
  protected readonly query = signal('');

  /** @internal */
  protected readonly isOpen = signal(false);

  /** @internal */
  protected readonly activeIndex = signal(-1);

  /** @internal */
  protected readonly panelRef = viewChild<ElementRef<HTMLElement>>('panel');

  /** @internal */
  protected readonly inputEl = viewChild<ElementRef<HTMLInputElement>>('inputEl');

  /** @internal */
  protected readonly inputId = `llm-combobox-input-${nextId}`;

  /** @internal */
  protected readonly panelId = `llm-combobox-panel-${nextId}`;

  /** @internal */
  protected readonly errorId = `llm-combobox-errors-${nextId++}`;

  /** @internal */
  protected readonly filteredOptions = computed(() => {
    const q = this.query().toLowerCase();
    if (!q) return this.options();
    return this.options().filter((o) => o.label.toLowerCase().includes(q));
  });

  /** @internal */
  protected readonly activeOptionId = computed(() => {
    const idx = this.activeIndex();
    return idx >= 0 ? this.optionId(idx) : null;
  });

  /** @internal */
  protected readonly showErrors = computed(
    () => this.touched() && this.invalid() && this.errors().length > 0,
  );

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.isOpen()) classes.push('is-open');
    if (this.disabled()) classes.push('is-disabled');
    if (this.invalid()) classes.push('is-invalid');
    if (this.touched()) classes.push('is-touched');
    return classes.join(' ');
  });

  private outsideClickHandler: ((e: MouseEvent) => void) | null = null;
  private readonly elementRef = inject<ElementRef<HTMLElement>>(ElementRef);

  /** @internal */
  protected optionId(index: number): string {
    return `${this.panelId}-option-${index}`;
  }

  /** @internal */
  protected onInput(event: Event): void {
    const q = (event.target as HTMLInputElement).value;
    this.query.set(q);
    this.activeIndex.set(-1);
    if (q === '') {
      this.value.set('');
    }
    if (!this.isOpen()) this.open();
  }

  /** @internal */
  protected onFocus(): void {
    if (!this.disabled()) this.open();
  }

  /** @internal */
  protected onBlur(): void {
    const selectedOption = this.options().find((o) => o.value === this.value());
    this.query.set(selectedOption?.label ?? '');
    this.touched.set(true);
  }

  /** @internal */
  protected onOptionSelect(option: LlmComboboxOption): void {
    if (option.disabled || this.disabled()) return;
    this.value.set(option.value);
    this.query.set(option.label);
    this.touched.set(true);
    this.close();
    this.inputEl()?.nativeElement.focus();
  }

  /** @internal */
  protected onKeydown(event: KeyboardEvent): void {
    if (this.disabled()) return;

    switch (event.key) {
      case 'Enter': {
        const activeIdx = this.activeIndex();
        if (this.isOpen() && activeIdx >= 0) {
          event.preventDefault();
          const option = this.filteredOptions()[activeIdx];
          this.onOptionSelect(option);
        }
        break;
      }
      case 'Escape': {
        event.preventDefault();
        const selectedOption = this.options().find((o) => o.value === this.value());
        this.query.set(selectedOption?.label ?? '');
        this.close();
        break;
      }
      case 'Tab': {
        this.close();
        break;
      }
      case 'ArrowDown':
      case 'ArrowUp': {
        if (!this.isOpen()) {
          this.open();
          break;
        }
        event.preventDefault();
        const opts = this.filteredOptions();
        const enabledIndices = opts.map((_, i) => i).filter((i) => !opts[i].disabled);
        if (enabledIndices.length === 0) break;
        const currentPos = enabledIndices.indexOf(this.activeIndex());
        const len = enabledIndices.length;
        const nextPos =
          event.key === 'ArrowDown'
            ? (currentPos + 1) % len
            : (currentPos - 1 + len) % len;
        this.activeIndex.set(enabledIndices[nextPos]);
        break;
      }
    }
  }

  private open(): void {
    const panel = this.panelRef();
    if (!panel || this.isOpen()) return;
    (panel.nativeElement as HTMLElement & { showPopover(): void }).showPopover();
    this.isOpen.set(true);
    this.activeIndex.set(-1);

    this.outsideClickHandler = (e: MouseEvent) => {
      if (!this.elementRef.nativeElement.contains(e.target as Node)) {
        this.close();
      }
    };
    document.addEventListener('click', this.outsideClickHandler);
  }

  private close(): void {
    const panel = this.panelRef();
    if (!panel || !this.isOpen()) return;
    try {
      (panel.nativeElement as HTMLElement & { hidePopover(): void }).hidePopover();
    } catch {
      // Panel may already be hidden
    }
    this.isOpen.set(false);
    this.activeIndex.set(-1);

    if (this.outsideClickHandler) {
      document.removeEventListener('click', this.outsideClickHandler);
      this.outsideClickHandler = null;
    }
  }
}
