// libs/vue/src/lib/badge/llm-badge.vue
<script setup lang="ts">
import { computed } from 'vue';
import './llm-badge.css';

defineOptions({ name: 'LlmBadge' });

type LlmBadgeVariant = 'default' | 'success' | 'warning' | 'danger' | 'info';

interface LlmBadgeProps {
  variant?: LlmBadgeVariant;
  size?: 'sm' | 'md';
}

const VARIANT_ICONS: Record<LlmBadgeVariant, string | null> = {
  default: null,
  success: '✓',
  warning: '⚠',
  danger: '✕',
  info: 'ℹ',
};

const props = withDefaults(defineProps<LlmBadgeProps>(), {
  variant: 'default',
  size: 'md',
});

const classes = computed(() => [
  'llm-badge',
  `variant-${props.variant}`,
  `size-${props.size}`,
]);

const variantIcon = computed(() => VARIANT_ICONS[props.variant]);
</script>

<template>
  <span :class="classes" role="status">
    <span v-if="variantIcon" class="variant-icon" aria-hidden="true">{{ variantIcon }}</span>
    <slot />
  </span>
</template>

// libs/angular/src/lib/badge/llm-badge.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

/**
 * Inline status badge for labeling items with semantic color variants.
 *
 * Usage:
 * ```html
 * <llm-badge variant="success">Active</llm-badge>
 * <llm-badge variant="danger" size="sm">Error</llm-badge>
 * <llm-badge variant="warning">Pending</llm-badge>
 * ```
 */
const VARIANT_ICONS: Record<'default' | 'success' | 'warning' | 'danger' | 'info', string | null> = {
  default: null,
  success: '✓',
  warning: '⚠',
  danger: '✕',
  info: 'ℹ',
};

@Component({
  selector: 'llm-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (variantIcon(); as icon) {
      <span class="variant-icon" aria-hidden="true">{{ icon }}</span>
    }
    <ng-content />
  `,
  styleUrl: './llm-badge.css',
  host: {
    '[class]': 'hostClasses()',
    role: 'status',
  },
})
export class LlmBadge {
  /** Semantic color variant of the badge. */
  readonly variant = input<'default' | 'success' | 'warning' | 'danger' | 'info'>('default');

  /** Size of the badge. */
  readonly size = input<'sm' | 'md'>('md');

  protected readonly hostClasses = computed(
    () => `variant-${this.variant()} size-${this.size()}`
  );

  protected readonly variantIcon = computed(() => VARIANT_ICONS[this.variant()]);
}
