// libs/vue/src/lib/stepper/atl-stepper.vue
<script lang="ts">
import type { InjectionKey, Ref } from 'vue';
import AtlIcon from '../icon/atl-icon.vue';

export interface StepInfo {
  id: string;
  label: string;
  description?: string;
  completed: boolean;
  error: boolean;
  optional: boolean;
  disabled: boolean;
}

export interface AtlStepperContext {
  activeStep: Ref<number>;
  steps: Ref<StepInfo[]>;
  linear: Ref<boolean>;
  registerStep(step: StepInfo): void;
  unregisterStep(id: string): void;
  updateStep(id: string, info: Partial<StepInfo>): void;
  goTo(index: number): void;
  next(): void;
  prev(): void;
}

export const AtlStepperKey: InjectionKey<AtlStepperContext> =
  Symbol('AtlStepper');
</script>

<script setup lang="ts">
import { computed, provide, ref, watch } from 'vue';
import './atl-stepper.css';

defineOptions({ name: 'AtlStepper' });

const props = withDefaults(
  defineProps<{
    activeStep?: number;
    orientation?: 'horizontal' | 'vertical';
    linear?: boolean;
  }>(),
  {
    activeStep: 0,
    orientation: 'horizontal',
    linear: false,
  },
);

const emit = defineEmits<{
  'update:activeStep': [index: number];
}>();

const internalStep = ref(props.activeStep);
const steps = ref<StepInfo[]>([]);
const linearRef = computed(() => props.linear);

watch(
  () => props.activeStep,
  (val) => {
    internalStep.value = val;
  },
);

function registerStep(step: StepInfo) {
  steps.value.push(step);
}

function unregisterStep(id: string) {
  steps.value = steps.value.filter((s) => s.id !== id);
}

function updateStep(id: string, info: Partial<StepInfo>) {
  const idx = steps.value.findIndex((s) => s.id === id);
  if (idx !== -1) {
    steps.value[idx] = { ...steps.value[idx], ...info };
  }
}

// Whether step `index` can be activated right now: not itself disabled, and —
// in linear mode — either at/behind the active step, or ahead of it with every
// step before it completed or optional. Drives both goTo()'s guard and the
// header button's native `disabled` state, so an unreachable step is also not
// focusable — no roving-tabindex bookkeeping needed, since the header is a
// list, not a tab widget.
function isReachable(index: number): boolean {
  const step = steps.value[index];
  if (!step || step.disabled) return false;
  if (!props.linear) return true;
  if (index <= internalStep.value) return true;
  return steps.value.slice(0, index).every((s) => s.completed || s.optional);
}

function goTo(index: number) {
  if (index < 0 || index >= steps.value.length) return;
  if (!isReachable(index)) return;
  internalStep.value = index;
  emit('update:activeStep', index);
}

function next() {
  goTo(internalStep.value + 1);
}

function prev() {
  const p = internalStep.value - 1;
  if (p >= 0 && !steps.value[p]?.disabled) {
    internalStep.value = p;
    emit('update:activeStep', p);
  }
}

provide(AtlStepperKey, {
  activeStep: internalStep,
  steps,
  linear: linearRef,
  registerStep,
  unregisterStep,
  updateStep,
  goTo,
  next,
  prev,
});

const classes = computed(() => [
  'atl-stepper',
  `orientation-${props.orientation}`,
]);

function isConnectorActive(i: number) {
  return internalStep.value > i || steps.value[i]?.completed;
}
</script>

<template>
  <div :class="classes">
    <ol class="stepper-header" role="list" aria-label="Progress">
      <template v-for="(step, i) in steps" :key="step.id">
        <li
          class="step-item"
          :class="{
            'is-active': internalStep === i,
            'is-completed': step.completed && internalStep !== i,
            'is-error': step.error,
            'is-disabled': step.disabled,
          }"
        >
          <button
            :id="`atl-step-${i}`"
            type="button"
            class="step-circle"
            :aria-label="step.label"
            :aria-current="internalStep === i ? 'step' : undefined"
            :disabled="!isReachable(i)"
            @click="goTo(i)"
          >
            <template v-if="step.completed && !step.error">
              <AtlIcon name="check" size="sm" />
            </template>
            <template v-else-if="step.error">
              <AtlIcon name="close" size="sm" />
            </template>
            <template v-else>{{ i + 1 }}</template>
          </button>
          <div class="step-text">
            <span class="step-label">{{ step.label }}</span>
            <span v-if="step.description" class="step-description">{{
              step.description
            }}</span>
            <span v-if="step.optional && !step.completed" class="step-optional"
              >Optional</span
            >
          </div>
        </li>
        <li
          v-if="i < steps.length - 1"
          class="step-connector"
          aria-hidden="true"
          :class="{ 'is-active': isConnectorActive(i) }"
        />
      </template>
    </ol>
    <div class="stepper-content">
      <slot />
    </div>
  </div>
</template>

// libs/angular/src/lib/stepper/atl-stepper.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  model,
  OnDestroy,
  OnInit,
  signal,
} from '@angular/core';
import {
  ATL_STEPPER,
  type AtlStepperContext,
  type StepInfo,
} from './atl-stepper.token';
import { AtlIcon } from '../icon/atl-icon';

let nextId = 0;

/**
 * Multi-step wizard container.
 *
 * Usage:
 * ```html
 * <atl-stepper [(activeStep)]="step">
 *   <atl-step label="Account">Account form here.</atl-step>
 *   <atl-step label="Profile">Profile form here.</atl-step>
 *   <atl-step label="Review">Review and submit.</atl-step>
 * </atl-stepper>
 * ```
 */
@Component({
  selector: 'atl-stepper',
  standalone: true,
  imports: [AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ol class="stepper-header" role="list" aria-label="Progress">
      @for (step of steps(); track step.id; let i = $index; let last = $last) {
        <li
          class="step-item"
          [class.is-active]="activeStep() === i"
          [class.is-completed]="step.completed && activeStep() !== i"
          [class.is-error]="step.error"
          [class.is-disabled]="step.disabled"
        >
          <button
            type="button"
            class="step-circle"
            [id]="'atl-step-' + i"
            [attr.aria-label]="step.label"
            [attr.aria-current]="activeStep() === i ? 'step' : null"
            [disabled]="!isReachable(i)"
            (click)="goTo(i)"
          >
            @if (step.completed && !step.error) {
              <atl-icon name="check" size="sm" />
            } @else if (step.error) {
              <atl-icon name="close" size="sm" />
            } @else {
              {{ i + 1 }}
            }
          </button>
          <div class="step-text">
            <span class="step-label">{{ step.label }}</span>
            @if (step.description) {
              <span class="step-description">{{ step.description }}</span>
            }
            @if (step.optional && !step.completed) {
              <span class="step-optional">Optional</span>
            }
          </div>
        </li>
        @if (!last) {
          <li
            class="step-connector"
            aria-hidden="true"
            [class.is-active]="activeStep() > i || step.completed"
          ></li>
        }
      }
    </ol>
    <div class="stepper-content">
      <ng-content />
    </div>
  `,
  styleUrl: './atl-stepper.css',
  host: {
    '[class]': 'hostClasses()',
  },
  providers: [{ provide: ATL_STEPPER, useExisting: AtlStepper }],
})
export class AtlStepper implements AtlStepperContext {
  /** Index of the currently active step. Supports two-way binding. */
  readonly activeStep = model(0);

  /** Layout orientation. */
  readonly orientation = input<'horizontal' | 'vertical'>('horizontal');

  /**
   * When true, users can only navigate to completed steps or the next pending step.
   * Use `goTo()` / `next()` in your step content to advance programmatically.
   */
  readonly linear = input(false);

  /** @internal */
  readonly steps = signal<StepInfo[]>([]);

  /** @internal */
  protected readonly hostClasses = computed(
    () => `orientation-${this.orientation()}`,
  );

  /** @internal — called by AtlStep on init */
  registerStep(info: StepInfo): void {
    this.steps.update((list) => [...list, info]);
  }

  /** @internal — called by AtlStep on destroy */
  unregisterStep(id: string): void {
    this.steps.update((list) => list.filter((s) => s.id !== id));
  }

  /** @internal — called by AtlStep effect when inputs change */
  updateStep(id: string, info: Partial<StepInfo>): void {
    this.steps.update((list) =>
      list.map((s) => (s.id === id ? { ...s, ...info } : s)),
    );
  }

  /**
   * Whether step `index` can be activated right now: not itself disabled, and —
   * in linear mode — either at or behind the active step, or ahead of it with
   * every step before it completed or optional. Drives both `goTo()`'s guard
   * and the header button's native `disabled` state, so a step that cannot be
   * activated is also not focusable (no roving-tabindex bookkeeping needed —
   * the header is a list, not a tab widget).
   */
  protected isReachable(index: number): boolean {
    const steps = this.steps();
    const step = steps[index];
    if (step.disabled) return false;
    if (!this.linear()) return true;
    if (index <= this.activeStep()) return true;
    return steps.slice(0, index).every((s) => s.completed || s.optional);
  }

  /** Navigate to a specific step index. Respects linear mode. */
  goTo(index: number): void {
    const steps = this.steps();
    if (index < 0 || index >= steps.length) return;
    if (!this.isReachable(index)) return;
    this.activeStep.set(index);
  }

  /** Advance to the next step. */
  next(): void {
    this.goTo(this.activeStep() + 1);
  }

  /** Go back to the previous step. */
  prev(): void {
    const prev = this.activeStep() - 1;
    if (prev < 0) return;
    const steps = this.steps();
    if (steps[prev]?.disabled) return;
    this.activeStep.set(prev);
  }
}

/**
 * Individual step. Place inside `<atl-stepper>`.
 *
 * Usage:
 * ```html
 * <atl-step label="Account">Account form here.</atl-step>
 * ```
 */
@Component({
  selector: 'atl-step',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (isActive()) {
      <div
        role="region"
        class="step-panel"
        [attr.aria-labelledby]="'atl-step-' + myIndex()"
      >
        <ng-content />
      </div>
    }
  `,
  styles: `
    :host {
      display: contents;
    }
  `,
})
export class AtlStep implements OnInit, OnDestroy {
  /** Text displayed on the step indicator. Required. */
  readonly label = input.required<string>();

  /** Optional subtitle shown below the label. */
  readonly description = input<string | undefined>(undefined);

  /** Mark this step as completed (shows a checkmark). */
  readonly completed = input(false);

  /** Mark this step as having an error (shows an X). */
  readonly error = input(false);

  /** Mark this step as optional. */
  readonly optional = input(false);

  /** Whether this step is disabled. */
  readonly disabled = input(false);

  /** @internal */
  private readonly id = `atl-step-instance-${nextId++}`;

  /** @internal */
  private readonly context = inject(ATL_STEPPER);

  /** @internal */
  protected readonly myIndex = computed(() =>
    this.context.steps().findIndex((s) => s.id === this.id),
  );

  /** @internal */
  protected readonly isActive = computed(
    () => this.context.activeStep() === this.myIndex(),
  );

  constructor() {
    // Keep step info in sync when inputs change
    effect(() => {
      if (this.myIndex() === -1) return;
      this.context.updateStep(this.id, {
        label: this.label(),
        description: this.description(),
        completed: this.completed(),
        error: this.error(),
        optional: this.optional(),
        disabled: this.disabled(),
      });
    });
  }

  ngOnInit(): void {
    this.context.registerStep({
      id: this.id,
      label: this.label(),
      description: this.description(),
      completed: this.completed(),
      error: this.error(),
      optional: this.optional(),
      disabled: this.disabled(),
    });
  }

  ngOnDestroy(): void {
    this.context.unregisterStep(this.id);
  }
}
