// libs/react/src/lib/combobox/atl-combobox.tsx
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import type { AtlComboboxOption, AtlComboboxSpec } from '../spec';
import './atl-combobox.css';
import { AtlIcon } from '../icon/atl-icon';

export type { AtlComboboxOption };

export interface AtlComboboxProps extends AtlComboboxSpec {
  value?: string;
  onValueChange?: (value: string) => void;
  errors?: string[];
}

/**
 * Filterable autocomplete combobox. Accepts an `options` array and emits the
 * selected option's `value`. The user types to narrow the list; selecting an
 * option commits the value and displays its label.
 *
 * Usage:
 * ```tsx
 * <AtlCombobox
 *   value={country}
 *   onValueChange={setCountry}
 *   options={countryOptions}
 *   placeholder="Search country…"
 * />
 * ```
 */
export function AtlCombobox({
  value = '',
  onValueChange,
  options = [],
  placeholder = '',
  disabled = false,
  readonly = false,
  invalid = false,
  required = false,
  name,
  errors = [],
}: AtlComboboxProps) {
  const [query, setQuery] = useState('');
  const [isOpen, setIsOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);

  const inputRef = useRef<HTMLInputElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const inputId = useId();
  const panelId = useId();
  const errorsId = `${useId()}-errors`;

  const selectedLabel = useMemo(
    () => options.find((o) => o.value === value)?.label ?? '',
    [options, value],
  );

  const filteredOptions = useMemo(() => {
    if (!query) return options;
    const q = query.toLowerCase();
    return options.filter((o) => o.label.toLowerCase().includes(q));
  }, [options, query]);

  const displayValue = isOpen ? query : selectedLabel;

  // Outside-click closes panel
  useEffect(() => {
    if (!isOpen) return;
    function handleClick(e: MouseEvent) {
      if (!containerRef.current?.contains(e.target as Node)) {
        setIsOpen(false);
        setQuery(selectedLabel);
      }
    }
    document.addEventListener('click', handleClick);
    return () => document.removeEventListener('click', handleClick);
  }, [isOpen, selectedLabel]);

  function open() {
    if (disabled || readonly) return;
    setQuery(selectedLabel);
    setIsOpen(true);
    setActiveIndex(-1);
  }

  function close() {
    setIsOpen(false);
    setActiveIndex(-1);
  }

  function selectOption(option: AtlComboboxOption) {
    if (option.disabled || disabled || readonly) return;
    onValueChange?.(option.value);
    setQuery(option.label);
    close();
    inputRef.current?.focus();
  }

  function handleInput(e: React.ChangeEvent<HTMLInputElement>) {
    const q = e.target.value;
    setQuery(q);
    setActiveIndex(-1);
    if (q === '') onValueChange?.('');
    if (!isOpen) open();
  }

  function handleFocus() {
    open();
  }

  function handleBlur() {
    setQuery(selectedLabel);
  }

  function handleKeydown(e: React.KeyboardEvent) {
    switch (e.key) {
      case 'ArrowDown': {
        e.preventDefault();
        if (!isOpen) {
          open();
          return;
        }
        setActiveIndex((i) => (i + 1 >= filteredOptions.length ? 0 : i + 1));
        break;
      }
      case 'ArrowUp': {
        e.preventDefault();
        if (!isOpen) {
          open();
          return;
        }
        setActiveIndex((i) => (i - 1 < 0 ? filteredOptions.length - 1 : i - 1));
        break;
      }
      case 'Enter': {
        e.preventDefault();
        if (
          isOpen &&
          activeIndex >= 0 &&
          activeIndex < filteredOptions.length
        ) {
          selectOption(filteredOptions[activeIndex]);
        }
        break;
      }
      case 'Escape': {
        e.preventDefault();
        setQuery(selectedLabel);
        close();
        break;
      }
      case 'Tab': {
        close();
        break;
      }
    }
  }

  const classes = [
    'atl-combobox',
    isOpen && 'is-open',
    disabled && 'is-disabled',
    readonly && 'is-readonly',
    invalid && 'is-invalid',
  ]
    .filter(Boolean)
    .join(' ');

  const activeOptionId =
    activeIndex >= 0 ? `${panelId}-option-${activeIndex}` : undefined;

  return (
    <div className={classes} ref={containerRef}>
      <div className="atl-combobox-wrapper">
        <input
          ref={inputRef}
          className="atl-combobox-input"
          type="text"
          autoComplete="off"
          role="combobox"
          id={inputId}
          aria-expanded={isOpen}
          aria-controls={panelId}
          aria-autocomplete="list"
          aria-activedescendant={activeOptionId}
          aria-invalid={invalid || undefined}
          aria-describedby={errors.length > 0 ? errorsId : undefined}
          disabled={disabled}
          readOnly={readonly}
          required={required}
          name={name}
          placeholder={placeholder}
          value={displayValue}
          onChange={handleInput}
          onFocus={handleFocus}
          onBlur={handleBlur}
          onKeyDown={handleKeydown}
        />
        {invalid && (
          <AtlIcon name="danger" size="sm" className="invalid-icon" />
        )}
        <span className="atl-combobox-icon" aria-hidden="true">
          <AtlIcon name="chevron-down" size="sm" />
        </span>
      </div>

      {isOpen && (
        <ul
          id={panelId}
          className="atl-combobox-panel"
          role="listbox"
          aria-labelledby={inputId}
        >
          {filteredOptions.length > 0 ? (
            filteredOptions.map((option, i) => (
              <li
                key={option.value}
                id={`${panelId}-option-${i}`}
                role="option"
                className={[
                  'atl-combobox-option',
                  activeIndex === i && 'is-active',
                  option.value === value && 'is-selected',
                  option.disabled && 'is-disabled',
                ]
                  .filter(Boolean)
                  .join(' ')}
                aria-selected={option.value === value}
                aria-disabled={option.disabled || undefined}
                onMouseDown={() => selectOption(option)}
                onMouseEnter={() => setActiveIndex(i)}
              >
                <span>{option.label}</span>
                {option.value === value && (
                  <AtlIcon
                    name="check"
                    size="sm"
                    className="atl-combobox-check"
                  />
                )}
              </li>
            ))
          ) : (
            <li
              className="atl-combobox-no-results"
              role="option"
              aria-selected={false}
              aria-disabled="true"
            >
              No results found.
            </li>
          )}
        </ul>
      )}

      {errors.length > 0 && (
        <div className="atl-combobox-errors" id={errorsId} aria-live="polite">
          {errors.map((e, i) => (
            <p key={i} className="atl-combobox-error-message">
              {e}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

// libs/vue/src/lib/combobox/atl-combobox.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue';
import type { AtlComboboxOption } from '../spec';
import './atl-combobox.css';
import AtlIcon from '../icon/atl-icon.vue';

defineOptions({ name: 'AtlCombobox' });

interface Props {
  value?: string;
  options?: AtlComboboxOption[];
  placeholder?: string;
  disabled?: boolean;
  readonly?: boolean;
  invalid?: boolean;
  required?: boolean;
  name?: string;
  errors?: string[];
}

const props = withDefaults(defineProps<Props>(), {
  value: '',
  options: () => [],
  placeholder: '',
  disabled: false,
  readonly: false,
  invalid: false,
  required: false,
  name: '',
  errors: () => [],
});

const emit = defineEmits<{
  'update:value': [value: string];
}>();

const inputRef = ref<HTMLInputElement | null>(null);
const containerRef = ref<HTMLDivElement | null>(null);

const query = ref('');
const isOpen = ref(false);
const activeIndex = ref(-1);

let idBase = Math.random().toString(36).slice(2);
const inputId = `atl-combobox-input-${idBase}`;
const panelId = `atl-combobox-panel-${idBase}`;
const errorsId = `atl-combobox-errors-${idBase}`;

const selectedLabel = computed(
  () => props.options.find((o) => o.value === props.value)?.label ?? '',
);

const filteredOptions = computed(() => {
  const q = query.value.toLowerCase();
  if (!q) return props.options;
  return props.options.filter((o) => o.label.toLowerCase().includes(q));
});

const activeOptionId = computed(() =>
  activeIndex.value >= 0 ? `${panelId}-option-${activeIndex.value}` : undefined,
);

const wrapperClasses = computed(() => [
  'atl-combobox',
  isOpen.value && 'is-open',
  props.disabled && 'is-disabled',
  props.readonly && 'is-readonly',
  props.invalid && 'is-invalid',
]);

// Sync query to selected label when value changes externally
watch(
  () => props.value,
  () => {
    if (!isOpen.value) query.value = selectedLabel.value;
  },
  { immediate: true },
);

function open() {
  if (props.disabled || props.readonly || isOpen.value) return;
  isOpen.value = true;
  activeIndex.value = -1;
  document.addEventListener('click', onOutsideClick);
}

function close() {
  if (!isOpen.value) return;
  isOpen.value = false;
  activeIndex.value = -1;
  document.removeEventListener('click', onOutsideClick);
}

function onOutsideClick(e: MouseEvent) {
  if (!containerRef.value?.contains(e.target as Node)) {
    query.value = selectedLabel.value;
    close();
  }
}

onUnmounted(() => {
  document.removeEventListener('click', onOutsideClick);
});

function selectOption(option: AtlComboboxOption) {
  if (option.disabled || props.disabled || props.readonly) return;
  emit('update:value', option.value);
  query.value = option.label;
  close();
  inputRef.value?.focus();
}

function onInput(event: Event) {
  const q = (event.target as HTMLInputElement).value;
  query.value = q;
  activeIndex.value = -1;
  if (q === '') emit('update:value', '');
  if (!isOpen.value) open();
}

function onFocus() {
  open();
}

function onBlur() {
  query.value = selectedLabel.value;
}

function onKeydown(event: KeyboardEvent) {
  const filtered = filteredOptions.value;
  switch (event.key) {
    case 'ArrowDown': {
      event.preventDefault();
      if (!isOpen.value) { open(); return; }
      const next = activeIndex.value + 1;
      activeIndex.value = next >= filtered.length ? 0 : next;
      break;
    }
    case 'ArrowUp': {
      event.preventDefault();
      if (!isOpen.value) { open(); return; }
      const prev = activeIndex.value - 1;
      activeIndex.value = prev < 0 ? filtered.length - 1 : prev;
      break;
    }
    case 'Enter': {
      event.preventDefault();
      const idx = activeIndex.value;
      if (isOpen.value && idx >= 0 && idx < filtered.length) {
        selectOption(filtered[idx]);
      }
      break;
    }
    case 'Escape': {
      event.preventDefault();
      query.value = selectedLabel.value;
      close();
      break;
    }
    case 'Tab': {
      close();
      break;
    }
  }
}
</script>

<template>
  <div ref="containerRef" :class="wrapperClasses">
    <div class="atl-combobox-wrapper">
      <input
        ref="inputRef"
        class="atl-combobox-input"
        type="text"
        autocomplete="off"
        role="combobox"
        :id="inputId"
        :aria-expanded="isOpen"
        :aria-controls="panelId"
        aria-autocomplete="list"
        :aria-activedescendant="activeOptionId"
        :aria-invalid="invalid || undefined"
        :aria-describedby="errors.length > 0 ? errorsId : undefined"
        :disabled="disabled"
        :readonly="readonly"
        :required="required"
        :name="name || undefined"
        :placeholder="placeholder"
        :value="query"
        @input="onInput"
        @focus="onFocus"
        @blur="onBlur"
        @keydown="onKeydown"
      />
      <AtlIcon v-if="invalid" name="danger" size="sm" class="invalid-icon" />
      <span class="atl-combobox-icon" aria-hidden="true">
        <AtlIcon name="chevron-down" size="sm" />
      </span>
    </div>

    <ul
      v-if="isOpen"
      :id="panelId"
      class="atl-combobox-panel"
      role="listbox"
      :aria-labelledby="inputId"
    >
      <template v-if="filteredOptions.length > 0">
        <li
          v-for="(option, i) in filteredOptions"
          :key="option.value"
          :id="`${panelId}-option-${i}`"
          role="option"
          :class="[
            'atl-combobox-option',
            activeIndex === i && 'is-active',
            option.value === value && 'is-selected',
            option.disabled && 'is-disabled',
          ]"
          :aria-selected="option.value === value"
          :aria-disabled="option.disabled || undefined"
          @mousedown="selectOption(option)"
          @mouseenter="activeIndex = i"
        >
          <span>{{ option.label }}</span>
          <AtlIcon name="check" size="sm" class="atl-combobox-check" />
        </li>
      </template>
      <li v-else class="atl-combobox-no-results" role="option" aria-disabled="true">
        No results found.
      </li>
    </ul>

    <div
      v-if="errors.length > 0"
      :id="errorsId"
      class="atl-combobox-errors"
      aria-live="polite"
    >
      <p v-for="(error, i) in errors" :key="i" class="atl-combobox-error-message">{{ error }}</p>
    </div>
  </div>
</template>
