// libs/llm-components-react/src/lib/accordion/llm-accordion.tsx
import {
  createContext,
  useContext,
  useState,
  useRef,
  useId,
  useLayoutEffect,
  useCallback,
  ReactNode,
  HTMLAttributes,
  KeyboardEvent,
} from 'react';
import type {
  LlmAccordionGroupSpec,
  LlmAccordionItemSpec,
} from '@atelier-ui/spec';
import './llm-accordion.css';

interface AccordionGroupContextValue {
  multi: boolean;
  openItems: Set<string>;
  toggleItem: (id: string) => void;
  registerItem: (id: string, ref: React.RefObject<HTMLButtonElement | null>, disabled: boolean) => void;
  unregisterItem: (id: string) => void;
  handleKeydown: (e: KeyboardEvent, id: string) => void;
}

const AccordionGroupContext = createContext<AccordionGroupContextValue>({
  multi: false,
  openItems: new Set(),
  toggleItem: () => { /* noop */ },
  registerItem: () => { /* noop */ },
  unregisterItem: () => { /* noop */ },
  handleKeydown: () => { /* noop */ },
});

/**
 * Properties for the LlmAccordionGroup component.
 */
export interface LlmAccordionGroupProps
  extends HTMLAttributes<HTMLDivElement>,
    LlmAccordionGroupSpec {
  /**
   * Whether multiple items can be expanded simultaneously.
   */
  multi?: boolean;
  /**
   * The visual style variant of the accordion.
   */
  variant?: 'default' | 'bordered' | 'separated';
  /**
   * The accordion items to be rendered.
   */
  children?: ReactNode;
}

/**
 * A container component that manages a group of accordion items.
 */
export function LlmAccordionGroup({
  multi = false,
  variant = 'default',
  children,
  className,
  ...rest
}: LlmAccordionGroupProps) {
  const [openItems, setOpenItems] = useState<Set<string>>(new Set());
  const itemsRef = useRef<{ id: string; triggerRef: React.RefObject<HTMLButtonElement | null>; disabled: boolean }[]>([]);

  const classes = ['llm-accordion-group', `variant-${variant}`, className]
    .filter(Boolean)
    .join(' ');

  const toggleItem = useCallback((id: string) => {
    setOpenItems((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        if (!multi) next.clear();
        next.add(id);
      }
      return next;
    });
  }, [multi]);

  const registerItem = useCallback((id: string, ref: React.RefObject<HTMLButtonElement | null>, disabled: boolean) => {
    itemsRef.current = [...itemsRef.current.filter((i) => i.id !== id), { id, triggerRef: ref, disabled }];
  }, []);

  const unregisterItem = useCallback((id: string) => {
    itemsRef.current = itemsRef.current.filter((i) => i.id !== id);
  }, []);

  const handleKeydown = useCallback((e: KeyboardEvent, currentId: string) => {
    const enabled = itemsRef.current.filter((i) => !i.disabled);
    if (enabled.length === 0) return;

    const pos = enabled.findIndex((i) => i.id === currentId);
    const n = enabled.length;
    let target: (typeof enabled)[0] | null = null;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      target = enabled[(pos + 1) % n];
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      target = enabled[(pos - 1 + n) % n];
    } else if (e.key === 'Home') {
      e.preventDefault();
      target = enabled[0];
    } else if (e.key === 'End') {
      e.preventDefault();
      target = enabled[n - 1];
    }

    target?.triggerRef.current?.focus();
  }, []);

  return (
    <AccordionGroupContext.Provider
      value={{ multi, openItems, toggleItem, registerItem, unregisterItem, handleKeydown }}
    >
      <div className={classes} role="presentation" {...rest}>
        {children}
      </div>
    </AccordionGroupContext.Provider>
  );
}

/**
 * Properties for the LlmAccordionItem component.
 */
export interface LlmAccordionItemProps
  extends HTMLAttributes<HTMLDivElement>,
    LlmAccordionItemSpec {
  /**
   * Whether the item is currently expanded.
   */
  expanded?: boolean;
  /**
   * Callback triggered when the expanded state changes.
   */
  onExpandedChange?: (expanded: boolean) => void;
  /**
   * Whether the accordion item is disabled.
   */
  disabled?: boolean;
  /**
   * The content of the accordion item, typically including an LlmAccordionHeader.
   */
  children?: ReactNode;
}

/**
 * An individual item within an accordion group.
 */
export function LlmAccordionItem({
  expanded: externalExpanded,
  onExpandedChange,
  disabled = false,
  children,
  className,
  ...rest
}: LlmAccordionItemProps) {
  const ctx = useContext(AccordionGroupContext);
  const id = useId();
  const triggerId = `${id}-trigger`;
  const panelId = `${id}-panel`;
  const triggerRef = useRef<HTMLButtonElement>(null);

  const { registerItem, unregisterItem } = ctx;

  // Register/unregister with parent
  useLayoutEffect(() => {
    registerItem(id, triggerRef, disabled);
    return () => unregisterItem(id);
  }, [id, triggerRef, disabled, registerItem, unregisterItem]);

  const isControlled = externalExpanded !== undefined;
  const isExpanded = isControlled ? externalExpanded : ctx.openItems.has(id);

  const toggle = () => {
    if (disabled) return;
    const next = !isExpanded;
    if (!isControlled) ctx.toggleItem(id);
    onExpandedChange?.(next);
  };

  const classes = [
    'llm-accordion-item',
    isExpanded && 'is-expanded',
    disabled && 'is-disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  // Separate header child from body children
  const childArray = Array.isArray(children) ? children : [children];
  const headerNode = childArray.find(
    (c): c is React.ReactElement =>
      typeof c === 'object' &&
      c !== null &&
      'type' in (c as object) &&
      (c as React.ReactElement).type === LlmAccordionHeader
  );
  const bodyNodes = childArray.filter((c) => c !== headerNode);

  return (
    <div className={classes} {...rest}>
      <h3 className="accordion-heading">
        <button
          ref={triggerRef}
          type="button"
          id={triggerId}
          className={['accordion-trigger', disabled && 'is-disabled']
            .filter(Boolean)
            .join(' ')}
          aria-expanded={isExpanded}
          aria-controls={panelId}
          aria-disabled={disabled || undefined}
          disabled={disabled}
          onClick={toggle}
          onKeyDown={(e) => ctx.handleKeydown(e, id)}
        >
          {headerNode}
          <svg
            className={['chevron', isExpanded && 'is-expanded']
              .filter(Boolean)
              .join(' ')}
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            aria-hidden="true"
          >
            <path
              d="M4 6L8 10L12 6"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>
      </h3>
      <div
        className={['accordion-panel-wrapper', isExpanded && 'is-expanded']
          .filter(Boolean)
          .join(' ')}
      >
        <div
          id={panelId}
          role="region"
          aria-labelledby={triggerId}
          className="accordion-panel"
        >
          {bodyNodes}
        </div>
      </div>
    </div>
  );
}

/**
 * The header component for an LlmAccordionItem.
 */
export function LlmAccordionHeader({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLSpanElement> & {
  /**
   * The content to be rendered in the header.
   */
  children?: ReactNode;
}) {
  return (
    <span
      className={['accordion-header-content', className].filter(Boolean).join(' ')}
      {...rest}
    >
      {children}
    </span>
  );
}

// libs/llm-components-angular/src/lib/accordion/llm-accordion.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  Directive,
  ElementRef,
  inject,
  input,
  model,
  OnDestroy,
  OnInit,
  signal,
} from '@angular/core';
import { CdkAccordion, CdkAccordionItem } from '@angular/cdk/accordion';
import { LLM_ACCORDION_GROUP, type AccordionItem, type LlmAccordionGroupContext } from './llm-accordion.token';

let nextId = 0;

/**
 * Container that manages accordion items. Controls single vs multi expansion
 * and provides keyboard navigation across items.
 *
 * Usage:
 * ```html
 * <llm-accordion-group [multi]="true" variant="separated">
 *   <llm-accordion-item [(expanded)]="open">
 *     <span llmAccordionHeader>Title</span>
 *     Body content here.
 *   </llm-accordion-item>
 * </llm-accordion-group>
 * ```
 */
@Component({
  selector: 'llm-accordion-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  styleUrl: './llm-accordion.css',
  hostDirectives: [{ directive: CdkAccordion, inputs: ['multi'] }],
  host: {
    '[class]': 'hostClasses()',
    role: 'presentation',
  },
  providers: [{ provide: LLM_ACCORDION_GROUP, useExisting: LlmAccordionGroup }],
})
export class LlmAccordionGroup implements LlmAccordionGroupContext {
  /** Allow multiple items to be expanded simultaneously. */
  readonly multi = input(false);

  /** Visual variant. */
  readonly variant = input<'default' | 'bordered' | 'separated'>('default');

  /** @internal */
  protected readonly hostClasses = computed(() => `variant-${this.variant()}`);

  /** @internal */
  private readonly items = signal<AccordionItem[]>([]);

  register(item: AccordionItem): void {
    this.items.update((list) => [...list, item]);
  }

  unregister(item: AccordionItem): void {
    this.items.update((list) => list.filter((i) => i !== item));
  }

  handleKeydown(event: KeyboardEvent, item: AccordionItem): void {
    const allItems = this.items();
    const enabled = allItems.filter((i) => !i.isItemDisabled());
    if (enabled.length === 0) return;

    const pos = enabled.indexOf(item);
    const n = enabled.length;
    let target: AccordionItem | null = null;

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        target = enabled[(pos + 1) % n];
        break;
      case 'ArrowUp':
        event.preventDefault();
        target = enabled[(pos - 1 + n) % n];
        break;
      case 'Home':
        event.preventDefault();
        target = enabled[0];
        break;
      case 'End':
        event.preventDefault();
        target = enabled[n - 1];
        break;
    }

    target?.focusTrigger();
  }
}

/**
 * Directive to mark the accordion header content.
 */
@Directive({
  selector: '[llmAccordionHeader]',
  standalone: true,
})
export class LlmAccordionHeader {}

/**
 * Individual collapsible accordion item. Place inside `<llm-accordion-group>`.
 *
 * Usage:
 * ```html
 * <llm-accordion-item [(expanded)]="isOpen">
 *   <span llmAccordionHeader>Section Title</span>
 *   Section content goes here.
 * </llm-accordion-item>
 * ```
 */
@Component({
  selector: 'llm-accordion-item',
  standalone: true,
  imports: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [CdkAccordionItem],
  template: `
    <h3 class="accordion-heading">
      <button
        type="button"
        class="accordion-trigger"
        [id]="triggerId"
        [attr.aria-expanded]="isExpanded()"
        [attr.aria-controls]="panelId"
        [attr.aria-disabled]="disabled() || null"
        [class.is-disabled]="disabled()"
        (click)="onToggle()"
        (keydown)="onKeydown($event)"
      >
        <ng-content select="[llmAccordionHeader]" />
        <svg
          class="chevron"
          [class.is-expanded]="isExpanded()"
          width="16"
          height="16"
          viewBox="0 0 16 16"
          fill="none"
          aria-hidden="true"
        >
          <path
            d="M4 6L8 10L12 6"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </button>
    </h3>
    <div
      class="accordion-panel-wrapper"
      [class.is-expanded]="isExpanded()"
    >
      <div
        role="region"
        [id]="panelId"
        [attr.aria-labelledby]="triggerId"
        class="accordion-panel"
      >
        <ng-content />
      </div>
    </div>
  `,
  styleUrl: './llm-accordion.css',
  host: {
    '[attr.data-accordion-id]': 'id',
  },
})
export class LlmAccordionItem implements AccordionItem, OnInit, OnDestroy {
  /** Whether this item is expanded. Supports two-way binding. */
  readonly expanded = model(false);

  /** Whether this item is disabled. */
  readonly disabled = input(false);

  /** @internal */
  readonly id = `llm-accordion-item-${nextId++}`;

  /** @internal */
  readonly triggerId = `${this.id}-trigger`;

  /** @internal */
  readonly panelId = `${this.id}-panel`;

  /** @internal */
  private readonly group = inject(LlmAccordionGroup);

  /** @internal */
  private readonly cdkItem = inject(CdkAccordionItem);

  /** @internal */
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);

  /** @internal */
  protected readonly isExpanded = signal(false);

  constructor() {
    this.cdkItem.expandedChange.subscribe((expanded: boolean) => {
      this.isExpanded.set(expanded);
      this.expanded.set(expanded);
    });
  }

  ngOnInit(): void {
    this.group.register(this);
    // Sync initial expanded model
    if (this.expanded()) {
      this.cdkItem.open();
    }
  }

  ngOnDestroy(): void {
    this.group.unregister(this);
  }

  /** @internal — for FocusKeyManager */
  focusTrigger(): void {
    this.el.nativeElement.querySelector<HTMLButtonElement>('.accordion-trigger')?.focus();
  }

  /** @internal — for FocusKeyManager */
  isItemDisabled(): boolean {
    return this.disabled();
  }

  /** @internal */
  protected onToggle(): void {
    if (this.disabled()) return;
    this.cdkItem.toggle();
  }

  /** @internal */
  protected onKeydown(event: KeyboardEvent): void {
    this.group.handleKeydown(event, this);
  }
}
