// libs/vue/src/lib/dialog/llm-dialog.vue
<script lang="ts">
import type { InjectionKey } from 'vue';

export interface LlmDialogContext {
  headerId: string;
  close: () => void;
}

export const LlmDialogKey: InjectionKey<LlmDialogContext> = Symbol('LlmDialog');

export interface LlmDialogProps {
  open?: boolean;
  closeOnBackdrop?: boolean;
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  ariaLabel?: string;
}
</script>

<script setup lang="ts">
import { computed, onMounted, provide, ref, useId, watch } from 'vue';
import './llm-dialog.css';

defineOptions({ name: 'LlmDialog' });

const props = withDefaults(defineProps<LlmDialogProps>(), {
  open: false,
  closeOnBackdrop: true,
  size: 'md',
  ariaLabel: undefined,
});

const emit = defineEmits<{
  'update:open': [open: boolean];
}>();

const dialogRef = ref<HTMLDialogElement | null>(null);
const headerId = useId();

function close() {
  emit('update:open', false);
}

provide(LlmDialogKey, {
  headerId,
  close,
});

onMounted(() => {
  if (props.open && dialogRef.value) {
    dialogRef.value.showModal();
  }
});

watch(
  () => props.open,
  (isOpen) => {
    const dialog = dialogRef.value;
    if (!dialog) return;
    if (isOpen) {
      if (!dialog.open) dialog.showModal();
    } else {
      if (dialog.open) dialog.close();
    }
  },
  { flush: 'post' },
);

function onDialogClose() {
  emit('update:open', false);
}

function onDialogCancel(event: Event) {
  event.preventDefault();
  emit('update:open', false);
}

function onBackdropClick(event: MouseEvent) {
  if (props.closeOnBackdrop && event.target === dialogRef.value) {
    emit('update:open', false);
  }
}

const panelClasses = computed(() => ['panel', `size-${props.size}`]);
</script>

<template>
  <dialog
    ref="dialogRef"
    class="llm-dialog"
    :aria-label="ariaLabel || undefined"
    :aria-labelledby="!ariaLabel ? headerId : undefined"
    aria-modal="true"
    @close="onDialogClose"
    @cancel="onDialogCancel"
    @click="onBackdropClick"
  >
    <div :class="panelClasses" @click.stop>
      <slot />
    </div>
  </dialog>
</template>

// libs/llm-components-react/src/lib/dialog/llm-dialog.tsx
import {
  useEffect,
  useRef,
  useId,
  createContext,
  useContext,
  ReactNode,
  HTMLAttributes,
  MouseEvent,
} from 'react';
import './llm-dialog.css';

interface DialogContextValue {
  headerId: string;
  close: () => void;
}

const DialogContext = createContext<DialogContextValue>({
  headerId: '',
  close: () => {},
});

export interface LlmDialogProps {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  closeOnBackdrop?: boolean;
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  'aria-label'?: string;
  'aria-labelledby'?: string;
  children?: ReactNode;
}

export function LlmDialog({
  open = false,
  onOpenChange,
  closeOnBackdrop = true,
  size = 'md',
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledby,
  children,
}: LlmDialogProps) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const headerId = useId();
  const triggerElRef = useRef<Element | null>(null);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (open) {
      triggerElRef.current = document.activeElement;
      if (!dialog.open) dialog.showModal();
    } else {
      if (dialog.open) dialog.close();
      (triggerElRef.current as HTMLElement | null)?.focus();
      triggerElRef.current = null;
    }
  }, [open]);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    const onClose = () => onOpenChange?.(false);
    const onCancel = (e: Event) => {
      e.preventDefault();
      onOpenChange?.(false);
    };
    dialog.addEventListener('close', onClose);
    dialog.addEventListener('cancel', onCancel);
    return () => {
      dialog.removeEventListener('close', onClose);
      dialog.removeEventListener('cancel', onCancel);
    };
  }, [onOpenChange]);

  const handleBackdropClick = (e: MouseEvent<HTMLDialogElement>) => {
    if (!closeOnBackdrop) return;
    if (e.target === dialogRef.current) {
      onOpenChange?.(false);
    }
  };

  const effectiveAriaLabelledby = ariaLabel ? undefined : (ariaLabelledby ?? headerId);

  return (
    <DialogContext.Provider value={{ headerId, close: () => onOpenChange?.(false) }}>
      <dialog
        ref={dialogRef}
        className={`llm-dialog${open ? ' is-open' : ''}`}
        aria-label={ariaLabel || undefined}
        aria-labelledby={effectiveAriaLabelledby}
        aria-modal="true"
        onClick={handleBackdropClick}
      >
        <div className={`panel size-${size}`} onClick={(e) => e.stopPropagation()}>
          {children}
        </div>
      </dialog>
    </DialogContext.Provider>
  );
}

export function LlmDialogHeader({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & { children?: ReactNode }) {
  const ctx = useContext(DialogContext);
  return (
    <div
      id={ctx.headerId}
      className={['llm-dialog-header', className].filter(Boolean).join(' ')}
      {...rest}
    >
      {children}
      <button
        className="close-btn"
        type="button"
        aria-label="Close dialog"
        onClick={ctx.close}
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <line x1="18" y1="6" x2="6" y2="18" />
          <line x1="6" y1="6" x2="18" y2="18" />
        </svg>
      </button>
    </div>
  );
}

export function LlmDialogContent({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & { children?: ReactNode }) {
  return (
    <div
      className={['llm-dialog-content', className].filter(Boolean).join(' ')}
      {...rest}
    >
      {children}
    </div>
  );
}

export function LlmDialogFooter({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & { children?: ReactNode }) {
  return (
    <div
      className={['llm-dialog-footer', className].filter(Boolean).join(' ')}
      {...rest}
    >
      {children}
    </div>
  );
}
