// libs/vue/src/lib/button/llm-button.vue
<script setup lang="ts">
import { computed } from 'vue';
import './llm-button.css';

defineOptions({ name: 'LlmButton' });

interface LlmButtonProps {
  variant?: 'primary' | 'secondary' | 'outline';
  size?: 'sm' | 'md' | 'lg';
  disabled?: boolean;
  loading?: boolean;
  type?: 'button' | 'submit' | 'reset';
}

const props = withDefaults(defineProps<LlmButtonProps>(), {
  variant: 'primary',
  size: 'md',
  disabled: false,
  loading: false,
  type: 'button',
});

const isDisabled = computed(() => props.disabled || props.loading);

const classes = computed(() => [
  'llm-button',
  `variant-${props.variant}`,
  `size-${props.size}`,
  isDisabled.value && 'is-disabled',
  props.loading && 'is-loading',
].filter(Boolean));
</script>

<template>
  <button
    :class="classes"
    :type="type"
    :disabled="isDisabled"
    :aria-disabled="isDisabled || undefined"
  >
    <span v-if="loading" class="spinner" aria-hidden="true" />
    <slot />
  </button>
</template>

// libs/llm-components-react/src/lib/button/llm-button.tsx
import { ButtonHTMLAttributes, ReactNode } from 'react';
import './llm-button.css';

export interface LlmButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'outline';
  size?: 'sm' | 'md' | 'lg';
  loading?: boolean;
  children?: ReactNode;
}

export function LlmButton({
  variant = 'primary',
  size = 'md',
  disabled = false,
  loading = false,
  children,
  className,
  ...rest
}: LlmButtonProps) {
  const isDisabled = disabled || loading;
  const classes = ['llm-button', `variant-${variant}`, `size-${size}`, isDisabled && 'is-disabled', loading && 'is-loading', className]
    .filter(Boolean).join(' ');

  return (
    <button
      className={classes}
      disabled={isDisabled}
      aria-disabled={isDisabled || undefined}
      {...rest}
    >
      {loading && <span className="spinner" aria-hidden="true" />}
      {children}
    </button>
  );
}
