// libs/vue/src/lib/alert/atl-alert.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@atelier-ui/styles/alert/atl-alert.css';
import type { AtlIconName } from '../spec';
import AtlIcon from '../icon/atl-icon.vue';

defineOptions({ name: 'AtlAlert' });

type AtlAlertVariant = 'info' | 'success' | 'warning' | 'danger';

interface AtlAlertProps {
  variant?: AtlAlertVariant;
  dismissible?: boolean;
}

// Which AtlIcon each variant carries. Names, not glyphs: a glyph in a string map
// was the fifth way this library drew an icon, and the one check:icon-duplication
// missed (ADR-0050).
const VARIANT_ICON_NAMES: Partial<Record<AtlAlertVariant, AtlIconName>> = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
};

const props = withDefaults(defineProps<AtlAlertProps>(), {
  variant: 'info',
  dismissible: false,
});

const emit = defineEmits<{
  dismissed: [];
}>();

const classes = computed(() => ['atl-alert', `variant-${props.variant}`]);

const ariaLive = computed(() =>
  props.variant === 'danger' || props.variant === 'warning'
    ? 'assertive'
    : 'polite',
);

const variantIconName = computed(() => VARIANT_ICON_NAMES[props.variant]);
</script>

<template>
  <div :class="classes" role="alert" :aria-live="ariaLive">
    <span class="content">
      <AtlIcon
        v-if="variantIconName"
        class="variant-icon"
        :name="variantIconName"
        size="sm"
      />
      <slot />
    </span>
    <button
      v-if="dismissible"
      class="dismiss"
      type="button"
      aria-label="Dismiss"
      @click="emit('dismissed')"
    >
      <AtlIcon name="close" size="sm" />
    </button>
  </div>
</template>

// libs/react/src/lib/alert/atl-alert.tsx
import { HTMLAttributes, ReactNode } from 'react';
import type { AtlAlertSpec, AtlIconName } from '../spec';
import '@atelier-ui/styles/alert/atl-alert.css';
import { AtlIcon } from '../icon/atl-icon';

/** Which AtlIcon each variant carries. Names, not glyphs: a glyph in a string map
 * was the fifth way this library drew an icon, and the one check:icon-duplication
 * missed (ADR-0050). */
const VARIANT_ICON_NAMES: Partial<Record<AtlAlertVariant, AtlIconName>> = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
};

type AtlAlertVariant = 'info' | 'success' | 'warning' | 'danger';

/**
 * Properties for the AtlAlert component.
 */
export interface AtlAlertProps
  extends HTMLAttributes<HTMLDivElement>, AtlAlertSpec {
  /**
   * The visual style variant of the alert.
   */
  variant?: AtlAlertVariant;
  /**
   * Whether the alert can be dismissed by the user.
   */
  dismissible?: boolean;
  /**
   * Callback triggered when the alert is dismissed.
   */
  onDismissed?: () => void;
  /**
   * The content to be rendered inside the alert.
   */
  children?: ReactNode;
}

/**
 * An alert component for displaying important messages.
 */
export function AtlAlert({
  variant = 'info',
  dismissible = false,
  onDismissed,
  children,
  className,
  ...rest
}: AtlAlertProps) {
  const classes = ['atl-alert', `variant-${variant}`, className]
    .filter(Boolean)
    .join(' ');
  const ariaLive =
    variant === 'danger' || variant === 'warning' ? 'assertive' : 'polite';

  return (
    <div className={classes} role="alert" aria-live={ariaLive} {...rest}>
      <span className="content">
        {VARIANT_ICON_NAMES[variant] && (
          <AtlIcon
            className="variant-icon"
            name={VARIANT_ICON_NAMES[variant]}
            size="sm"
          />
        )}
        {children}
      </span>
      {dismissible && (
        <button
          className="dismiss"
          type="button"
          aria-label="Dismiss"
          onClick={onDismissed}
        >
          <AtlIcon name="close" size="sm" />
        </button>
      )}
    </div>
  );
}
