// libs/angular/src/lib/toggle/atl-toggle.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
} from '@angular/core';
import type { FormCheckboxControl } from '@angular/forms/signals';
import { type ValidationError, type WithOptionalFieldTree } from '@angular/forms/signals';

let nextId = 0;

/**
 * Accessible toggle (switch) component for use with Angular Signal Forms.
 * Presents as a pill-shaped on/off slider instead of a checkbox box,
 * but has identical boolean semantics and implements FormCheckboxControl.
 *
 * Usage:
 * ```html
 * <atl-toggle [(checked)]="enabled">Enable notifications</atl-toggle>
 * <atl-toggle [formField]="form.enabled">Enable</atl-toggle>
 * ```
 */
@Component({
  selector: 'atl-toggle',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [attr.for]="inputId">
      <input
        type="checkbox"
        role="switch"
        [id]="inputId"
        [checked]="checked()"
        (change)="onChange($event)"
        (blur)="touched.set(true)"
        [disabled]="disabled()"
        [attr.name]="name() || null"
        [attr.aria-checked]="checked()"
        [attr.aria-invalid]="invalid() || null"
        [attr.aria-required]="required() || null"
        [attr.aria-describedby]="showErrors() ? errorId : null"
      />
      <span class="track" aria-hidden="true">
        <span class="thumb"></span>
      </span>
      <ng-content />
    </label>
    @if (showErrors()) {
      <div class="errors" [id]="errorId" aria-live="polite">
        @for (error of errors(); track error.kind) {
          <p class="error-message">{{ error.message }}</p>
        }
      </div>
    }
  `,
  styleUrl: './atl-toggle.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class AtlToggle implements FormCheckboxControl {
  /** The checked state. Bound by [formField] directive. Supports [(checked)] two-way binding. */
  readonly checked = model(false);

  /** Whether the user has interacted with the input. Bound by [formField] directive. */
  readonly touched = model(false);

  /** Whether the toggle is disabled. Bound by [formField] directive. */
  readonly disabled = input(false);

  /** Whether the toggle has validation errors. Bound by [formField] directive. */
  readonly invalid = input(false);

  /** Whether the toggle is required. Bound by [formField] directive. */
  readonly required = input(false);

  /** The input's name attribute. Bound by [formField] directive. */
  readonly name = input('');

  /** Validation errors from the form system. Bound by [formField] directive. */
  readonly errors = input<readonly WithOptionalFieldTree<ValidationError>[]>([]);

  /** @internal */
  protected readonly inputId = `atl-toggle-${nextId++}`;

  /** @internal */
  protected readonly errorId = `atl-toggle-errors-${nextId++}`;

  /** @internal */
  protected readonly showErrors = computed(
    () => this.touched() && this.invalid() && this.errors().length > 0
  );

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.checked()) classes.push('is-checked');
    if (this.disabled()) classes.push('is-disabled');
    if (this.invalid()) classes.push('is-invalid');
    if (this.touched()) classes.push('is-touched');
    return classes.join(' ');
  });

  /** @internal */
  protected onChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.checked.set(target.checked);
  }
}

// libs/vue/src/lib/toggle/atl-toggle.vue
<script setup lang="ts">
import { computed, useId } from 'vue';
import '@atelier-ui/styles/toggle/atl-toggle.css';

defineOptions({ name: 'AtlToggle' });

interface AtlToggleProps {
  /** The checked state. Two-way bound via `v-model:checked` (emits `update:checked`). */
  checked?: boolean;
  /** Whether the toggle has validation errors; sets `aria-invalid`. */
  invalid?: boolean;
  /** Validation error messages shown below the control and linked to it via `aria-describedby`. */
  errors?: string[];
  /** Whether the toggle is disabled. */
  disabled?: boolean;
  /** Whether the toggle is required. */
  required?: boolean;
  /** The input's `name` attribute. */
  name?: string;
  /** Explicit id for the native input. Wins over the auto-generated id, so an external `<label for>` can point at it. */
  id?: string;
}

const props = withDefaults(defineProps<AtlToggleProps>(), {
  checked: false,
  invalid: false,
  errors: () => [],
  disabled: false,
  required: false,
  name: '',
  id: '',
});

const emit = defineEmits<{
  'update:checked': [value: boolean];
}>();

const inputId = computed(
  () => props.id || `toggle-${Math.random().toString(36).slice(2)}`,
);
const errorsId = useId();

function onChange(event: Event) {
  emit('update:checked', (event.target as HTMLInputElement).checked);
}
</script>

<template>
  <div
    class="atl-toggle"
    :class="{
      'is-checked': checked,
      'is-invalid': invalid,
      'is-disabled': disabled,
    }"
  >
    <label :for="inputId" class="toggle-label">
      <input
        :id="inputId"
        type="checkbox"
        role="switch"
        :checked="checked"
        :disabled="disabled"
        :required="required"
        :name="name"
        :aria-invalid="invalid || undefined"
        :aria-checked="checked"
        :aria-describedby="errors.length > 0 ? errorsId : undefined"
        @change="onChange"
      />
      <span class="track">
        <span class="thumb" />
      </span>
      <slot />
    </label>
    <div v-if="errors.length" :id="errorsId" class="errors" aria-live="polite">
      <p v-for="(error, i) in errors" :key="i" class="error-message">
        {{ error }}
      </p>
    </div>
  </div>
</template>
