// libs/react/src/lib/toggle/atl-toggle.tsx
import { InputHTMLAttributes, ReactNode, useId } from 'react';
import type { AtlToggleSpec } from '../spec';
import './atl-toggle.css';

/**
 * Properties for the AtlToggle component.
 */
export interface AtlToggleProps
  extends
    Omit<
      InputHTMLAttributes<HTMLInputElement>,
      'type' | 'checked' | 'onChange' | 'readOnly' | 'value'
    >,
    AtlToggleSpec {
  /**
   * Callback fired when the checked state changes.
   */
  onCheckedChange?: (checked: boolean) => void;
  /**
   * List of error messages to display.
   */
  errors?: string[];
  /**
   * Optional content to display alongside the toggle.
   */
  children?: ReactNode;
}

/**
 * A toggle switch component for binary choices, supporting validation and custom labels.
 */
export function AtlToggle({
  checked = false,
  onCheckedChange,
  invalid = false,
  errors = [],
  disabled = false,
  required = false,
  children,
  className,
  id,
  name,
  ...rest
}: AtlToggleProps) {
  const generatedId = useId();
  const inputId = id || `toggle-${generatedId}`;
  const errorId = `${inputId}-errors`;

  const classes = [
    'atl-toggle',
    checked && 'is-checked',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes}>
      <label htmlFor={inputId}>
        <input
          type="checkbox"
          role="switch"
          id={inputId}
          checked={checked}
          onChange={(e) => onCheckedChange?.(e.target.checked)}
          disabled={disabled}
          required={required}
          aria-checked={checked}
          aria-invalid={invalid || undefined}
          aria-required={required || undefined}
          aria-describedby={errors.length > 0 ? errorId : undefined}
          name={name}
          {...rest}
        />
        <span className="track" aria-hidden="true">
          <span className="thumb" />
        </span>
        {children}
      </label>
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

// libs/vue/src/lib/toggle/atl-toggle.vue
<script setup lang="ts">
import { computed, useId } from 'vue';
import './atl-toggle.css';

defineOptions({ name: 'AtlToggle' });

interface AtlToggleProps {
  checked?: boolean;
  invalid?: boolean;
  errors?: string[];
  disabled?: boolean;
  required?: boolean;
  name?: string;
  id?: string;
}

const props = withDefaults(defineProps<AtlToggleProps>(), {
  checked: false,
  invalid: false,
  errors: () => [],
  disabled: false,
  required: false,
  name: '',
  id: '',
});

const emit = defineEmits<{
  'update:checked': [value: boolean];
}>();

const inputId = computed(
  () => props.id || `toggle-${Math.random().toString(36).slice(2)}`,
);
const errorsId = useId();

function onChange(event: Event) {
  emit('update:checked', (event.target as HTMLInputElement).checked);
}
</script>

<template>
  <div
    class="atl-toggle"
    :class="{
      'is-checked': checked,
      'is-invalid': invalid,
      'is-disabled': disabled,
    }"
  >
    <label :for="inputId" class="toggle-label">
      <input
        :id="inputId"
        type="checkbox"
        role="switch"
        :checked="checked"
        :disabled="disabled"
        :required="required"
        :name="name"
        :aria-invalid="invalid || undefined"
        :aria-checked="checked"
        :aria-describedby="errors.length > 0 ? errorsId : undefined"
        @change="onChange"
      />
      <span class="track">
        <span class="thumb" />
      </span>
      <slot />
    </label>
    <div v-if="errors.length" :id="errorsId" class="errors" aria-live="polite">
      <p v-for="(error, i) in errors" :key="i" class="error-message">
        {{ error }}
      </p>
    </div>
  </div>
</template>
