// libs/angular/src/lib/alert/llm-alert.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

/**
 * Inline notification banner with semantic color variants and optional dismiss button.
 *
 * Usage:
 * ```html
 * <llm-alert variant="success">Your changes were saved.</llm-alert>
 * <llm-alert variant="warning" [dismissible]="true" (dismissed)="onDismiss()">
 *   Your session expires soon.
 * </llm-alert>
 * ```
 */
const VARIANT_ICONS: Record<'info' | 'success' | 'warning' | 'danger', string> = {
  info: 'ℹ',
  success: '✓',
  warning: '⚠',
  danger: '✕',
};

@Component({
  selector: 'llm-alert',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="content">
      <span class="variant-icon" aria-hidden="true">{{ variantIcon() }}</span>
      <ng-content />
    </span>
    @if (isDismissible) {
      <button class="dismiss" type="button" aria-label="Dismiss" (click)="dismiss()">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <line x1="18" y1="6" x2="6" y2="18" />
          <line x1="6" y1="6" x2="18" y2="18" />
        </svg>
      </button>
    }
  `,
  styleUrl: './llm-alert.css',
  host: {
    '[class]': 'hostClassesValue',
    role: 'alert',
    '[attr.aria-live]': 'ariaLive',
  },
})
export class LlmAlert {
  /** Semantic color variant of the alert. */
  readonly variant = input<'info' | 'success' | 'warning' | 'danger'>('info');

  /** Whether to show a dismiss button. */
  readonly dismissible = input(false);

  /** Emitted when the dismiss button is clicked. */
  readonly dismissed = output<void>();

  protected readonly hostClasses = computed(() => `variant-${this.variant()}`);

  protected readonly variantIcon = computed(() => VARIANT_ICONS[this.variant()]);

  /** @internal */
  get isDismissible(): boolean {
    return this.dismissible();
  }

  /** @internal */
  get hostClassesValue(): string {
    return this.hostClasses();
  }

  /** @internal */
  get ariaLive(): string {
    return this.variant() === 'danger' ? 'assertive' : 'polite';
  }

  protected dismiss(): void {
    this.dismissed.emit();
  }
}

// libs/vue/src/lib/alert/llm-alert.vue
<script setup lang="ts">
import { computed } from 'vue';
import './llm-alert.css';

defineOptions({ name: 'LlmAlert' });

type LlmAlertVariant = 'info' | 'success' | 'warning' | 'danger';

interface LlmAlertProps {
  variant?: LlmAlertVariant;
  dismissible?: boolean;
}

const VARIANT_ICONS: Record<LlmAlertVariant, string> = {
  info: 'ℹ',
  success: '✓',
  warning: '⚠',
  danger: '✕',
};

const props = withDefaults(defineProps<LlmAlertProps>(), {
  variant: 'info',
  dismissible: false,
});

const emit = defineEmits<{
  dismissed: [];
}>();

const classes = computed(() => ['llm-alert', `variant-${props.variant}`]);

const ariaLive = computed(() =>
  props.variant === 'danger' || props.variant === 'warning' ? 'assertive' : 'polite'
);

const variantIcon = computed(() => VARIANT_ICONS[props.variant]);
</script>

<template>
  <div :class="classes" role="alert" :aria-live="ariaLive">
    <span class="content">
      <span class="variant-icon" aria-hidden="true">{{ variantIcon }}</span>
      <slot />
    </span>
    <button
      v-if="dismissible"
      class="dismiss"
      type="button"
      aria-label="Dismiss"
      @click="emit('dismissed')"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <line x1="18" y1="6" x2="6" y2="18" />
        <line x1="6" y1="6" x2="18" y2="18" />
      </svg>
    </button>
  </div>
</template>
