// libs/react/src/lib/input/llm-input.tsx
import { InputHTMLAttributes } from 'react';
import type { LlmInputSpec } from '../spec';
import './llm-input.css';

/**
 * Properties for the LlmInput component.
 */
export interface LlmInputProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'readOnly'>,
    LlmInputSpec {
  /**
   * The type of input to render.
   */
  type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
  /**
   * The current value of the input.
   */
  value?: string;
  /**
   * Callback triggered when the value changes.
   */
  onValueChange?: (value: string) => void;
  /**
   * Whether the input is in an invalid state.
   */
  invalid?: boolean;
  /**
   * Array of error messages to display.
   */
  errors?: string[];
  /**
   * The label for the input.
   */
  label?: string;
  /**
   * Whether the input is read-only.
   */
  readOnly?: boolean;
}

/**
 * A versatile input component for text entry.
 */
export function LlmInput({
  type = 'text',
  value,
  onChange,
  onValueChange,
  invalid = false,
  errors = [],
  disabled = false,
  readOnly: reactReadOnly,
  readonly: specReadOnly,
  required = false,
  label,
  className,
  id,
  ...rest
}: LlmInputProps) {
  const readOnly = reactReadOnly ?? specReadOnly ?? false;
  const inputId =
    id || (label ? `input-${label.toLowerCase().replace(/\s+/g, '-')}` : undefined);
  const classes = [
    'llm-input',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    readOnly && 'is-readonly',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onChange?.(e);
    onValueChange?.(e.target.value);
  };

  const errorId = inputId ? `${inputId}-errors` : undefined;

  return (
    <div className={classes}>
      {label && <label htmlFor={inputId}>{label}</label>}
      <div className="input-field">
        <input
          id={inputId}
          type={type}
          value={value}
          onChange={handleChange}
          disabled={disabled}
          readOnly={readOnly}
          required={required}
          aria-invalid={invalid || undefined}
          aria-required={required || undefined}
          aria-describedby={errors.length > 0 ? errorId : undefined}
          {...rest}
        />
      </div>
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

// libs/angular/src/lib/input/llm-input.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
} from '@angular/core';
import type { FormValueControl } from '@angular/forms/signals';
import { type ValidationError, type WithOptionalFieldTree } from '@angular/forms/signals';

let nextId = 0;

/**
 * Accessible text input component for use with Angular Signal Forms.
 *
 * Usage:
 * ```html
 * <llm-input type="email" placeholder="you@example.com" [(value)]="email" />
 * <llm-input [formField]="loginForm.email" placeholder="Email" />
 * ```
 */
@Component({
  selector: 'llm-input',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <input
      [type]="type()"
      [value]="value()"
      (input)="onInput($event)"
      (blur)="touched.set(true)"
      [disabled]="disabled()"
      [readOnly]="readonly()"
      [placeholder]="placeholder()"
      [attr.name]="name() || null"
      [attr.aria-invalid]="invalid() || null"
      [attr.aria-required]="required() || null"
      [attr.aria-describedby]="showErrors() ? errorId : null"
    />
    @if (showErrors()) {
      <div class="errors" [id]="errorId" aria-live="polite">
        @for (error of errors(); track error.kind) {
          <p class="error-message">{{ error.message }}</p>
        }
      </div>
    }
  `,
  styleUrl: './llm-input.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class LlmInput implements FormValueControl<string> {
  /** The current input value. Bound by [formField] directive. Supports [(value)] two-way binding. */
  readonly value = model('');

  /** The type of input field. */
  readonly type = input<'text' | 'email' | 'password' | 'number' | 'tel' | 'url'>('text');

  /** Placeholder text shown when the input is empty. */
  readonly placeholder = input('');

  /** Whether the input is disabled. Bound by [formField] directive. */
  readonly disabled = input(false);

  /** Whether the input is read-only. Bound by [formField] directive. */
  readonly readonly = input(false);

  /** Whether the input has validation errors. Bound by [formField] directive. */
  readonly invalid = input(false);

  /** Validation errors from the form system. Bound by [formField] directive. */
  readonly errors = input<readonly WithOptionalFieldTree<ValidationError>[]>([]);

  /** Whether the user has interacted with the input. Bound by [formField] directive. */
  readonly touched = model(false);

  /** Whether the input is required. Bound by [formField] directive. */
  readonly required = input(false);

  /** The input's name attribute. Bound by [formField] directive. */
  readonly name = input('');

  /** @internal */
  protected readonly errorId = `llm-input-errors-${nextId++}`;

  /** @internal */
  protected readonly showErrors = computed(
    () => this.touched() && this.invalid() && this.errors().length > 0
  );

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.disabled()) classes.push('is-disabled');
    if (this.invalid()) classes.push('is-invalid');
    if (this.readonly()) classes.push('is-readonly');
    if (this.touched()) classes.push('is-touched');
    return classes.join(' ');
  });

  /** @internal */
  protected onInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.value.set(target.value);
  }
}
