// libs/vue/src/lib/table/atl-table.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@atelier-ui/styles/table/atl-table.css';

defineOptions({ name: 'AtlTable' });

interface Props {
  /** Visual style of the table rows. */
  variant?: 'default' | 'striped' | 'bordered';
  /** Row density. */
  size?: 'sm' | 'md' | 'lg';
  /** Whether the header row sticks to the top when the table scrolls. */
  stickyHeader?: boolean;
  /**
   * Accessible name for the scrollable table region. Surfaces to
   * screen readers as the region's label so keyboard users who
   * scroll the wrapper know what they're scrolling. Defaults to
   * `"Table"` if unset.
   */
  ariaLabel?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  size: 'md',
  stickyHeader: false,
  ariaLabel: undefined,
});

const classes = computed(() => [
  'atl-table',
  `variant-${props.variant}`,
  `size-${props.size}`,
  props.stickyHeader && 'is-sticky-header',
]);
</script>

<template>
  <div :class="classes">
    <!-- Scrollable wrapper: tabindex=0 + role/aria-label so keyboard
         users can scroll wide tables horizontally and screen readers
         announce the region (axe: scrollable-region-focusable). -->
    <div
      class="atl-table-wrapper"
      tabindex="0"
      role="region"
      :aria-label="ariaLabel ?? 'Table'"
    >
      <table>
        <slot />
      </table>
    </div>
  </div>
</template>

// libs/react/src/lib/table/atl-table.tsx
import {
  HTMLAttributes,
  ReactNode,
  TdHTMLAttributes,
  ThHTMLAttributes,
} from 'react';
import type {
  AtlTableSpec,
  AtlTbodySpec,
  AtlTrSpec,
  AtlThSpec,
  AtlTdSpec,
  AtlSortDirection,
} from '../spec';
import { AtlCheckbox } from '../checkbox/atl-checkbox';
import '@atelier-ui/styles/table/atl-table.css';
import { AtlIcon } from '../icon/atl-icon';

export type { AtlSortDirection };

// ---------------------------------------------------------------------------
// AtlTable
// ---------------------------------------------------------------------------

export interface AtlTableProps
  extends HTMLAttributes<HTMLDivElement>, AtlTableSpec {
  /**
   * Visual style of the table rows.
   */
  variant?: 'default' | 'striped' | 'bordered';
  /**
   * Row density: the vertical padding of cells.
   */
  size?: 'sm' | 'md' | 'lg';
  /**
   * Whether the header row sticks to the top when the table scrolls.
   */
  stickyHeader?: boolean;
  /**
   * The table sections: `AtlThead` and `AtlTbody` elements.
   */
  children?: ReactNode;
  /**
   * Accessible name for the scrollable table region. Surfaces to
   * screen readers as the region's label so keyboard users who
   * scroll the wrapper know what they're scrolling. Defaults to
   * `"Table"` if unset.
   */
  'aria-label'?: string;
}

export function AtlTable({
  variant = 'default',
  size = 'md',
  stickyHeader = false,
  children,
  className,
  'aria-label': ariaLabel,
  ...rest
}: AtlTableProps) {
  const classes = [
    'atl-table',
    `variant-${variant}`,
    `size-${size}`,
    stickyHeader && 'is-sticky-header',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes} {...rest}>
      {/* The wrapper is the scrollable region — give it tabindex=0 so
       * keyboard users can scroll horizontally through wide tables.
       * role=region + aria-label expose it as a labelled landmark for
       * screen readers (axe rule: scrollable-region-focusable). */}
      <div
        className="atl-table-wrapper"
        tabIndex={0}
        role="region"
        aria-label={ariaLabel ?? 'Table'}
      >
        <table>{children}</table>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// AtlThead
// ---------------------------------------------------------------------------

export interface AtlTheadProps {
  children?: ReactNode;
}

export function AtlThead({ children }: AtlTheadProps) {
  return <thead>{children}</thead>;
}

// ---------------------------------------------------------------------------
// AtlTbody
// ---------------------------------------------------------------------------

export interface AtlTbodyProps extends AtlTbodySpec {
  children?: ReactNode;
  /** Content shown in place of rows when empty=true. */
  emptyContent?: ReactNode;
}

export function AtlTbody({
  empty = false,
  colSpan = 1,
  children,
  emptyContent,
}: AtlTbodyProps) {
  return (
    <tbody>
      {!empty ? (
        children
      ) : (
        <tr>
          <td colSpan={colSpan} className="atl-tbody-empty-cell">
            {emptyContent}
          </td>
        </tr>
      )}
    </tbody>
  );
}

// ---------------------------------------------------------------------------
// AtlTr
// ---------------------------------------------------------------------------

export interface AtlTrProps extends AtlTrSpec {
  children?: ReactNode;
  onSelectedChange?: (selected: boolean) => void;
}

export function AtlTr({
  selected = false,
  selectable = false,
  children,
  onSelectedChange,
}: AtlTrProps) {
  return (
    <tr
      aria-selected={selectable ? selected : undefined}
      className={selected ? 'is-selected' : undefined}
    >
      {selectable && (
        <td className="atl-tr-select-cell">
          <AtlCheckbox checked={selected} onCheckedChange={onSelectedChange} />
        </td>
      )}
      {children}
    </tr>
  );
}

// ---------------------------------------------------------------------------
// AtlTh
// ---------------------------------------------------------------------------

export interface AtlThProps
  extends Omit<ThHTMLAttributes<HTMLTableCellElement>, 'align'>, AtlThSpec {
  children?: ReactNode;
  onSort?: (direction: AtlSortDirection) => void;
}

export function AtlTh({
  sortable = false,
  sortDirection = null,
  align = 'start',
  width,
  children,
  onSort,
  className,
  ...rest
}: AtlThProps) {
  const classes =
    [
      `align-${align}`,
      sortDirection && 'is-sorted',
      sortDirection === 'asc' && 'sort-asc',
      sortDirection === 'desc' && 'sort-desc',
      className,
    ]
      .filter(Boolean)
      .join(' ') || undefined;

  const ariaSort = sortable
    ? sortDirection === 'asc'
      ? 'ascending'
      : sortDirection === 'desc'
        ? 'descending'
        : 'none'
    : undefined;

  function cycleSort() {
    const next: AtlSortDirection =
      sortDirection === null ? 'asc' : sortDirection === 'asc' ? 'desc' : null;
    onSort?.(next);
  }

  return (
    <th
      aria-sort={ariaSort}
      style={width ? { width } : undefined}
      className={classes}
      {...rest}
    >
      {sortable ? (
        <button type="button" className="atl-th-sort-btn" onClick={cycleSort}>
          {children}
          <span className="atl-th-sort-icon" aria-hidden="true">
            <AtlIcon
              name="sort-asc"
              size="sm"
              className="atl-th-sort-asc-arrow"
            />
            <AtlIcon
              name="sort-desc"
              size="sm"
              className="atl-th-sort-desc-arrow"
            />
          </span>
        </button>
      ) : (
        children
      )}
    </th>
  );
}

// ---------------------------------------------------------------------------
// AtlTd
// ---------------------------------------------------------------------------

export interface AtlTdProps
  extends Omit<TdHTMLAttributes<HTMLTableCellElement>, 'align'>, AtlTdSpec {
  children?: ReactNode;
}

export function AtlTd({
  align = 'start',
  children,
  className,
  ...rest
}: AtlTdProps) {
  const classes = [`align-${align}`, className].filter(Boolean).join(' ');
  return (
    <td className={classes} {...rest}>
      {children}
    </td>
  );
}
