// libs/vue/src/lib/avatar/atl-avatar.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import '@atelier-ui/styles/avatar/atl-avatar.css';
import AtlIcon from '../icon/atl-icon.vue';

defineOptions({ name: 'AtlAvatar' });

interface AtlAvatarProps {
  /** Image URL. Falls back to initials if empty or if the image fails to load. */
  src?: string;
  /** Alt text for the image (also used as the accessible label). */
  alt?: string;
  /** Full name used to generate the initials fallback and the default accessible label. */
  name?: string;
  /** Size of the avatar. */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /** Shape of the avatar. */
  shape?: 'circle' | 'square';
  /** Presence status indicator dot. Empty string hides the dot. */
  status?: 'online' | 'offline' | 'away' | 'busy' | '';
}

const props = withDefaults(defineProps<AtlAvatarProps>(), {
  src: '',
  alt: '',
  name: '',
  size: 'md',
  shape: 'circle',
  status: '',
});

const imgError = ref(false);

watch(
  () => props.src,
  () => {
    imgError.value = false;
  },
);

function getInitials(name: string): string {
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0].toUpperCase())
    .join('');
}

const initials = computed(() => (props.name ? getInitials(props.name) : ''));
const ariaLabel = computed(() => props.alt || props.name || 'Avatar');

const classes = computed(() => [
  'atl-avatar',
  `size-${props.size}`,
  `shape-${props.shape}`,
]);
</script>

<template>
  <div :class="classes" :aria-label="ariaLabel" role="img">
    <img
      v-if="src && !imgError"
      :src="src"
      :alt="alt || name"
      @error="imgError = true"
    />
    <span v-else-if="initials" class="initials">{{ initials }}</span>
    <AtlIcon name="person" size="sm" class="icon" />
    <span
      v-if="status"
      :class="`status-dot status-${status}`"
      aria-hidden="true"
    />
  </div>
</template>

// libs/react/src/lib/avatar/atl-avatar.tsx
import { HTMLAttributes, ReactNode, Children, useState } from 'react';
import type { AtlAvatarSpec, AtlAvatarGroupSpec } from '../spec';
import '@atelier-ui/styles/avatar/atl-avatar.css';
import { AtlIcon } from '../icon/atl-icon';

/**
 * Properties for the AtlAvatar component.
 */
export interface AtlAvatarProps
  extends HTMLAttributes<HTMLDivElement>, AtlAvatarSpec {
  /**
   * The URL of the image to display.
   */
  src?: string;
  /**
   * Accessible text for the avatar image.
   */
  alt?: string;
  /**
   * The name of the person/entity, used for initials if no image is provided.
   */
  name?: string;
  /**
   * The size of the avatar.
   */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /**
   * The shape of the avatar.
   */
  shape?: 'circle' | 'square';
  /**
   * The status indicator to display on the avatar.
   */
  status?: 'online' | 'offline' | 'away' | 'busy' | '';
}

function getInitials(name: string): string {
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0].toUpperCase())
    .join('');
}

/**
 * An avatar component for displaying user profile pictures or initials.
 */
export function AtlAvatar({
  src = '',
  alt = '',
  name = '',
  size = 'md',
  shape = 'circle',
  status = '',
  className,
  ...rest
}: AtlAvatarProps) {
  const [imgError, setImgError] = useState(false);
  const [prevSrc, setPrevSrc] = useState(src);

  // Reset imgError when src changes
  if (src !== prevSrc) {
    setPrevSrc(src);
    setImgError(false);
  }

  const classes = ['atl-avatar', `size-${size}`, `shape-${shape}`, className]
    .filter(Boolean)
    .join(' ');

  const initials = name ? getInitials(name) : '';
  const ariaLabel = alt || name || 'Avatar';

  return (
    <div className={classes} aria-label={ariaLabel} role="img" {...rest}>
      {src && !imgError ? (
        <img src={src} alt={alt || name} onError={() => setImgError(true)} />
      ) : initials ? (
        <span className="initials" aria-hidden="true">
          {initials}
        </span>
      ) : (
        <AtlIcon name="person" size="sm" className="icon" />
      )}
      {status && (
        <span className={`status-dot status-${status}`} aria-hidden="true" />
      )}
    </div>
  );
}

/**
 * Properties for the AtlAvatarGroup component.
 */
export interface AtlAvatarGroupProps
  extends HTMLAttributes<HTMLDivElement>, AtlAvatarGroupSpec {
  /**
   * The maximum number of avatars to show before displaying an overflow badge.
   */
  max?: number;
  /**
   * The size of the avatars in the group.
   */
  size?: AtlAvatarProps['size'];
  /**
   * The avatars to be rendered in the group.
   */
  children?: ReactNode;
}

/**
 * A container for grouping multiple avatars.
 */
export function AtlAvatarGroup({
  max = 5,
  size = 'md',
  children,
  className,
  ...rest
}: AtlAvatarGroupProps) {
  const childArray = Children.toArray(children);
  const visible = childArray.slice(0, max);
  const overflow = childArray.length - max;

  const classes = ['atl-avatar-group', `size-${size}`, className]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes} {...rest}>
      {visible}
      {overflow > 0 && (
        <div
          className={`overflow-badge size-${size}`}
          aria-label={`+${overflow} more`}
        >
          +{overflow}
        </div>
      )}
    </div>
  );
}
