// libs/react/src/lib/pagination/atl-pagination.tsx
import { HTMLAttributes, useMemo } from 'react';
import type { AtlPaginationSpec } from '../spec';
import '@atelier-ui/styles/pagination/atl-pagination.css';
import { AtlIcon } from '../icon/atl-icon';

type PageItem =
  { type: 'page'; page: number } | { type: 'ellipsis'; key: string };

function buildPageItems(
  page: number,
  pageCount: number,
  siblingCount: number,
): PageItem[] {
  if (pageCount <= 1) return [{ type: 'page', page: 1 }];

  const items: PageItem[] = [];

  // Always include first page
  items.push({ type: 'page', page: 1 });

  const left = Math.max(2, page - siblingCount);
  const right = Math.min(pageCount - 1, page + siblingCount);

  // Left ellipsis
  if (left > 2) {
    items.push({ type: 'ellipsis', key: 'ellipsis-start' });
  }

  // Middle pages
  for (let p = left; p <= right; p++) {
    items.push({ type: 'page', page: p });
  }

  // Right ellipsis
  if (right < pageCount - 1) {
    items.push({ type: 'ellipsis', key: 'ellipsis-end' });
  }

  // Always include last page
  items.push({ type: 'page', page: pageCount });

  return items;
}

/**
 * Properties for the AtlPagination component.
 */
export interface AtlPaginationProps
  extends Omit<HTMLAttributes<HTMLElement>, 'onChange'>, AtlPaginationSpec {
  /**
   * The currently active page.
   */
  page?: number;
  /**
   * The total number of pages.
   */
  pageCount?: number;
  /**
   * The number of pages to show on either side of the current page.
   */
  siblingCount?: number;
  /**
   * Whether to show buttons for first and last pages.
   */
  showFirstLast?: boolean;
  /**
   * Callback triggered when the page changes.
   */
  onPageChange?: (page: number) => void;
}

/**
 * A pagination component for navigating through paged content.
 */
export function AtlPagination({
  page = 1,
  pageCount = 1,
  siblingCount = 1,
  showFirstLast = true,
  onPageChange,
  className,
  ...rest
}: AtlPaginationProps) {
  const classes = ['atl-pagination', className].filter(Boolean).join(' ');

  const pageItems = useMemo(
    () => buildPageItems(page, pageCount, siblingCount),
    [page, pageCount, siblingCount],
  );

  const goTo = (p: number) => {
    const clamped = Math.min(Math.max(p, 1), pageCount);
    if (clamped !== page) {
      onPageChange?.(clamped);
    }
  };

  return (
    <nav className={classes} aria-label="Pagination" {...rest}>
      <ul className="page-list">
        {showFirstLast && (
          <li>
            <button
              className={['page-btn', page <= 1 ? 'is-disabled' : '']
                .filter(Boolean)
                .join(' ')}
              disabled={page <= 1}
              aria-label="First page"
              onClick={() => goTo(1)}
            >
              <AtlIcon name="chevron-double-left" size="sm" />
            </button>
          </li>
        )}
        <li>
          <button
            className={['page-btn', page <= 1 ? 'is-disabled' : '']
              .filter(Boolean)
              .join(' ')}
            disabled={page <= 1}
            aria-label="Previous page"
            onClick={() => goTo(page - 1)}
          >
            <AtlIcon name="chevron-left" size="sm" />
          </button>
        </li>

        {pageItems.map((item, index) =>
          item.type === 'page' ? (
            <li key={item.page}>
              <button
                className={['page-btn', item.page === page ? 'is-active' : '']
                  .filter(Boolean)
                  .join(' ')}
                aria-current={item.page === page ? 'page' : undefined}
                aria-label={`Page ${item.page}`}
                onClick={() => goTo(item.page)}
              >
                {item.page}
              </button>
            </li>
          ) : (
            <li key={item.key}>
              <span className="ellipsis" aria-hidden="true">
                …
              </span>
            </li>
          ),
        )}

        <li>
          <button
            className={['page-btn', page >= pageCount ? 'is-disabled' : '']
              .filter(Boolean)
              .join(' ')}
            disabled={page >= pageCount}
            aria-label="Next page"
            onClick={() => goTo(page + 1)}
          >
            <AtlIcon name="chevron-right" size="sm" />
          </button>
        </li>
        {showFirstLast && (
          <li>
            <button
              className={['page-btn', page >= pageCount ? 'is-disabled' : '']
                .filter(Boolean)
                .join(' ')}
              disabled={page >= pageCount}
              aria-label="Last page"
              onClick={() => goTo(pageCount)}
            >
              <AtlIcon name="chevron-double-right" size="sm" />
            </button>
          </li>
        )}
      </ul>
    </nav>
  );
}

// libs/vue/src/lib/pagination/atl-pagination.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@atelier-ui/styles/pagination/atl-pagination.css';
import AtlIcon from '../icon/atl-icon.vue';

defineOptions({ name: 'AtlPagination' });

interface AtlPaginationProps {
  /** Current page (1-based). Controlled: listen to `pageChange` and feed the new page back in. */
  page?: number;
  /** Total number of pages. */
  pageCount?: number;
  /** Number of page buttons to show on each side of the current page. */
  siblingCount?: number;
  /** Whether to show first/last page jump buttons. */
  showFirstLast?: boolean;
}

const props = withDefaults(defineProps<AtlPaginationProps>(), {
  page: 1,
  pageCount: 1,
  siblingCount: 1,
  showFirstLast: true,
});

const emit = defineEmits<{
  pageChange: [page: number];
}>();

type PageItem =
  { type: 'page'; page: number } | { type: 'ellipsis'; key: string };

function buildPageItems(
  page: number,
  pageCount: number,
  siblingCount: number,
): PageItem[] {
  if (pageCount <= 1) return [{ type: 'page', page: 1 }];
  const items: PageItem[] = [];
  items.push({ type: 'page', page: 1 });
  const left = Math.max(2, page - siblingCount);
  const right = Math.min(pageCount - 1, page + siblingCount);
  if (left > 2) items.push({ type: 'ellipsis', key: 'ellipsis-start' });
  for (let p = left; p <= right; p++) items.push({ type: 'page', page: p });
  if (right < pageCount - 1)
    items.push({ type: 'ellipsis', key: 'ellipsis-end' });
  if (pageCount > 1) items.push({ type: 'page', page: pageCount });
  return items;
}

const pageItems = computed(() =>
  buildPageItems(props.page, props.pageCount, props.siblingCount),
);

function goTo(p: number) {
  const clamped = Math.min(Math.max(p, 1), props.pageCount);
  if (clamped !== props.page) {
    emit('pageChange', clamped);
  }
}
</script>

<template>
  <nav class="atl-pagination" aria-label="Pagination">
    <ul class="page-list">
      <li v-if="showFirstLast">
        <button
          class="page-btn nav-btn"
          :class="{ 'is-disabled': page <= 1 }"
          :disabled="page <= 1"
          aria-label="First page"
          @click="goTo(1)"
        >
          <AtlIcon name="chevron-double-left" size="sm" />
        </button>
      </li>
      <li>
        <button
          class="page-btn nav-btn"
          :class="{ 'is-disabled': page <= 1 }"
          :disabled="page <= 1"
          aria-label="Previous page"
          @click="goTo(page - 1)"
        >
          <AtlIcon name="chevron-left" size="sm" />
        </button>
      </li>

      <template
        v-for="item in pageItems"
        :key="item.type === 'page' ? item.page : item.key"
      >
        <li v-if="item.type === 'ellipsis'">
          <span class="ellipsis" aria-hidden="true">…</span>
        </li>
        <li v-else>
          <button
            class="page-btn"
            :class="{ 'is-active': item.page === page }"
            :aria-label="`Page ${item.page}`"
            :aria-current="item.page === page ? 'page' : undefined"
            @click="goTo(item.page)"
          >
            {{ item.page }}
          </button>
        </li>
      </template>

      <li>
        <button
          class="page-btn nav-btn"
          :class="{ 'is-disabled': page >= pageCount }"
          :disabled="page >= pageCount"
          aria-label="Next page"
          @click="goTo(page + 1)"
        >
          <AtlIcon name="chevron-right" size="sm" />
        </button>
      </li>
      <li v-if="showFirstLast">
        <button
          class="page-btn nav-btn"
          :class="{ 'is-disabled': page >= pageCount }"
          :disabled="page >= pageCount"
          aria-label="Last page"
          @click="goTo(pageCount)"
        >
          <AtlIcon name="chevron-double-right" size="sm" />
        </button>
      </li>
    </ul>
  </nav>
</template>
