// libs/react/src/lib/accordion/atl-accordion.tsx
import {
  createContext,
  useContext,
  useState,
  useRef,
  useId,
  useLayoutEffect,
  useCallback,
  ReactNode,
  HTMLAttributes,
  KeyboardEvent,
} from 'react';
import type {
  AtlAccordionGroupSpec,
  AtlAccordionItemSpec,
} from '../spec';
import './atl-accordion.css';

interface AccordionGroupContextValue {
  multi: boolean;
  openItems: Set<string>;
  toggleItem: (id: string) => void;
  registerItem: (id: string, ref: React.RefObject<HTMLButtonElement | null>, disabled: boolean) => void;
  unregisterItem: (id: string) => void;
  handleKeydown: (e: KeyboardEvent, id: string) => void;
}

const AccordionGroupContext = createContext<AccordionGroupContextValue>({
  multi: false,
  openItems: new Set(),
  toggleItem: () => { /* noop */ },
  registerItem: () => { /* noop */ },
  unregisterItem: () => { /* noop */ },
  handleKeydown: () => { /* noop */ },
});

/**
 * Properties for the AtlAccordionGroup component.
 */
export interface AtlAccordionGroupProps
  extends HTMLAttributes<HTMLDivElement>,
    AtlAccordionGroupSpec {
  /**
   * Whether multiple items can be expanded simultaneously.
   */
  multi?: boolean;
  /**
   * The visual style variant of the accordion.
   */
  variant?: 'default' | 'bordered' | 'separated';
  /**
   * The accordion items to be rendered.
   */
  children?: ReactNode;
}

/**
 * A container component that manages a group of accordion items.
 */
export function AtlAccordionGroup({
  multi = false,
  variant = 'default',
  children,
  className,
  ...rest
}: AtlAccordionGroupProps) {
  const [openItems, setOpenItems] = useState<Set<string>>(new Set());
  const itemsRef = useRef<{ id: string; triggerRef: React.RefObject<HTMLButtonElement | null>; disabled: boolean }[]>([]);

  const classes = ['atl-accordion-group', `variant-${variant}`, className]
    .filter(Boolean)
    .join(' ');

  const toggleItem = useCallback((id: string) => {
    setOpenItems((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        if (!multi) next.clear();
        next.add(id);
      }
      return next;
    });
  }, [multi]);

  const registerItem = useCallback((id: string, ref: React.RefObject<HTMLButtonElement | null>, disabled: boolean) => {
    itemsRef.current = [...itemsRef.current.filter((i) => i.id !== id), { id, triggerRef: ref, disabled }];
  }, []);

  const unregisterItem = useCallback((id: string) => {
    itemsRef.current = itemsRef.current.filter((i) => i.id !== id);
  }, []);

  const handleKeydown = useCallback((e: KeyboardEvent, currentId: string) => {
    const enabled = itemsRef.current.filter((i) => !i.disabled);
    if (enabled.length === 0) return;

    const pos = enabled.findIndex((i) => i.id === currentId);
    const n = enabled.length;
    let target: (typeof enabled)[0] | null = null;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      target = enabled[(pos + 1) % n];
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      target = enabled[(pos - 1 + n) % n];
    } else if (e.key === 'Home') {
      e.preventDefault();
      target = enabled[0];
    } else if (e.key === 'End') {
      e.preventDefault();
      target = enabled[n - 1];
    }

    target?.triggerRef.current?.focus();
  }, []);

  return (
    <AccordionGroupContext.Provider
      value={{ multi, openItems, toggleItem, registerItem, unregisterItem, handleKeydown }}
    >
      <div className={classes} role="presentation" {...rest}>
        {children}
      </div>
    </AccordionGroupContext.Provider>
  );
}

/**
 * Properties for the AtlAccordionItem component.
 */
export interface AtlAccordionItemProps
  extends HTMLAttributes<HTMLDivElement>,
    AtlAccordionItemSpec {
  /**
   * Whether the item is currently expanded.
   */
  expanded?: boolean;
  /**
   * Callback triggered when the expanded state changes.
   */
  onExpandedChange?: (expanded: boolean) => void;
  /**
   * Whether the accordion item is disabled.
   */
  disabled?: boolean;
  /**
   * HTML heading level wrapping the trigger button. Default `3`.
   * Match your page's heading outline so heading order stays valid.
   */
  headingLevel?: 1 | 2 | 3 | 4 | 5 | 6;
  /**
   * The content of the accordion item, typically including an AtlAccordionHeader.
   */
  children?: ReactNode;
}

/**
 * An individual item within an accordion group.
 */
export function AtlAccordionItem({
  expanded: externalExpanded,
  onExpandedChange,
  disabled = false,
  headingLevel = 3,
  children,
  className,
  ...rest
}: AtlAccordionItemProps) {
  const ctx = useContext(AccordionGroupContext);
  const id = useId();
  const triggerId = `${id}-trigger`;
  const panelId = `${id}-panel`;
  const triggerRef = useRef<HTMLButtonElement>(null);

  const { registerItem, unregisterItem } = ctx;

  // Register/unregister with parent
  useLayoutEffect(() => {
    registerItem(id, triggerRef, disabled);
    return () => unregisterItem(id);
  }, [id, triggerRef, disabled, registerItem, unregisterItem]);

  const isControlled = externalExpanded !== undefined;
  const isExpanded = isControlled ? externalExpanded : ctx.openItems.has(id);

  const toggle = () => {
    if (disabled) return;
    const next = !isExpanded;
    if (!isControlled) ctx.toggleItem(id);
    onExpandedChange?.(next);
  };

  const classes = [
    'atl-accordion-item',
    isExpanded && 'is-expanded',
    disabled && 'is-disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  // Separate header child from body children
  const childArray = Array.isArray(children) ? children : [children];
  const headerNode = childArray.find(
    (c): c is React.ReactElement =>
      typeof c === 'object' &&
      c !== null &&
      'type' in (c as object) &&
      (c as React.ReactElement).type === AtlAccordionHeader
  );
  const bodyNodes = childArray.filter((c) => c !== headerNode);

  // Render the heading wrapper at the level the consumer asked for.
  // We can't use a JSX expression as a tag, so React.createElement is
  // the cleanest path here.
  const Heading = `h${headingLevel}` as 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
  return (
    <div className={classes} {...rest}>
      <Heading className="accordion-heading">
        <button
          ref={triggerRef}
          type="button"
          id={triggerId}
          className={['accordion-trigger', disabled && 'is-disabled']
            .filter(Boolean)
            .join(' ')}
          aria-expanded={isExpanded}
          aria-controls={panelId}
          aria-disabled={disabled || undefined}
          disabled={disabled}
          onClick={toggle}
          onKeyDown={(e) => ctx.handleKeydown(e, id)}
        >
          {headerNode}
          <svg
            className={['chevron', isExpanded && 'is-expanded']
              .filter(Boolean)
              .join(' ')}
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            aria-hidden="true"
          >
            <path
              d="M4 6L8 10L12 6"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>
      </Heading>
      <div
        className={['accordion-panel-wrapper', isExpanded && 'is-expanded']
          .filter(Boolean)
          .join(' ')}
      >
        <div
          id={panelId}
          role="region"
          aria-labelledby={triggerId}
          className="accordion-panel"
        >
          {bodyNodes}
        </div>
      </div>
    </div>
  );
}

/**
 * The header component for an AtlAccordionItem.
 */
export function AtlAccordionHeader({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLSpanElement> & {
  /**
   * The content to be rendered in the header.
   */
  children?: ReactNode;
}) {
  return (
    <span
      className={['accordion-header-content', className].filter(Boolean).join(' ')}
      {...rest}
    >
      {children}
    </span>
  );
}

// libs/angular/src/lib/accordion/atl-accordion.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  Directive,
  ElementRef,
  inject,
  input,
  model,
  OnDestroy,
  OnInit,
  signal,
} from '@angular/core';
import { CdkAccordion, CdkAccordionItem } from '@angular/cdk/accordion';
import { ATL_ACCORDION_GROUP, type AccordionItem, type AtlAccordionGroupContext } from './atl-accordion.token';

let nextId = 0;

/**
 * Container that manages accordion items. Controls single vs multi expansion
 * and provides keyboard navigation across items.
 *
 * Usage:
 * ```html
 * <atl-accordion-group [multi]="true" variant="separated">
 *   <atl-accordion-item [(expanded)]="open">
 *     <span atlAccordionHeader>Title</span>
 *     Body content here.
 *   </atl-accordion-item>
 * </atl-accordion-group>
 * ```
 */
@Component({
  selector: 'atl-accordion-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  styleUrl: './atl-accordion.css',
  hostDirectives: [{ directive: CdkAccordion, inputs: ['multi'] }],
  host: {
    '[class]': 'hostClassesValue',
    role: 'presentation',
  },
  providers: [{ provide: ATL_ACCORDION_GROUP, useExisting: AtlAccordionGroup }],
})
export class AtlAccordionGroup implements AtlAccordionGroupContext {
  /** Allow multiple items to be expanded simultaneously. */
  readonly multi = input(false);

  /** Visual variant. */
  readonly variant = input<'default' | 'bordered' | 'separated'>('default');

  /** @internal */
  protected readonly hostClasses = computed(() => `atl-accordion-group variant-${this.variant()}`);

  /** @internal */
  get hostClassesValue(): string {
    return this.hostClasses();
  }

  /** @internal */
  private readonly items = signal<AccordionItem[]>([]);

  register(item: AccordionItem): void {
    this.items.update((list) => [...list, item]);
  }

  unregister(item: AccordionItem): void {
    this.items.update((list) => list.filter((i) => i !== item));
  }

  handleKeydown(event: KeyboardEvent, item: AccordionItem): void {
    const enabledItems = this.items().filter((i) => !i.disabled);
    const len = enabledItems.length;
    if (len === 0) return;

    const currentIdx = enabledItems.indexOf(item);

    let targetItem: AccordionItem | null = null;

    switch (event.key) {
      case 'ArrowDown':
        targetItem = enabledItems[(currentIdx + 1) % len];
        break;
      case 'ArrowUp':
        targetItem = enabledItems[(currentIdx - 1 + len) % len];
        break;
      case 'Home':
        targetItem = enabledItems[0];
        break;
      case 'End':
        targetItem = enabledItems[len - 1];
        break;
      default:
        return;
    }

    event.preventDefault();
    targetItem.focus();
  }
}

/**
 * Directive to mark the accordion header content.
 */
@Directive({
  selector: '[atlAccordionHeader]',
  standalone: true,
})
export class AtlAccordionHeader {}

/**
 * Individual collapsible accordion item. Place inside `<atl-accordion-group>`.
 *
 * Usage:
 * ```html
 * <atl-accordion-item [(expanded)]="isOpen">
 *   <span atlAccordionHeader>Section Title</span>
 *   Section content goes here.
 * </atl-accordion-item>
 * ```
 */
@Component({
  selector: 'atl-accordion-item',
  standalone: true,
  imports: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [CdkAccordionItem],
  template: `
    <div role="heading" [attr.aria-level]="headingLevel()" class="accordion-heading">
      <button
        type="button"
        class="accordion-trigger"
        [id]="triggerId"
        [attr.aria-expanded]="isExpandedValue"
        [attr.aria-controls]="panelId"
        [attr.aria-disabled]="ariaDisabled"
        [class.is-disabled]="isDisabled"
        (click)="onToggle()"
        (keydown)="onKeydown($event)"
      >
        <ng-content select="[atlAccordionHeader]" />
        <svg
          class="chevron"
          [class.is-expanded]="isExpandedValue"
          width="16"
          height="16"
          viewBox="0 0 16 16"
          fill="none"
          aria-hidden="true"
        >
          <path
            d="M4 6L8 10L12 6"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </button>
    </div>
    <div
      class="accordion-panel-wrapper"
      [class.is-expanded]="isExpandedValue"
    >
      <div
        role="region"
        [id]="panelId"
        [attr.aria-labelledby]="triggerId"
        class="accordion-panel"
      >
        <ng-content />
      </div>
    </div>
  `,
  styleUrl: './atl-accordion.css',
  host: {
    class: 'atl-accordion-item',
    '[attr.data-accordion-id]': 'id',
  },
})
export class AtlAccordionItem implements AccordionItem, OnInit, OnDestroy {
  /** Whether this item is expanded. Supports two-way binding. */
  readonly expanded = model(false);

  /** Whether this item is disabled. */
  // eslint-disable-next-line @angular-eslint/no-input-rename
  readonly disabledInput = input(false, { alias: 'disabled' });

  /**
   * HTML heading level wrapping the trigger button. Default `3`.
   * Match your page's heading outline so heading order stays valid.
   * Rendered as `<div role="heading" aria-level="N">` so screen
   * readers treat it as a real heading at that level.
   */
  readonly headingLevel = input<1 | 2 | 3 | 4 | 5 | 6>(3);

  /** @internal — satisfies AccordionItem / FocusableOption interface */
  get disabled(): boolean {
    return this.disabledInput();
  }

  /** @internal */
  readonly id = `atl-accordion-item-${nextId++}`;

  /** @internal */
  readonly triggerId = `${this.id}-trigger`;

  /** @internal */
  readonly panelId = `${this.id}-panel`;

  /** @internal */
  private readonly group = inject(AtlAccordionGroup);

  /** @internal */
  private readonly cdkItem = inject(CdkAccordionItem);

  /** @internal */
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);

  /** @internal */
  protected readonly isExpanded = signal(false);

  /** @internal */
  get isExpandedValue(): boolean {
    return this.isExpanded();
  }

  /** @internal */
  get isDisabled(): boolean {
    return this.disabledInput();
  }

  /** @internal */
  get ariaDisabled(): boolean | null {
    return this.disabledInput() || null;
  }

  constructor() {
    this.cdkItem.expandedChange.subscribe((expanded: boolean) => {
      this.isExpanded.set(expanded);
      this.expanded.set(expanded);
    });
  }

  ngOnInit(): void {
    this.group.register(this);
    // Sync initial expanded model
    if (this.expanded()) {
      this.cdkItem.open();
    }
  }

  ngOnDestroy(): void {
    this.group.unregister(this);
  }

  /** @internal — for FocusKeyManager */
  focus(): void {
    this.el.nativeElement.querySelector<HTMLButtonElement>('.accordion-trigger')?.focus();
  }

  /** @internal */
  protected onToggle(): void {
    if (this.disabledInput()) return;
    this.cdkItem.toggle();
  }

  /** @internal */
  protected onKeydown(event: KeyboardEvent): void {
    this.group.handleKeydown(event, this);
  }
}
