// libs/vue/src/lib/checkbox/atl-checkbox.vue
<script setup lang="ts">
import { ref, watch, onMounted, computed, useId } from 'vue';
import '@atelier-ui/styles/checkbox/atl-checkbox.css';
import type { AtlErrorItem } from '../spec';
import { errorMessage } from '../error-message';

defineOptions({ name: 'AtlCheckbox' });

interface AtlCheckboxProps {
  /** The checked state. Two-way bound via `v-model:checked` (emits `update:checked`). */
  checked?: boolean;
  /** Tri-state indeterminate mode (e.g. "select all"), shown as a dash. Applied to the native input's DOM property. */
  indeterminate?: boolean;
  /** Whether the checkbox has validation errors; sets `aria-invalid`. */
  invalid?: boolean;
  /** Validation error messages shown below the control and linked to it via `aria-describedby`. */
  errors?: ReadonlyArray<string | AtlErrorItem>;
  /** Whether the checkbox is disabled. */
  disabled?: boolean;
  /** Whether the checkbox is required. */
  required?: boolean;
  /** The input's `name` attribute. */
  name?: string;
  /** Explicit id for the native input. Wins over the auto-generated id, so an external `<label for>` can point at it. */
  id?: string;
}

const props = withDefaults(defineProps<AtlCheckboxProps>(), {
  checked: false,
  indeterminate: false,
  invalid: false,
  errors: () => [],
  disabled: false,
  required: false,
  name: '',
  id: '',
});

const emit = defineEmits<{
  'update:checked': [value: boolean];
}>();

const inputRef = ref<HTMLInputElement | null>(null);

const errorsId = useId();
// useId(), not Math.random(): a random id inside a computed() re-rolls on every
// re-evaluation and differs between server and client render, breaking SSR
// hydration. useId() is stable per component instance.
const generatedId = useId();

const inputId = computed(() => props.id || `checkbox-${generatedId}`);

watch(
  () => props.indeterminate,
  (val) => {
    if (inputRef.value) inputRef.value.indeterminate = val;
  },
);

onMounted(() => {
  if (inputRef.value) inputRef.value.indeterminate = props.indeterminate;
});

function onChange(event: Event) {
  const target = event.target as HTMLInputElement;
  emit('update:checked', target.checked);
}
</script>

<template>
  <div
    class="atl-checkbox"
    :class="{ 'is-invalid': invalid, 'is-disabled': disabled }"
  >
    <label :for="inputId" class="checkbox-label">
      <input
        :id="inputId"
        ref="inputRef"
        type="checkbox"
        :checked="checked"
        :disabled="disabled"
        :required="required"
        :name="name"
        :aria-invalid="invalid || undefined"
        :aria-describedby="errors.length > 0 ? errorsId : undefined"
        @change="onChange"
      />
      <slot />
    </label>
    <div v-if="errors.length" :id="errorsId" class="errors" aria-live="polite">
      <p v-for="(error, i) in errors" :key="i" class="error-message">
        {{ errorMessage(error) }}
      </p>
    </div>
  </div>
</template>

// libs/angular/src/lib/checkbox/atl-checkbox.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  ElementRef,
  input,
  model,
  viewChild,
} from '@angular/core';
import type { FormCheckboxControl } from '@angular/forms/signals';
import { type ValidationError, type WithOptionalFieldTree } from '@angular/forms/signals';

let nextId = 0;

/**
 * Accessible checkbox component for use with Angular Signal Forms.
 *
 * Usage:
 * ```html
 * <atl-checkbox [(checked)]="accepted">I agree to the terms</atl-checkbox>
 * <atl-checkbox [formField]="form.accepted">Accept</atl-checkbox>
 * ```
 */
@Component({
  selector: 'atl-checkbox',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [attr.for]="inputId">
      <input
        #nativeInput
        type="checkbox"
        [id]="inputId"
        [checked]="checked()"
        (change)="onChange($event)"
        (blur)="touched.set(true)"
        [disabled]="disabled()"
        [attr.name]="name() || null"
        [attr.aria-invalid]="invalid() || null"
        [attr.aria-required]="required() || null"
        [attr.aria-describedby]="showErrors() ? errorId : null"
      />
      <ng-content />
    </label>
    @if (showErrors()) {
      <div class="errors" [id]="errorId" aria-live="polite">
        @for (error of errors(); track error.kind) {
          <p class="error-message">{{ error.message }}</p>
        }
      </div>
    }
  `,
  styleUrl: './atl-checkbox.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class AtlCheckbox implements FormCheckboxControl {
  /** The checked state. Bound by [formField] directive. Supports [(checked)] two-way binding. */
  readonly checked = model(false);

  /** Whether the user has interacted with the input. Bound by [formField] directive. */
  readonly touched = model(false);

  /** Tri-state indeterminate mode (e.g. "select all"). Set via DOM property. */
  readonly indeterminate = input(false);

  /** Whether the checkbox is disabled. Bound by [formField] directive. */
  readonly disabled = input(false);

  /** Whether the checkbox has validation errors. Bound by [formField] directive. */
  readonly invalid = input(false);

  /** Whether the checkbox is required. Bound by [formField] directive. */
  readonly required = input(false);

  /** The input's name attribute. Bound by [formField] directive. */
  readonly name = input('');

  /** Validation errors from the form system. Bound by [formField] directive. */
  readonly errors = input<readonly WithOptionalFieldTree<ValidationError>[]>([]);

  /** @internal */
  protected readonly inputId = `atl-checkbox-${nextId++}`;

  /** @internal */
  protected readonly errorId = `atl-checkbox-errors-${nextId++}`;

  /** @internal */
  private readonly nativeInput = viewChild<ElementRef<HTMLInputElement>>('nativeInput');

  /** @internal */
  protected readonly showErrors = computed(
    () => this.touched() && this.invalid() && this.errors().length > 0
  );

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.checked()) classes.push('is-checked');
    if (this.disabled()) classes.push('is-disabled');
    if (this.invalid()) classes.push('is-invalid');
    if (this.touched()) classes.push('is-touched');
    return classes.join(' ');
  });

  constructor() {
    effect(() => {
      const el = this.nativeInput()?.nativeElement;
      if (el) {
        el.indeterminate = this.indeterminate();
      }
    });
  }

  /** @internal */
  protected onChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.checked.set(target.checked);
  }
}
