// libs/vue/src/lib/textarea/llm-textarea.vue
<script setup lang="ts">
import { ref, watch, onMounted, computed, nextTick } from 'vue';
import './llm-textarea.css';

defineOptions({ name: 'LlmTextarea' });

interface LlmTextareaProps {
  value?: string;
  rows?: number;
  placeholder?: string;
  invalid?: boolean;
  errors?: string[];
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  label?: string;
  autoResize?: boolean;
  name?: string;
  id?: string;
}

const props = withDefaults(defineProps<LlmTextareaProps>(), {
  value: '',
  rows: 3,
  placeholder: '',
  invalid: false,
  errors: () => [],
  disabled: false,
  readonly: false,
  required: false,
  label: '',
  autoResize: false,
  name: '',
  id: '',
});

const emit = defineEmits<{
  'update:value': [value: string];
}>();

const textareaRef = ref<HTMLTextAreaElement | null>(null);

const textareaId = computed(() => props.id || (props.label ? `textarea-${Math.random().toString(36).slice(2)}` : undefined));

function adjustHeight() {
  if (props.autoResize && textareaRef.value) {
    textareaRef.value.style.height = 'auto';
    textareaRef.value.style.height = `${textareaRef.value.scrollHeight}px`;
  }
}

watch(() => props.value, async () => {
  await nextTick();
  adjustHeight();
});

onMounted(() => adjustHeight());

function onInput(event: Event) {
  emit('update:value', (event.target as HTMLTextAreaElement).value);
  adjustHeight();
}
</script>

<template>
  <div class="llm-textarea" :class="{ 'is-invalid': invalid, 'is-disabled': disabled }">
    <label v-if="label" :for="textareaId" class="textarea-label">{{ label }}</label>
    <textarea
      :id="textareaId"
      ref="textareaRef"
      :value="value"
      :rows="rows"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      :required="required"
      :name="name"
      :aria-invalid="invalid || undefined"
      @input="onInput"
    />
    <ul v-if="errors.length" class="errors" aria-live="polite">
      <li v-for="(error, i) in errors" :key="i" class="error">{{ error }}</li>
    </ul>
  </div>
</template>

// libs/llm-components-react/src/lib/textarea/llm-textarea.tsx
import { TextareaHTMLAttributes, useRef, useEffect } from 'react';
import './llm-textarea.css';

export interface LlmTextareaProps extends TextareaHTMLAttributes<HTMLTextAreaElement> {
  value?: string;
  onValueChange?: (value: string) => void;
  invalid?: boolean;
  errors?: string[];
  label?: string;
  autoResize?: boolean;
  readOnly?: boolean;
}

export function LlmTextarea({
  value,
  onChange,
  onValueChange,
  invalid = false,
  errors = [],
  disabled = false,
  readOnly = false,
  required = false,
  label,
  autoResize = false,
  rows = 3,
  className,
  id,
  ...rest
}: LlmTextareaProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const inputId =
    id || (label ? `textarea-${label.toLowerCase().replace(/\s+/g, '-')}` : undefined);
  const classes = [
    'llm-textarea',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    readOnly && 'is-readonly',
    autoResize && 'is-auto-resize',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  useEffect(() => {
    if (autoResize && textareaRef.current) {
      const el = textareaRef.current;
      el.style.height = 'auto';
      el.style.height = `${el.scrollHeight}px`;
    }
  }, [value, autoResize]);

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onChange?.(e);
    onValueChange?.(e.target.value);
    if (autoResize && textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  };

  const errorId = inputId ? `${inputId}-errors` : undefined;

  return (
    <div className={classes}>
      {label && <label htmlFor={inputId}>{label}</label>}
      <textarea
        ref={textareaRef}
        id={inputId}
        value={value}
        onChange={handleChange}
        disabled={disabled}
        readOnly={readOnly}
        required={required}
        rows={rows}
        aria-invalid={invalid || undefined}
        aria-required={required || undefined}
        aria-describedby={errors.length > 0 ? errorId : undefined}
        {...rest}
      />
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}
