// libs/vue/src/lib/badge/llm-badge.vue
<script setup lang="ts">
import { computed } from 'vue';
import './llm-badge.css';

defineOptions({ name: 'LlmBadge' });

interface LlmBadgeProps {
  variant?: 'default' | 'success' | 'warning' | 'danger' | 'info';
  size?: 'sm' | 'md';
}

const props = withDefaults(defineProps<LlmBadgeProps>(), {
  variant: 'default',
  size: 'md',
});

const classes = computed(() => [
  'llm-badge',
  `variant-${props.variant}`,
  `size-${props.size}`,
]);
</script>

<template>
  <span :class="classes" role="status">
    <slot />
  </span>
</template>

// libs/llm-components-react/src/lib/badge/llm-badge.tsx
import { HTMLAttributes, ReactNode } from 'react';
import './llm-badge.css';

export interface LlmBadgeProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: 'default' | 'success' | 'warning' | 'danger' | 'info';
  size?: 'sm' | 'md';
  children?: ReactNode;
}

export function LlmBadge({
  variant = 'default',
  size = 'md',
  children,
  className,
  ...rest
}: LlmBadgeProps) {
  const classes = ['llm-badge', `variant-${variant}`, `size-${size}`, className]
    .filter(Boolean).join(' ');
  return (
    <span className={classes} role="status" {...rest}>
      {children}
    </span>
  );
}
