// libs/vue/src/lib/input/llm-input.vue
<script setup lang="ts">
import { computed } from 'vue';
import './llm-input.css';

defineOptions({ name: 'LlmInput' });

interface LlmInputProps {
  value?: string;
  type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
  placeholder?: string;
  invalid?: boolean;
  errors?: string[];
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  label?: string;
  name?: string;
  id?: string;
}

const props = withDefaults(defineProps<LlmInputProps>(), {
  value: '',
  type: 'text',
  placeholder: '',
  invalid: false,
  errors: () => [],
  disabled: false,
  readonly: false,
  required: false,
  label: '',
  name: '',
  id: '',
});

const emit = defineEmits<{
  'update:value': [value: string];
}>();

const inputId = computed(() => props.id || (props.label ? `input-${Math.random().toString(36).slice(2)}` : undefined));

function onInput(event: Event) {
  emit('update:value', (event.target as HTMLInputElement).value);
}
</script>

<template>
  <div class="llm-input" :class="{ 'is-invalid': invalid, 'is-disabled': disabled }">
    <label v-if="label" :for="inputId" class="input-label">{{ label }}</label>
    <input
      :id="inputId"
      :type="type"
      :value="value"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      :required="required"
      :name="name"
      :aria-invalid="invalid || undefined"
      @input="onInput"
    />
    <ul v-if="errors.length" class="errors" aria-live="polite">
      <li v-for="(error, i) in errors" :key="i" class="error">{{ error }}</li>
    </ul>
  </div>
</template>

// libs/llm-components-react/src/lib/input/llm-input.tsx
import { InputHTMLAttributes } from 'react';
import './llm-input.css';

export interface LlmInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> {
  type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
  value?: string;
  onValueChange?: (value: string) => void;
  invalid?: boolean;
  errors?: string[];
  label?: string;
  readOnly?: boolean;
}

export function LlmInput({
  type = 'text',
  value,
  onChange,
  onValueChange,
  invalid = false,
  errors = [],
  disabled = false,
  readOnly = false,
  required = false,
  label,
  className,
  id,
  ...rest
}: LlmInputProps) {
  const inputId =
    id || (label ? `input-${label.toLowerCase().replace(/\s+/g, '-')}` : undefined);
  const classes = [
    'llm-input',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    readOnly && 'is-readonly',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onChange?.(e);
    onValueChange?.(e.target.value);
  };

  const errorId = inputId ? `${inputId}-errors` : undefined;

  return (
    <div className={classes}>
      {label && <label htmlFor={inputId}>{label}</label>}
      <input
        id={inputId}
        type={type}
        value={value}
        onChange={handleChange}
        disabled={disabled}
        readOnly={readOnly}
        required={required}
        aria-invalid={invalid || undefined}
        aria-required={required || undefined}
        aria-describedby={errors.length > 0 ? errorId : undefined}
        {...rest}
      />
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}
