// libs/react/src/lib/card/atl-card.tsx
import { HTMLAttributes, ReactNode } from 'react';
import type { AtlCardSpec, AtlCardRole } from '../spec';
import '@atelier-ui/styles/card/atl-card.css';

/**
 * Properties for the AtlCard component.
 */
export interface AtlCardProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'role'>, AtlCardSpec {
  /**
   * The visual style variant of the card.
   */
  variant?: 'elevated' | 'outlined' | 'flat';
  /**
   * The padding size within the card.
   */
  padding?: 'none' | 'sm' | 'md' | 'lg';
  /**
   * Opt-in landmark role. Default is no role (plain `<div>`).
   * Pick `'article'` for self-contained content, `'region'` for a
   * perceivable area that needs a screen-reader stop (pair with
   * aria-label), or `'section'` to mirror an HTML `<section>`.
   */
  role?: AtlCardRole;
  /**
   * The content to be rendered inside the card.
   */
  children?: ReactNode;
}

/**
 * A card component for grouping related content.
 */
export function AtlCard({
  variant = 'elevated',
  padding = 'md',
  children,
  className,
  ...rest
}: AtlCardProps) {
  const classes = [
    'atl-card',
    `variant-${variant}`,
    `padding-${padding}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');
  return (
    <div className={classes} {...rest}>
      {children}
    </div>
  );
}

/**
 * The header component for an AtlCard.
 */
export function AtlCardHeader({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & {
  /**
   * The content of the card header.
   */
  children?: ReactNode;
}) {
  return (
    <div
      className={['atl-card-header', className].filter(Boolean).join(' ')}
      {...rest}
    >
      {children}
    </div>
  );
}

/**
 * The main content component for an AtlCard.
 */
export function AtlCardContent({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & {
  /**
   * The main content of the card.
   */
  children?: ReactNode;
}) {
  return (
    <div
      className={['atl-card-content', className].filter(Boolean).join(' ')}
      {...rest}
    >
      {children}
    </div>
  );
}

/**
 * The footer component for an AtlCard.
 */
export function AtlCardFooter({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement> & {
  /**
   * The content of the card footer.
   */
  children?: ReactNode;
}) {
  return (
    <div
      className={['atl-card-footer', className].filter(Boolean).join(' ')}
      {...rest}
    >
      {children}
    </div>
  );
}

// libs/vue/src/lib/card/atl-card.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@atelier-ui/styles/card/atl-card.css';

defineOptions({ name: 'AtlCard' });

interface AtlCardProps {
  /** Visual style of the card. */
  variant?: 'elevated' | 'outlined' | 'flat';
  /** Internal padding of the card. */
  padding?: 'none' | 'sm' | 'md' | 'lg';
  /**
   * Opt-in landmark role. Default is no role.
   *
   * - `'article'` — self-contained content (blog post, comment).
   * - `'region'`  — perceivable area that needs a screen-reader stop;
   *                 pair with `aria-label`.
   * - `'section'` — mirrors an HTML `<section>`.
   *
   * Most cards group content visually and shouldn't add a landmark.
   * Leave unset by default.
   */
  role?: 'article' | 'region' | 'section';
}

const props = withDefaults(defineProps<AtlCardProps>(), {
  variant: 'elevated',
  padding: 'md',
  role: undefined,
});

const classes = computed(() => [
  'atl-card',
  `variant-${props.variant}`,
  `padding-${props.padding}`,
]);
</script>

<template>
  <div :class="classes" :role="role">
    <slot />
  </div>
</template>
