// libs/vue/src/lib/skeleton/atl-skeleton.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@atelier-ui/styles/skeleton/atl-skeleton.css';

defineOptions({ name: 'AtlSkeleton' });

interface AtlSkeletonProps {
  /** Shape variant of the skeleton placeholder. */
  variant?: 'text' | 'circular' | 'rectangular';
  /** CSS width of the skeleton. */
  width?: string;
  /** CSS height. When unset, a sensible default is chosen per variant. */
  height?: string;
  /** Whether the shimmer animation is active. */
  animated?: boolean;
}

const props = withDefaults(defineProps<AtlSkeletonProps>(), {
  variant: 'text',
  width: '100%',
  height: undefined,
  animated: true,
});

function computeHeight(
  variant: string,
  width: string,
  height?: string,
): string {
  if (height) return height;
  switch (variant) {
    case 'text':
      return '1em';
    case 'circular':
      return width;
    case 'rectangular':
      return '100px';
    default:
      return '1em';
  }
}

const classes = computed(() =>
  [
    'atl-skeleton',
    `variant-${props.variant}`,
    props.animated && 'is-animated',
  ].filter(Boolean),
);

const inlineStyle = computed(() => ({
  width: props.width,
  height: computeHeight(props.variant, props.width, props.height),
}));
</script>

<template>
  <div :class="classes" :style="inlineStyle" aria-hidden="true" />
</template>

// libs/angular/src/lib/skeleton/atl-skeleton.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

/**
 * Loading placeholder that mimics the shape of content while it loads.
 *
 * Usage:
 * ```html
 * <atl-skeleton />
 * <atl-skeleton variant="circular" width="40px" />
 * <atl-skeleton variant="rectangular" height="200px" />
 * ```
 */
@Component({
  selector: 'atl-skeleton',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: ``,
  styleUrl: './atl-skeleton.css',
  host: {
    '[class]': 'hostClasses()',
    '[style.width]': 'width()',
    '[style.height]': 'computedHeight()',
    'aria-hidden': 'true',
  },
})
export class AtlSkeleton {
  /** Shape variant of the skeleton placeholder. */
  readonly variant = input<'text' | 'circular' | 'rectangular'>('text');

  /** CSS width of the skeleton. */
  readonly width = input('100%');

  /** CSS height — when empty, a sensible default is chosen per variant. */
  readonly height = input('');

  /** Whether the shimmer animation is active. */
  readonly animated = input(true);

  protected readonly computedHeight = computed(() => {
    if (this.height()) return this.height();
    switch (this.variant()) {
      case 'text':
        return '1em';
      case 'circular':
        return this.width();
      case 'rectangular':
        return '100px';
    }
  });

  protected readonly hostClasses = computed(() => {
    const classes = [`variant-${this.variant()}`];
    if (this.animated()) classes.push('is-animated');
    return classes.join(' ');
  });
}
