// libs/vue/src/lib/toggle/llm-toggle.vue
<script setup lang="ts">
import { computed } from 'vue';
import './llm-toggle.css';

defineOptions({ name: 'LlmToggle' });

interface LlmToggleProps {
  checked?: boolean;
  invalid?: boolean;
  errors?: string[];
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  name?: string;
  id?: string;
}

const props = withDefaults(defineProps<LlmToggleProps>(), {
  checked: false,
  invalid: false,
  errors: () => [],
  disabled: false,
  readonly: false,
  required: false,
  name: '',
  id: '',
});

const emit = defineEmits<{
  'update:checked': [value: boolean];
}>();

const inputId = computed(() => props.id || `toggle-${Math.random().toString(36).slice(2)}`);

function onChange(event: Event) {
  if (props.readonly) return;
  emit('update:checked', (event.target as HTMLInputElement).checked);
}
</script>

<template>
  <div class="llm-toggle" :class="{ 'is-invalid': invalid, 'is-disabled': disabled }">
    <label :for="inputId" class="toggle-label">
      <input
        :id="inputId"
        type="checkbox"
        role="switch"
        :checked="checked"
        :disabled="disabled"
        :required="required"
        :name="name"
        :aria-invalid="invalid || undefined"
        :aria-checked="checked"
        @change="onChange"
      />
      <span class="track">
        <span class="thumb" />
      </span>
      <slot />
    </label>
    <ul v-if="errors.length" class="errors" aria-live="polite">
      <li v-for="(error, i) in errors" :key="i" class="error">{{ error }}</li>
    </ul>
  </div>
</template>

// libs/react/src/lib/toggle/llm-toggle.tsx
import { InputHTMLAttributes, ReactNode, useId } from 'react';
import type { LlmToggleSpec } from '../spec';
import './llm-toggle.css';

/**
 * Properties for the LlmToggle component.
 */
export interface LlmToggleProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'checked' | 'onChange' | 'readOnly' | 'value'>,
    LlmToggleSpec {
  /**
   * Whether the toggle is read-only.
   */
  readOnly?: boolean;
  /**
   * Callback fired when the checked state changes.
   */
  onCheckedChange?: (checked: boolean) => void;
  /**
   * List of error messages to display.
   */
  errors?: string[];
  /**
   * Optional content to display alongside the toggle.
   */
  children?: ReactNode;
}

/**
 * A toggle switch component for binary choices, supporting validation and custom labels.
 */
export function LlmToggle({
  checked = false,
  onCheckedChange,
  invalid = false,
  errors = [],
  disabled = false,
  readOnly: reactReadOnly,
  readonly: specReadOnly,
  required = false,
  children,
  className,
  id,
  name,
  ...rest
}: LlmToggleProps) {
  const readOnly = reactReadOnly ?? specReadOnly ?? false;
  const generatedId = useId();
  const inputId = id || `toggle-${generatedId}`;
  const errorId = `${inputId}-errors`;

  const classes = [
    'llm-toggle',
    checked && 'is-checked',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes}>
      <label htmlFor={inputId}>
        <input
          type="checkbox"
          role="switch"
          id={inputId}
          checked={checked}
          onChange={(e) => onCheckedChange?.(e.target.checked)}
          disabled={disabled}
          readOnly={readOnly}
          required={required}
          aria-checked={checked}
          aria-invalid={invalid || undefined}
          aria-required={required || undefined}
          aria-describedby={errors.length > 0 ? errorId : undefined}
          name={name}
          {...rest}
        />
        <span className="track" aria-hidden="true">
          <span className="thumb" />
        </span>
        {children}
      </label>
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}
