// libs/llm-components-react/src/lib/avatar/llm-avatar.tsx
import { HTMLAttributes, ReactNode, Children, useState, useEffect } from 'react';
import type {
  LlmAvatarSpec,
  LlmAvatarGroupSpec,
} from '@atelier-ui/spec';
import './llm-avatar.css';

/**
 * Properties for the LlmAvatar component.
 */
export interface LlmAvatarProps
  extends HTMLAttributes<HTMLDivElement>,
    LlmAvatarSpec {
  /**
   * The URL of the image to display.
   */
  src?: string;
  /**
   * Accessible text for the avatar image.
   */
  alt?: string;
  /**
   * The name of the person/entity, used for initials if no image is provided.
   */
  name?: string;
  /**
   * The size of the avatar.
   */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /**
   * The shape of the avatar.
   */
  shape?: 'circle' | 'square';
  /**
   * The status indicator to display on the avatar.
   */
  status?: 'online' | 'offline' | 'away' | 'busy' | '';
}

function getInitials(name: string): string {
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0].toUpperCase())
    .join('');
}

/**
 * An avatar component for displaying user profile pictures or initials.
 */
export function LlmAvatar({
  src = '',
  alt = '',
  name = '',
  size = 'md',
  shape = 'circle',
  status = '',
  className,
  ...rest
}: LlmAvatarProps) {
  const [imgError, setImgError] = useState(false);

  // Reset imgError when src changes
  useEffect(() => {
    setImgError(false);
  }, [src]);

  const classes = ['llm-avatar', `size-${size}`, `shape-${shape}`, className]
    .filter(Boolean).join(' ');

  const initials = name ? getInitials(name) : '';
  const ariaLabel = alt || name || 'Avatar';

  return (
    <div className={classes} aria-label={ariaLabel} role="img" {...rest}>
      {src && !imgError ? (
        <img src={src} alt={alt || name} onError={() => setImgError(true)} />
      ) : initials ? (
        <span className="initials" aria-hidden="true">{initials}</span>
      ) : (
        <svg className="icon" aria-hidden="true" viewBox="0 0 24 24" fill="currentColor">
          <path d="M12 12c2.761 0 5-2.239 5-5s-2.239-5-5-5-5 2.239-5 5 2.239 5 5 5zm0 2c-3.314 0-10 1.343-10 4v2h20v-2c0-2.657-6.686-4-10-4z" />
        </svg>
      )}
      {status && <span className={`status-dot status-${status}`} aria-hidden="true" />}
    </div>
  );
}

/**
 * Properties for the LlmAvatarGroup component.
 */
export interface LlmAvatarGroupProps
  extends HTMLAttributes<HTMLDivElement>,
    LlmAvatarGroupSpec {
  /**
   * The maximum number of avatars to show before displaying an overflow badge.
   */
  max?: number;
  /**
   * The size of the avatars in the group.
   */
  size?: LlmAvatarProps['size'];
  /**
   * The avatars to be rendered in the group.
   */
  children?: ReactNode;
}

/**
 * A container for grouping multiple avatars.
 */
export function LlmAvatarGroup({
  max = 5,
  size = 'md',
  children,
  className,
  ...rest
}: LlmAvatarGroupProps) {
  const childArray = Children.toArray(children);
  const visible = childArray.slice(0, max);
  const overflow = childArray.length - max;

  const classes = ['llm-avatar-group', `size-${size}`, className].filter(Boolean).join(' ');

  return (
    <div className={classes} {...rest}>
      {visible}
      {overflow > 0 && (
        <div
          className={`overflow-badge size-${size}`}
          aria-label={`+${overflow} more`}
        >
          +{overflow}
        </div>
      )}
    </div>
  );
}

// libs/llm-components-angular/src/lib/avatar/llm-avatar.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  contentChildren,
  effect,
  input,
  signal,
  untracked,
} from '@angular/core';

/**
 * Displays a user avatar with image, initials, or icon fallback.
 *
 * Fallback order: image → initials (from `name`) → generic icon.
 *
 * Usage:
 * ```html
 * <llm-avatar src="https://example.com/photo.jpg" name="Jane Doe" />
 * <llm-avatar name="John Smith" size="lg" status="online" />
 * <llm-avatar size="sm" shape="square" />
 * ```
 */
@Component({
  selector: 'llm-avatar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (src() && showImage()) {
      <img [src]="src()" [alt]="alt()" (error)="showImage.set(false)" />
    } @else if (initials()) {
      <span class="initials" aria-hidden="true">{{ initials() }}</span>
    } @else {
      <svg class="icon" aria-hidden="true" viewBox="0 0 24 24" fill="currentColor">
        <path d="M12 12c2.761 0 5-2.239 5-5s-2.239-5-5-5-5 2.239-5 5 2.239 5 5 5zm0 2c-3.314 0-10 1.343-10 4v2h20v-2c0-2.657-6.686-4-10-4z" />
      </svg>
    }
    @if (status()) {
      <span [class]="'status-dot status-' + status()" aria-hidden="true"></span>
    }
  `,
  styleUrl: './llm-avatar.css',
  host: {
    '[class]': 'hostClasses()',
    role: 'img',
    '[attr.aria-label]': 'ariaLabel()',
  },
})
export class LlmAvatar {
  /** Image URL. Falls back to initials or icon if empty or fails to load. */
  readonly src = input('');

  /** Alt text for the image (also used as aria-label). */
  readonly alt = input('');

  /** Full name used to generate initials fallback and default aria-label. */
  readonly name = input('');

  /** Size of the avatar. */
  readonly size = input<'xs' | 'sm' | 'md' | 'lg' | 'xl'>('md');

  /** Shape of the avatar. */
  readonly shape = input<'circle' | 'square'>('circle');

  /** Presence status indicator dot. Empty string hides the dot. */
  readonly status = input<'online' | 'offline' | 'away' | 'busy' | ''>('');

  /** @internal — reset to true whenever src changes */
  protected readonly showImage = signal(true);

  /** @internal */
  protected readonly initials = computed(() => {
    const name = this.name();
    if (!name) return '';
    return name
      .split(' ')
      .filter(Boolean)
      .slice(0, 2)
      .map((w) => w[0].toUpperCase())
      .join('');
  });

  /** @internal */
  protected readonly ariaLabel = computed(
    () => this.alt() || this.name() || 'Avatar'
  );

  /** @internal */
  protected readonly hostClasses = computed(
    () => `size-${this.size()} shape-${this.shape()}`
  );

  constructor() {
    effect(() => {
      this.src(); // track src changes
      untracked(() => this.showImage.set(true));
    });
  }
}

/**
 * Groups multiple avatars with overlap and an overflow count badge.
 *
 * Usage:
 * ```html
 * <llm-avatar-group [max]="3" size="md">
 *   <llm-avatar name="Alice" />
 *   <llm-avatar name="Bob" />
 *   <llm-avatar name="Charlie" />
 *   <llm-avatar name="Dave" />
 * </llm-avatar-group>
 * ```
 */
@Component({
  selector: 'llm-avatar-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-content />
    @if (overflowCount() > 0) {
      <span [class]="'overflow-badge size-' + size()">+{{ overflowCount() }}</span>
    }
  `,
  styleUrl: './llm-avatar.css',
  host: {
    class: 'group',
    '[class]': '"group size-" + size()',
  },
})
export class LlmAvatarGroup {
  /** Maximum visible avatars before showing an overflow count. */
  readonly max = input(5);

  /** Size applied to the overflow badge (match the size used on child avatars). */
  readonly size = input<'xs' | 'sm' | 'md' | 'lg' | 'xl'>('md');

  private readonly avatarEls = contentChildren(LlmAvatar, { read: ElementRef });

  protected readonly overflowCount = computed(() =>
    Math.max(0, this.avatarEls().length - this.max())
  );

  constructor() {
    effect(() => {
      const max = this.max();
      this.avatarEls().forEach((el, i) => {
        (el.nativeElement as HTMLElement).style.display = i >= max ? 'none' : '';
      });
    });
  }
}
