// libs/vue/src/lib/radio-group/atl-radio-group.vue
<script lang="ts">
import type { InjectionKey } from 'vue';

export interface AtlRadioGroupContext {
  value: string;
  name: string;
  disabled: boolean;
  readonly: boolean;
  invalid: boolean;
  onSelect: (value: string) => void;
}

export const AtlRadioGroupKey: InjectionKey<AtlRadioGroupContext> =
  Symbol('AtlRadioGroup');

export interface AtlRadioGroupProps {
  /** The selected radio value. Two-way bound via `v-model:value` (emits `update:value`). */
  value?: string;
  /** Shared `name` attribute applied to all child radio inputs. */
  name?: string;
  /** Whether the whole group is disabled. */
  disabled?: boolean;
  /** Whether the selection can be read but not changed. Enforced by the group, since HTML ignores `readonly` on a radio input. */
  readonly?: boolean;
  /** Whether the group has validation errors; sets `aria-invalid`. */
  invalid?: boolean;
  /** Whether the group is required; sets `aria-required`. */
  required?: boolean;
  /** Validation error messages shown below the group. */
  errors?: string[];
}
</script>

<script setup lang="ts">
import { computed, provide, ref } from 'vue';
import '@atelier-ui/styles/radio-group/atl-radio-group.css';

defineOptions({ name: 'AtlRadioGroup' });

const props = withDefaults(defineProps<AtlRadioGroupProps>(), {
  value: '',
  name: '',
  disabled: false,
  readonly: false,
  invalid: false,
  required: false,
  errors: () => [],
});

const emit = defineEmits<{
  'update:value': [value: string];
}>();

provide(AtlRadioGroupKey, {
  get value() {
    return props.value ?? '';
  },
  get name() {
    return props.name ?? '';
  },
  get disabled() {
    return props.disabled ?? false;
  },
  get readonly() {
    return props.readonly ?? false;
  },
  get invalid() {
    return props.invalid ?? false;
  },
  onSelect(v: string) {
    if (!props.disabled && !props.readonly) {
      emit('update:value', v);
    }
  },
});

const classes = computed(() => [
  'atl-radio-group',
  props.invalid && 'is-invalid',
  props.disabled && 'is-disabled',
  props.readonly && 'is-readonly',
]);

const groupRef = ref<HTMLDivElement | null>(null);

// Roving arrow-key navigation per the WAI-ARIA radiogroup pattern: Arrow
// Down/Right move to the next enabled radio, Up/Left to the previous, both
// wrapping, and the navigated radio is selected and focused.
function onKeydown(event: KeyboardEvent): void {
  if (props.disabled || props.readonly) return;
  const forward = event.key === 'ArrowDown' || event.key === 'ArrowRight';
  const backward = event.key === 'ArrowUp' || event.key === 'ArrowLeft';
  if (!forward && !backward) return;
  const radios = Array.from(
    groupRef.value?.querySelectorAll<HTMLInputElement>('input[type="radio"]') ??
      [],
  ).filter((radio) => !radio.disabled);
  if (radios.length === 0) return;
  event.preventDefault();
  const currentIdx = radios.findIndex((radio) => radio.value === props.value);
  const start = currentIdx === -1 ? (forward ? -1 : 0) : currentIdx;
  const nextIdx = (start + (forward ? 1 : -1) + radios.length) % radios.length;
  const target = radios[nextIdx];
  target.focus();
  emit('update:value', target.value);
}
</script>

<template>
  <!-- role="radiogroup" is a composite-widget container, not itself a tab
  stop: this is the ARIA APG roving-tabindex pattern — @keydown here is
  event-delegation to move focus among the native <input type="radio">
  children, which are natively focusable/operable on their own. The
  container deliberately stays out of the tab sequence. -->
  <!-- eslint-disable-next-line vuejs-accessibility/interactive-supports-focus -->
  <div
    ref="groupRef"
    :class="classes"
    role="radiogroup"
    :aria-invalid="invalid || undefined"
    :aria-required="required || undefined"
    @keydown="onKeydown"
  >
    <slot />
    <div v-if="errors.length > 0" class="errors" role="alert">
      <p v-for="(error, index) in errors" :key="index" class="error-message">
        {{ error }}
      </p>
    </div>
  </div>
</template>

// libs/angular/src/lib/radio-group/atl-radio-group.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
  signal,
} from '@angular/core';
import { FocusKeyManager } from '@angular/cdk/a11y';
import type { FormValueControl } from '@angular/forms/signals';
import { type ValidationError, type WithOptionalFieldTree } from '@angular/forms/signals';
import { ATL_RADIO_GROUP, type AtlRadioGroupContext, type RadioItem } from './atl-radio-group.token';

let nextId = 0;

/**
 * Container for a group of radio buttons. Manages keyboard navigation, shared name,
 * and Signal Forms integration.
 *
 * Usage:
 * ```html
 * <atl-radio-group [(value)]="size" name="size">
 *   <atl-radio radioValue="sm">Small</atl-radio>
 *   <atl-radio radioValue="md">Medium</atl-radio>
 *   <atl-radio radioValue="lg">Large</atl-radio>
 * </atl-radio-group>
 *
 * <!-- With Signal Forms -->
 * <atl-radio-group [formField]="form.size">
 *   <atl-radio radioValue="sm">Small</atl-radio>
 * </atl-radio-group>
 * ```
 */
@Component({
  selector: 'atl-radio-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-content />
    @if (showErrors()) {
      <div class="errors" [id]="errorId" aria-live="polite">
        @for (error of errors(); track error.kind) {
          <p class="error-message">{{ error.message }}</p>
        }
      </div>
    }
  `,
  styleUrl: './atl-radio-group.css',
  host: {
    role: 'radiogroup',
    '[class]': 'hostClasses()',
    '[attr.aria-invalid]': 'invalid() || null',
    '[attr.aria-required]': 'required() || null',
    '[attr.aria-describedby]': 'showErrors() ? errorId : null',
    '(keydown)': 'onKeydown($event)',
  },
  providers: [{ provide: ATL_RADIO_GROUP, useExisting: AtlRadioGroup }],
})
export class AtlRadioGroup implements FormValueControl<string>, AtlRadioGroupContext {
  /** The selected value. Bound by [formField] directive. Supports [(value)] two-way binding. */
  readonly value = model('');

  /** Whether the user has interacted. Bound by [formField] directive. */
  readonly touched = model(false);

  /** Whether the group is disabled. Bound by [formField] directive. */
  readonly disabled = input(false);

  /**
   * Whether the selection can be read but not changed. Enforced by the guards in
   * `select()` and `onKeydown()`: HTML ignores `readonly` on a radio input, so the
   * group has to block the change itself. See ADR-0045.
   */
  readonly readonly = input(false);

  /** Whether the group has validation errors. Bound by [formField] directive. */
  readonly invalid = input(false);

  /** Whether the group is required. Bound by [formField] directive. */
  readonly required = input(false);

  /** Shared name attribute propagated to all child radio inputs. Bound by [formField] directive. */
  readonly name = input('');

  /** Validation errors from the form system. Bound by [formField] directive. */
  readonly errors = input<readonly WithOptionalFieldTree<ValidationError>[]>([]);

  /** @internal */
  protected readonly errorId = `atl-radio-group-errors-${nextId++}`;

  /** @internal */
  private readonly items = signal<RadioItem[]>([]);

  /** @internal */
  private keyManager: FocusKeyManager<RadioItem> | null = null;

  /** @internal */
  protected readonly showErrors = computed(
    () => this.touched() && this.invalid() && this.errors().length > 0
  );

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.disabled()) classes.push('is-disabled');
    if (this.readonly()) classes.push('is-readonly');
    if (this.invalid()) classes.push('is-invalid');
    if (this.touched()) classes.push('is-touched');
    return classes.join(' ');
  });

  /** @internal — called by AtlRadio on change */
  select(v: string): void {
    if (!this.disabled() && !this.readonly()) {
      this.value.set(v);
    }
  }

  /** @internal — called by AtlRadio on blur */
  markTouched(): void {
    this.touched.set(true);
  }

  /** @internal — called by AtlRadio on init */
  registerItem(item: RadioItem): void {
    this.items.update((list) => [...list, item]);
  }

  /** @internal — called by AtlRadio on destroy */
  unregisterItem(item: RadioItem): void {
    this.items.update((list) => list.filter((i) => i !== item));
  }

  /** @internal */
  protected onKeydown(event: KeyboardEvent): void {
    if (this.disabled() || this.readonly()) return;

    if (!this.keyManager) {
      this.keyManager = new FocusKeyManager(this.items())
        .withHorizontalOrientation('ltr')
        .withVerticalOrientation()
        .withWrap();
    }

    const currentIdx = this.items().findIndex((i) => i.radioValue() === this.value());
    this.keyManager.setActiveItem(currentIdx);
    this.keyManager.onKeydown(event);

    const activeIdx = this.keyManager.activeItemIndex;
    if (activeIdx !== null && activeIdx !== -1 && activeIdx !== currentIdx) {
      const target = this.items()[activeIdx];
      this.value.set(target.radioValue());
      this.touched.set(true);
    }
  }
}
