// libs/angular/src/lib/code-block/atl-code-block.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  signal,
} from '@angular/core';

/**
 * Displays a block of code with an optional header, language label, and copy button.
 * Designed for rendering LLM-generated code output, inline snippets, and API examples.
 *
 * Usage:
 * ```html
 * <atl-code-block code="const x = 1;" language="typescript" />
 * <atl-code-block [code]="generatedCode" filename="app.component.ts" [showLineNumbers]="true" />
 * ```
 */
@Component({
  selector: 'atl-code-block',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="code-block-header">
      <span class="code-block-label">{{ displayLabel() }}</span>
      @if (copyable()) {
        <button
          class="code-block-copy"
          type="button"
          [attr.aria-label]="copied() ? 'Copied' : 'Copy code'"
          (click)="copy()"
        >
          @if (copied()) {
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <polyline points="20 6 9 17 4 12" />
            </svg>
            Copied
          } @else {
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
            </svg>
            Copy
          }
        </button>
      }
    </div>
    <div class="code-block-body">
      <pre class="code-block-pre"><code>@if (showLineNumbers()) {
          @for (line of lines(); track $index) {
            <span class="code-line">
              <span class="code-line-number">{{ $index + 1 }}</span>
              <span class="code-line-text">{{ line }}</span>
            </span>
          }
        } @else {
          {{ code() }}
        }</code></pre>
    </div>
  `,
  styleUrl: './atl-code-block.css',
  host: {
    '[class]': '"atl-code-block"',
  },
})
export class AtlCodeBlock {
  /** The code string to display. */
  readonly code = input<string>('');

  /** Language label shown in the header. Ignored if filename is set. */
  readonly language = input<string>('text');

  /** Optional filename shown in the header instead of the language label. */
  readonly filename = input<string>('');

  /** Whether to show a copy-to-clipboard button. */
  readonly copyable = input<boolean>(true);

  /** Whether to display line numbers alongside the code. */
  readonly showLineNumbers = input<boolean>(false);

  protected readonly copied = signal(false);

  protected readonly displayLabel = computed(() => this.filename() || this.language());

  protected readonly lines = computed(() => this.code().split('\n'));

  protected copy(): void {
    void navigator.clipboard.writeText(this.code()).then(() => {
      this.copied.set(true);
      setTimeout(() => this.copied.set(false), 1800);
    });
  }
}

// libs/vue/src/lib/code-block/atl-code-block.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import './atl-code-block.css';

defineOptions({ name: 'AtlCodeBlock' });

interface AtlCodeBlockProps {
  /** The code string to display. */
  code: string;
  /** Language label shown in the header. Ignored if filename is set. */
  language?: string;
  /** Optional filename shown in the header instead of the language label. */
  filename?: string;
  /** Whether to show a copy-to-clipboard button. */
  copyable?: boolean;
  /** Whether to display line numbers alongside the code. */
  showLineNumbers?: boolean;
}

const props = withDefaults(defineProps<AtlCodeBlockProps>(), {
  language: 'text',
  filename: '',
  copyable: true,
  showLineNumbers: false,
});

const copied = ref(false);

const displayLabel = computed(() => props.filename || props.language);
const lines = computed(() => props.code.split('\n'));

function copy() {
  void navigator.clipboard.writeText(props.code).then(() => {
    copied.value = true;
    setTimeout(() => { copied.value = false; }, 1800);
  });
}
</script>

<template>
  <div class="atl-code-block">
    <div class="code-block-header">
      <span class="code-block-label">{{ displayLabel }}</span>
      <button
        v-if="copyable"
        class="code-block-copy"
        type="button"
        :aria-label="copied ? 'Copied' : 'Copy code'"
        @click="copy"
      >
        <template v-if="copied">
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <polyline points="20 6 9 17 4 12" />
          </svg>
          Copied
        </template>
        <template v-else>
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
          </svg>
          Copy
        </template>
      </button>
    </div>
    <div class="code-block-body">
      <pre class="code-block-pre"><code><template v-if="showLineNumbers"><span v-for="(line, i) in lines" :key="i" class="code-line"><span class="code-line-number">{{ i + 1 }}</span><span class="code-line-text">{{ line }}</span></span></template><template v-else>{{ code }}</template></code></pre>
    </div>
  </div>
</template>
