// libs/react/src/lib/badge/atl-badge.tsx
import { HTMLAttributes, ReactNode } from 'react';
import type { AtlBadgeSpec, AtlIconName } from '../spec';
import '@atelier-ui/styles/badge/atl-badge.css';
import { AtlIcon } from '../icon/atl-icon';

/** Which AtlIcon each variant carries. Names, not glyphs: a glyph in a string map
 * was the fifth way this library drew an icon, and the one check:icon-duplication
 * missed (ADR-0050). */
const VARIANT_ICON_NAMES: Partial<Record<AtlBadgeVariant, AtlIconName>> = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
};

type AtlBadgeVariant = 'default' | 'success' | 'warning' | 'danger' | 'info';

/**
 * Properties for the AtlBadge component.
 */
export interface AtlBadgeProps
  extends HTMLAttributes<HTMLSpanElement>, AtlBadgeSpec {
  /**
   * The visual style variant of the badge.
   */
  variant?: AtlBadgeVariant;
  /**
   * The size of the badge.
   */
  size?: 'sm' | 'md';
  /**
   * The content to be rendered inside the badge.
   */
  children?: ReactNode;
}

/**
 * A badge component for displaying small amounts of information or status.
 */
export function AtlBadge({
  variant = 'default',
  size = 'md',
  children,
  className,
  ...rest
}: AtlBadgeProps) {
  const classes = ['atl-badge', `variant-${variant}`, `size-${size}`, className]
    .filter(Boolean)
    .join(' ');
  const iconName = VARIANT_ICON_NAMES[variant];
  return (
    <span className={classes} role="status" {...rest}>
      {iconName && (
        <AtlIcon className="variant-icon" name={iconName} size="sm" />
      )}
      {children}
    </span>
  );
}

// libs/vue/src/lib/badge/atl-badge.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@atelier-ui/styles/badge/atl-badge.css';
import type { AtlIconName } from '../spec';
import AtlIcon from '../icon/atl-icon.vue';

defineOptions({ name: 'AtlBadge' });

type AtlBadgeVariant = 'default' | 'success' | 'warning' | 'danger' | 'info';

interface AtlBadgeProps {
  variant?: AtlBadgeVariant;
  size?: 'sm' | 'md';
}

// Which AtlIcon each variant carries. Names, not glyphs: a glyph in a string map
// was the fifth way this library drew an icon, and the one check:icon-duplication
// missed (ADR-0050).
const VARIANT_ICON_NAMES: Partial<Record<AtlBadgeVariant, AtlIconName>> = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
};

const props = withDefaults(defineProps<AtlBadgeProps>(), {
  variant: 'default',
  size: 'md',
});

const classes = computed(() => [
  'atl-badge',
  `variant-${props.variant}`,
  `size-${props.size}`,
]);

const variantIconName = computed(() => VARIANT_ICON_NAMES[props.variant]);
</script>

<template>
  <span :class="classes" role="status">
    <AtlIcon
      v-if="variantIconName"
      class="variant-icon"
      :name="variantIconName"
      size="sm"
    />
    <slot />
  </span>
</template>
