// libs/angular/src/lib/badge/atl-badge.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import type { AtlIconName, AtlBadgeVariant } from '../spec';
import { AtlIcon } from '../icon/atl-icon';

/**
 * Inline status badge for labeling items with semantic color variants.
 *
 * Usage:
 * ```html
 * <atl-badge variant="success">Active</atl-badge>
 * <atl-badge variant="danger" size="sm">Error</atl-badge>
 * <atl-badge variant="warning">Pending</atl-badge>
 * ```
 */
// Which AtlIcon each variant carries. Names, not glyphs: a glyph in a string map
// was the fifth way this library drew an icon, and the one check:icon-duplication
// missed (ADR-0050).
const VARIANT_ICON_NAMES: Partial<Record<AtlBadgeVariant, AtlIconName>> = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
};

@Component({
  selector: 'atl-badge',
  standalone: true,
  imports: [AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (variantIcon(); as icon) {
      <atl-icon class="variant-icon" [name]="icon" size="sm" />
    }
    <ng-content />
  `,
  styleUrl: './atl-badge.css',
  host: {
    '[class]': 'hostClasses()',
    role: 'status',
  },
})
export class AtlBadge {
  /** Semantic color variant of the badge. */
  readonly variant = input<
    'default' | 'success' | 'warning' | 'danger' | 'info'
  >('default');

  /** Size of the badge. */
  readonly size = input<'sm' | 'md'>('md');

  protected readonly hostClasses = computed(
    () => `variant-${this.variant()} size-${this.size()}`,
  );

  protected readonly variantIcon = computed(
    () => VARIANT_ICON_NAMES[this.variant()],
  );
}

// libs/vue/src/lib/badge/atl-badge.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@atelier-ui/styles/badge/atl-badge.css';
import type { AtlIconName } from '../spec';
import AtlIcon from '../icon/atl-icon.vue';

defineOptions({ name: 'AtlBadge' });

type AtlBadgeVariant = 'default' | 'success' | 'warning' | 'danger' | 'info';

interface AtlBadgeProps {
  /** Semantic color variant of the badge. */
  variant?: AtlBadgeVariant;
  /** Size of the badge. */
  size?: 'sm' | 'md';
}

// Which AtlIcon each variant carries. Names, not glyphs: a glyph in a string map
// was the fifth way this library drew an icon, and the one check:icon-duplication
// missed (ADR-0050).
const VARIANT_ICON_NAMES: Partial<Record<AtlBadgeVariant, AtlIconName>> = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
};

const props = withDefaults(defineProps<AtlBadgeProps>(), {
  variant: 'default',
  size: 'md',
});

const classes = computed(() => [
  'atl-badge',
  `variant-${props.variant}`,
  `size-${props.size}`,
]);

const variantIconName = computed(() => VARIANT_ICON_NAMES[props.variant]);
</script>

<template>
  <span :class="classes" role="status">
    <AtlIcon
      v-if="variantIconName"
      class="variant-icon"
      :name="variantIconName"
      size="sm"
    />
    <slot />
  </span>
</template>
