// libs/vue/src/lib/pagination/atl-pagination.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@atelier-ui/styles/pagination/atl-pagination.css';
import AtlIcon from '../icon/atl-icon.vue';

defineOptions({ name: 'AtlPagination' });

interface AtlPaginationProps {
  /** Current page (1-based). Controlled: listen to `pageChange` and feed the new page back in. */
  page?: number;
  /** Total number of pages. */
  pageCount?: number;
  /** Number of page buttons to show on each side of the current page. */
  siblingCount?: number;
  /** Whether to show first/last page jump buttons. */
  showFirstLast?: boolean;
}

const props = withDefaults(defineProps<AtlPaginationProps>(), {
  page: 1,
  pageCount: 1,
  siblingCount: 1,
  showFirstLast: true,
});

const emit = defineEmits<{
  pageChange: [page: number];
}>();

type PageItem =
  { type: 'page'; page: number } | { type: 'ellipsis'; key: string };

function buildPageItems(
  page: number,
  pageCount: number,
  siblingCount: number,
): PageItem[] {
  if (pageCount <= 1) return [{ type: 'page', page: 1 }];
  const items: PageItem[] = [];
  items.push({ type: 'page', page: 1 });
  const left = Math.max(2, page - siblingCount);
  const right = Math.min(pageCount - 1, page + siblingCount);
  if (left > 2) items.push({ type: 'ellipsis', key: 'ellipsis-start' });
  for (let p = left; p <= right; p++) items.push({ type: 'page', page: p });
  if (right < pageCount - 1)
    items.push({ type: 'ellipsis', key: 'ellipsis-end' });
  if (pageCount > 1) items.push({ type: 'page', page: pageCount });
  return items;
}

const pageItems = computed(() =>
  buildPageItems(props.page, props.pageCount, props.siblingCount),
);

function goTo(p: number) {
  const clamped = Math.min(Math.max(p, 1), props.pageCount);
  if (clamped !== props.page) {
    emit('pageChange', clamped);
  }
}
</script>

<template>
  <nav class="atl-pagination" aria-label="Pagination">
    <ul class="page-list">
      <li v-if="showFirstLast">
        <button
          class="page-btn nav-btn"
          :class="{ 'is-disabled': page <= 1 }"
          :disabled="page <= 1"
          aria-label="First page"
          @click="goTo(1)"
        >
          <AtlIcon name="chevron-double-left" size="sm" />
        </button>
      </li>
      <li>
        <button
          class="page-btn nav-btn"
          :class="{ 'is-disabled': page <= 1 }"
          :disabled="page <= 1"
          aria-label="Previous page"
          @click="goTo(page - 1)"
        >
          <AtlIcon name="chevron-left" size="sm" />
        </button>
      </li>

      <template
        v-for="item in pageItems"
        :key="item.type === 'page' ? item.page : item.key"
      >
        <li v-if="item.type === 'ellipsis'">
          <span class="ellipsis" aria-hidden="true">…</span>
        </li>
        <li v-else>
          <button
            class="page-btn"
            :class="{ 'is-active': item.page === page }"
            :aria-label="`Page ${item.page}`"
            :aria-current="item.page === page ? 'page' : undefined"
            @click="goTo(item.page)"
          >
            {{ item.page }}
          </button>
        </li>
      </template>

      <li>
        <button
          class="page-btn nav-btn"
          :class="{ 'is-disabled': page >= pageCount }"
          :disabled="page >= pageCount"
          aria-label="Next page"
          @click="goTo(page + 1)"
        >
          <AtlIcon name="chevron-right" size="sm" />
        </button>
      </li>
      <li v-if="showFirstLast">
        <button
          class="page-btn nav-btn"
          :class="{ 'is-disabled': page >= pageCount }"
          :disabled="page >= pageCount"
          aria-label="Last page"
          @click="goTo(pageCount)"
        >
          <AtlIcon name="chevron-double-right" size="sm" />
        </button>
      </li>
    </ul>
  </nav>
</template>

// libs/angular/src/lib/pagination/atl-pagination.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
} from '@angular/core';
import { AtlIcon } from '../icon/atl-icon';

export type PageItem =
  { type: 'page'; page: number } | { type: 'ellipsis'; key: string };

/**
 * Pagination control for navigating multi-page content.
 *
 * Usage:
 * ```html
 * <atl-pagination [(page)]="currentPage" [pageCount]="totalPages" />
 * ```
 */
@Component({
  selector: 'atl-pagination',
  standalone: true,
  imports: [AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav aria-label="Pagination">
      <ul role="list" class="page-list">
        @if (showFirstLast()) {
          <li>
            <button
              class="page-btn"
              [class.is-disabled]="page() <= 1"
              [disabled]="page() <= 1"
              aria-label="First page"
              (click)="goFirst()"
            >
              <atl-icon name="chevron-double-left" size="sm" />
            </button>
          </li>
        }
        <li>
          <button
            class="page-btn"
            [class.is-disabled]="page() <= 1"
            [disabled]="page() <= 1"
            aria-label="Previous page"
            (click)="goPrev()"
          >
            <atl-icon name="chevron-left" size="sm" />
          </button>
        </li>

        @for (item of pageItems(); track $index) {
          @if (item.type === 'page') {
            <li>
              <button
                class="page-btn"
                [class.is-active]="item.page === page()"
                [attr.aria-current]="item.page === page() ? 'page' : null"
                [attr.aria-label]="'Page ' + item.page"
                (click)="goTo(item.page)"
              >
                {{ item.page }}
              </button>
            </li>
          } @else {
            <li>
              <span class="ellipsis" aria-hidden="true">…</span>
            </li>
          }
        }

        <li>
          <button
            class="page-btn"
            [class.is-disabled]="page() >= pageCount()"
            [disabled]="page() >= pageCount()"
            aria-label="Next page"
            (click)="goNext()"
          >
            <atl-icon name="chevron-right" size="sm" />
          </button>
        </li>
        @if (showFirstLast()) {
          <li>
            <button
              class="page-btn"
              [class.is-disabled]="page() >= pageCount()"
              [disabled]="page() >= pageCount()"
              aria-label="Last page"
              (click)="goLast()"
            >
              <atl-icon name="chevron-double-right" size="sm" />
            </button>
          </li>
        }
      </ul>
    </nav>
  `,
  styleUrl: './atl-pagination.css',
})
export class AtlPagination {
  /** Current page (1-based). Supports two-way binding: [(page)]="currentPage". */
  readonly page = model(1);

  /** Total number of pages. */
  readonly pageCount = input(1);

  /** Number of page buttons to show on each side of the current page. */
  readonly siblingCount = input(1);

  /** Whether to show first/last page jump buttons. */
  readonly showFirstLast = input(true);

  protected readonly pageItems = computed((): PageItem[] => {
    const total = this.pageCount();
    const current = this.page();
    const siblings = this.siblingCount();

    if (total <= 1) return [{ type: 'page', page: 1 }];

    const items: PageItem[] = [];

    // Always include first page
    items.push({ type: 'page', page: 1 });

    const left = Math.max(2, current - siblings);
    const right = Math.min(total - 1, current + siblings);

    // Left ellipsis
    if (left > 2) {
      items.push({ type: 'ellipsis', key: 'ellipsis-start' });
    }

    // Middle pages
    for (let p = left; p <= right; p++) {
      items.push({ type: 'page', page: p });
    }

    // Right ellipsis
    if (right < total - 1) {
      items.push({ type: 'ellipsis', key: 'ellipsis-end' });
    }

    // Always include last page
    items.push({ type: 'page', page: total });

    return items;
  });

  protected goTo(p: number): void {
    const clamped = Math.min(Math.max(p, 1), this.pageCount());
    this.page.set(clamped);
  }

  protected goPrev(): void {
    this.goTo(this.page() - 1);
  }

  protected goNext(): void {
    this.goTo(this.page() + 1);
  }

  protected goFirst(): void {
    this.goTo(1);
  }

  protected goLast(): void {
    this.goTo(this.pageCount());
  }
}
