// libs/react/src/lib/checkbox/atl-checkbox.tsx
import {
  InputHTMLAttributes,
  ReactNode,
  useRef,
  useEffect,
  useId,
} from 'react';
import type { AtlCheckboxSpec } from '../spec';
import './atl-checkbox.css';

/**
 * Properties for the AtlCheckbox component.
 */
export interface AtlCheckboxProps
  extends
    Omit<
      InputHTMLAttributes<HTMLInputElement>,
      'type' | 'checked' | 'onChange' | 'readOnly' | 'value'
    >,
    AtlCheckboxSpec {
  /**
   * Whether the checkbox is checked.
   */
  checked?: boolean;
  /**
   * Callback triggered when the checked state changes.
   */
  onCheckedChange?: (checked: boolean) => void;
  /**
   * Whether the checkbox is in an indeterminate state.
   */
  indeterminate?: boolean;
  /**
   * Whether the checkbox is in an invalid state.
   */
  invalid?: boolean;
  /**
   * Array of error messages to display.
   */
  errors?: string[];
  /**
   * The content to be rendered as the label for the checkbox.
   */
  children?: ReactNode;
}

/**
 * A checkbox component for selecting one or more options.
 */
export function AtlCheckbox({
  checked = false,
  onCheckedChange,
  indeterminate = false,
  invalid = false,
  errors = [],
  disabled = false,
  required = false,
  children,
  className,
  id,
  name,
  ...rest
}: AtlCheckboxProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const generatedId = useId();
  const inputId = id || `checkbox-${generatedId}`;
  const errorId = `${inputId}-errors`;

  const classes = [
    'atl-checkbox',
    checked && 'is-checked',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = indeterminate;
    }
  }, [indeterminate]);

  return (
    <div className={classes}>
      <label htmlFor={inputId}>
        <input
          ref={inputRef}
          type="checkbox"
          id={inputId}
          checked={checked}
          onChange={(e) => onCheckedChange?.(e.target.checked)}
          disabled={disabled}
          required={required}
          aria-invalid={invalid || undefined}
          aria-required={required || undefined}
          aria-describedby={errors.length > 0 ? errorId : undefined}
          name={name}
          {...rest}
        />
        {children}
      </label>
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

// libs/vue/src/lib/checkbox/atl-checkbox.vue
<script setup lang="ts">
import { ref, watch, onMounted, computed, useId } from 'vue';
import './atl-checkbox.css';

defineOptions({ name: 'AtlCheckbox' });

interface AtlCheckboxProps {
  checked?: boolean;
  indeterminate?: boolean;
  invalid?: boolean;
  errors?: string[];
  disabled?: boolean;
  required?: boolean;
  name?: string;
  id?: string;
}

const props = withDefaults(defineProps<AtlCheckboxProps>(), {
  checked: false,
  indeterminate: false,
  invalid: false,
  errors: () => [],
  disabled: false,
  required: false,
  name: '',
  id: '',
});

const emit = defineEmits<{
  'update:checked': [value: boolean];
}>();

const inputRef = ref<HTMLInputElement | null>(null);

const inputId = computed(() => props.id || `checkbox-${Math.random().toString(36).slice(2)}`);
const errorsId = useId();

watch(
  () => props.indeterminate,
  (val) => {
    if (inputRef.value) inputRef.value.indeterminate = val;
  }
);

onMounted(() => {
  if (inputRef.value) inputRef.value.indeterminate = props.indeterminate;
});

function onChange(event: Event) {
  const target = event.target as HTMLInputElement;
  emit('update:checked', target.checked);
}
</script>

<template>
  <div class="atl-checkbox" :class="{ 'is-invalid': invalid, 'is-disabled': disabled }">
    <label :for="inputId" class="checkbox-label">
      <input
        :id="inputId"
        ref="inputRef"
        type="checkbox"
        :checked="checked"
        :disabled="disabled"
        :required="required"
        :name="name"
        :aria-invalid="invalid || undefined"
        :aria-describedby="errors.length > 0 ? errorsId : undefined"
        @change="onChange"
      />
      <slot />
    </label>
    <div v-if="errors.length" :id="errorsId" class="errors" aria-live="polite">
      <p v-for="(error, i) in errors" :key="i" class="error-message">{{ error }}</p>
    </div>
  </div>
</template>
