// libs/llm-components-react/src/lib/checkbox/llm-checkbox.tsx
import { InputHTMLAttributes, ReactNode, useRef, useEffect, useId } from 'react';
import './llm-checkbox.css';

export interface LlmCheckboxProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'checked' | 'onChange'> {
  checked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  indeterminate?: boolean;
  invalid?: boolean;
  errors?: string[];
  children?: ReactNode;
}

export function LlmCheckbox({
  checked = false,
  onCheckedChange,
  indeterminate = false,
  invalid = false,
  errors = [],
  disabled = false,
  required = false,
  children,
  className,
  id,
  name,
  ...rest
}: LlmCheckboxProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const generatedId = useId();
  const inputId = id || `checkbox-${generatedId}`;
  const errorId = `${inputId}-errors`;

  const classes = [
    'llm-checkbox',
    checked && 'is-checked',
    invalid && 'is-invalid',
    disabled && 'is-disabled',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = indeterminate;
    }
  }, [indeterminate]);

  return (
    <div className={classes}>
      <label htmlFor={inputId}>
        <input
          ref={inputRef}
          type="checkbox"
          id={inputId}
          checked={checked}
          onChange={(e) => onCheckedChange?.(e.target.checked)}
          disabled={disabled}
          required={required}
          aria-invalid={invalid || undefined}
          aria-required={required || undefined}
          aria-describedby={errors.length > 0 ? errorId : undefined}
          name={name}
          {...rest}
        />
        {children}
      </label>
      {errors.length > 0 && (
        <div className="errors" id={errorId} aria-live="polite">
          {errors.map((err, i) => (
            <p key={i} className="error-message">
              {err}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

// libs/vue/src/lib/checkbox/llm-checkbox.vue
<script setup lang="ts">
import { ref, watch, onMounted, computed } from 'vue';
import './llm-checkbox.css';

defineOptions({ name: 'LlmCheckbox' });

interface LlmCheckboxProps {
  checked?: boolean;
  indeterminate?: boolean;
  invalid?: boolean;
  errors?: string[];
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  name?: string;
  id?: string;
}

const props = withDefaults(defineProps<LlmCheckboxProps>(), {
  checked: false,
  indeterminate: false,
  invalid: false,
  errors: () => [],
  disabled: false,
  readonly: false,
  required: false,
  name: '',
  id: '',
});

const emit = defineEmits<{
  'update:checked': [value: boolean];
}>();

const inputRef = ref<HTMLInputElement | null>(null);

const inputId = computed(() => props.id || `checkbox-${Math.random().toString(36).slice(2)}`);

watch(
  () => props.indeterminate,
  (val) => {
    if (inputRef.value) inputRef.value.indeterminate = val;
  }
);

onMounted(() => {
  if (inputRef.value) inputRef.value.indeterminate = props.indeterminate;
});

function onChange(event: Event) {
  const target = event.target as HTMLInputElement;
  emit('update:checked', target.checked);
}
</script>

<template>
  <div class="llm-checkbox" :class="{ 'is-invalid': invalid, 'is-disabled': disabled }">
    <label :for="inputId" class="checkbox-label">
      <input
        :id="inputId"
        ref="inputRef"
        type="checkbox"
        :checked="checked"
        :disabled="disabled"
        :readonly="readonly"
        :required="required"
        :name="name"
        :aria-invalid="invalid || undefined"
        @change="onChange"
      />
      <slot />
    </label>
    <ul v-if="errors.length" class="errors" aria-live="polite">
      <li v-for="(error, i) in errors" :key="i" class="error">{{ error }}</li>
    </ul>
  </div>
</template>
