// libs/vue/src/lib/radio/atl-radio.vue
<script setup lang="ts">
import { computed, inject } from 'vue';
import { AtlRadioGroupKey } from '../radio-group/atl-radio-group.vue';
import '@atelier-ui/styles/radio/atl-radio.css';

defineOptions({ name: 'AtlRadio' });

interface AtlRadioProps {
  /** The value this radio option represents within the group. */
  radioValue: string;
  /** Whether this radio is individually disabled (in addition to a disabled group). */
  disabled?: boolean;
}

const props = withDefaults(defineProps<AtlRadioProps>(), {
  disabled: false,
});

const ctx = inject(AtlRadioGroupKey, {
  value: '',
  name: '',
  disabled: false,
  readonly: false,
  invalid: false,
  onSelect: () => undefined,
});

const isDisabled = computed(() => props.disabled || ctx.disabled);
const isChecked = computed(() => ctx.value === props.radioValue);

const classes = computed(() =>
  [
    'atl-radio',
    isDisabled.value && 'is-disabled',
    isChecked.value && 'is-checked',
    ctx.invalid && 'is-invalid',
  ].filter(Boolean),
);

function onChange() {
  if (!isDisabled.value && !ctx.readonly) {
    ctx.onSelect(props.radioValue);
  }
}

// HTML ignores `readonly` on a radio, so the guard above stops the model but not
// the input's own DOM state — and nothing re-renders to correct it, since nothing
// changed. Cancelling the click makes the browser restore the previous selection
// (verified in chromium). See ADR-0045.
function onClick(event: MouseEvent) {
  if (ctx.readonly) event.preventDefault();
}
</script>

<template>
  <label :class="classes">
    <input
      type="radio"
      :name="ctx.name || undefined"
      :value="radioValue"
      :checked="isChecked"
      :disabled="isDisabled"
      class="radio-input"
      @click="onClick"
      @change="onChange"
    />
    <span class="radio-indicator" aria-hidden="true" />
    <span v-if="$slots.default" class="radio-text">
      <slot />
    </span>
  </label>
</template>

// libs/react/src/lib/radio/atl-radio.tsx
import { ReactNode } from 'react';
import type { AtlRadioSpec } from '../spec';
import { useRadioGroup } from '../radio-group/atl-radio-group';
import '@atelier-ui/styles/radio/atl-radio.css';

/**
 * Properties for the AtlRadio component.
 */
export interface AtlRadioProps extends AtlRadioSpec {
  /**
   * The value of the radio button.
   */
  radioValue: string;
  /**
   * Whether the radio button is disabled.
   */
  disabled?: boolean;
  /**
   * The content to be rendered as the label for the radio button.
   */
  children?: ReactNode;
}

/**
 * An individual radio button component, meant to be used within AtlRadioGroup.
 */
export function AtlRadio({
  radioValue,
  disabled = false,
  children,
}: AtlRadioProps) {
  const ctx = useRadioGroup();
  const isDisabled = disabled || ctx.disabled;
  const isChecked = ctx.value === radioValue;

  const classes = [
    'atl-radio',
    isDisabled && 'is-disabled',
    isChecked && 'is-checked',
    ctx.invalid && 'is-invalid',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <label className={classes}>
      <input
        type="radio"
        name={ctx.name || undefined}
        value={radioValue}
        checked={isChecked}
        disabled={isDisabled}
        // HTML ignores `readonly` on a radio, so guarding onChange stops the model
        // but not the input's own DOM state. Cancelling the click makes the browser
        // restore the previous selection (verified in chromium). See ADR-0045.
        onClick={(e) => ctx.readOnly && e.preventDefault()}
        onChange={() =>
          !isDisabled && !ctx.readOnly && ctx.onSelect(radioValue)
        }
        onBlur={() => ctx.onBlur()}
      />
      {children && <span className="radio-text">{children}</span>}
    </label>
  );
}
