// libs/angular/src/lib/radio/llm-radio.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  OnDestroy,
  OnInit,
} from '@angular/core';
import { LLM_RADIO_GROUP, type RadioItem } from '../radio-group/llm-radio-group.token';

let nextId = 0;

/**
 * Individual radio button. Must be placed inside an `llm-radio-group`.
 *
 * Usage:
 * ```html
 * <llm-radio-group [(value)]="selected" name="plan">
 *   <llm-radio radioValue="free">Free</llm-radio>
 *   <llm-radio radioValue="pro">Pro</llm-radio>
 * </llm-radio-group>
 * ```
 */
@Component({
  selector: 'llm-radio',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [attr.for]="inputId">
      <input
        type="radio"
        [id]="inputId"
        [value]="radioValue()"
        [checked]="isChecked()"
        [disabled]="isDisabled()"
        [attr.name]="effectiveName() || null"
        (change)="onChange()"
        (blur)="onBlur()"
      />
      <ng-content />
    </label>
  `,
  styleUrl: './llm-radio.css',
  host: {
    '[class]': 'hostClasses()',
  },
})
export class LlmRadio implements RadioItem, OnInit, OnDestroy {
  /** The value this radio option represents within the group. */
  readonly radioValue = input.required<string>();

  /** Whether this specific radio is individually disabled (stacked with group disabled). */
  readonly disabled = input(false);

  /** @internal */
  private readonly group = inject(LLM_RADIO_GROUP, { optional: true });

  /** @internal */
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);

  /** @internal */
  protected readonly inputId = `llm-radio-${nextId++}`;

  /** @internal */
  protected readonly isChecked = computed(() => this.group?.value() === this.radioValue());

  /** @internal */
  readonly isDisabled = computed(() => this.disabled() || (this.group?.disabled() ?? false));

  /** @internal */
  protected readonly effectiveName = computed(() => this.group?.name() ?? '');

  /** @internal */
  protected readonly hostClasses = computed(() => {
    const classes: string[] = [];
    if (this.isChecked()) classes.push('is-checked');
    if (this.isDisabled()) classes.push('is-disabled');
    return classes.join(' ');
  });

  /** @internal — for FocusKeyManager */
  get disabled(): boolean {
    return this.isDisabled();
  }

  /** @internal — for FocusKeyManager */
  focus(): void {
    this.el.nativeElement.querySelector<HTMLInputElement>('input')?.focus();
  }

  ngOnInit(): void {
    this.group?.registerItem(this);
  }

  ngOnDestroy(): void {
    this.group?.unregisterItem(this);
  }

  /** @internal */
  protected onChange(): void {
    this.group?.select(this.radioValue());
  }

  /** @internal */
  protected onBlur(): void {
    this.group?.markTouched();
  }
}

// libs/react/src/lib/radio/llm-radio.tsx
import { ReactNode } from 'react';
import type { LlmRadioSpec } from '../spec';
import { useRadioGroup } from '../radio-group/llm-radio-group';
import './llm-radio.css';

/**
 * Properties for the LlmRadio component.
 */
export interface LlmRadioProps extends LlmRadioSpec {
  /**
   * The value of the radio button.
   */
  radioValue: string;
  /**
   * Whether the radio button is disabled.
   */
  disabled?: boolean;
  /**
   * The content to be rendered as the label for the radio button.
   */
  children?: ReactNode;
}

/**
 * An individual radio button component, meant to be used within LlmRadioGroup.
 */
export function LlmRadio({ radioValue, disabled = false, children }: LlmRadioProps) {
  const ctx = useRadioGroup();
  const isDisabled = disabled || ctx.disabled;
  const isReadOnly = ctx.readOnly;
  const isChecked = ctx.value === radioValue;

  const classes = [
    'llm-radio',
    isDisabled && 'is-disabled',
    isReadOnly && 'is-readonly',
    isChecked && 'is-checked',
    ctx.invalid && 'is-invalid',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <label className={classes}>
      <input
        type="radio"
        name={ctx.name || undefined}
        value={radioValue}
        checked={isChecked}
        disabled={isDisabled}
        readOnly={isReadOnly}
        onChange={() => !isDisabled && !isReadOnly && ctx.onSelect(radioValue)}
        onBlur={() => ctx.onBlur()}
      />
      {children && <span className="radio-text">{children}</span>}
    </label>
  );
}
