// libs/angular/src/lib/avatar/atl-avatar.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  contentChildren,
  effect,
  input,
  signal,
  untracked,
} from '@angular/core';
import { AtlIcon } from '../icon/atl-icon';

/**
 * Displays a user avatar with image, initials, or icon fallback.
 *
 * Fallback order: image → initials (from `name`) → generic icon.
 *
 * Usage:
 * ```html
 * <atl-avatar src="https://example.com/photo.jpg" name="Jane Doe" />
 * <atl-avatar name="John Smith" size="lg" status="online" />
 * <atl-avatar size="sm" shape="square" />
 * ```
 */
@Component({
  selector: 'atl-avatar',
  standalone: true,
  imports: [AtlIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <!-- eslint-disable -->
    @if (src() && showImage()) {
      <img [src]="src()" [alt]="alt()" (error)="showImage.set(false)" />
    } @else if (initials()) {
      <span class="initials" aria-hidden="true">{{ initials() }}</span>
    } @else {
      <atl-icon name="person" size="sm" class="icon" />
    }
    @if (status()) {
      <span [class]="'status-dot status-' + status()" aria-hidden="true"></span>
    }
  `,
  styleUrl: './atl-avatar.css',
  host: {
    '[class]': 'hostClasses()',
    role: 'img',
    '[attr.aria-label]': 'ariaLabel()',
  },
})
export class AtlAvatar {
  /** Image URL. Falls back to initials or icon if empty or fails to load. */
  readonly src = input('');

  /** Alt text for the image (also used as aria-label). */
  readonly alt = input('');

  /** Full name used to generate initials fallback and default aria-label. */
  readonly name = input('');

  /** Size of the avatar. */
  readonly size = input<'xs' | 'sm' | 'md' | 'lg' | 'xl'>('md');

  /** Shape of the avatar. */
  readonly shape = input<'circle' | 'square'>('circle');

  /** Presence status indicator dot. Empty string hides the dot. */
  readonly status = input<'online' | 'offline' | 'away' | 'busy' | ''>('');

  /** @internal — reset to true whenever src changes */
  protected readonly showImage = signal(true);

  /** @internal */
  protected readonly initials = computed(() => {
    const name = this.name();
    if (!name) return '';
    return name
      .split(' ')
      .filter(Boolean)
      .slice(0, 2)
      .map((w) => w[0].toUpperCase())
      .join('');
  });

  /** @internal */
  protected readonly ariaLabel = computed(
    () => this.alt() || this.name() || 'Avatar',
  );

  /** @internal */
  protected readonly hostClasses = computed(
    () => `size-${this.size()} shape-${this.shape()}`,
  );

  constructor() {
    effect(() => {
      this.src(); // track src changes
      untracked(() => this.showImage.set(true));
    });
  }
}

/**
 * Groups multiple avatars with overlap and an overflow count badge.
 *
 * Usage:
 * ```html
 * <atl-avatar-group [max]="3" size="md">
 *   <atl-avatar name="Alice" />
 *   <atl-avatar name="Bob" />
 *   <atl-avatar name="Charlie" />
 *   <atl-avatar name="Dave" />
 * </atl-avatar-group>
 * ```
 */
@Component({
  selector: 'atl-avatar-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-content />
    @if (overflowCount() > 0) {
      <span [class]="'overflow-badge size-' + size()"
        >+{{ overflowCount() }}</span
      >
    }
  `,
  styleUrl: './atl-avatar.css',
  host: {
    class: 'group',
    '[class]': '"group size-" + size()',
  },
})
export class AtlAvatarGroup {
  /** Maximum visible avatars before showing an overflow count. */
  readonly max = input(5);

  /** Size applied to the overflow badge (match the size used on child avatars). */
  readonly size = input<'xs' | 'sm' | 'md' | 'lg' | 'xl'>('md');

  private readonly avatarEls = contentChildren(AtlAvatar, { read: ElementRef });

  protected readonly overflowCount = computed(() =>
    Math.max(0, this.avatarEls().length - this.max()),
  );

  constructor() {
    effect(() => {
      const max = this.max();
      this.avatarEls().forEach((el, i) => {
        (el.nativeElement as HTMLElement).style.display =
          i >= max ? 'none' : '';
      });
    });
  }
}

// libs/vue/src/lib/avatar/atl-avatar.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import '@atelier-ui/styles/avatar/atl-avatar.css';
import AtlIcon from '../icon/atl-icon.vue';

defineOptions({ name: 'AtlAvatar' });

interface AtlAvatarProps {
  /** Image URL. Falls back to initials if empty or if the image fails to load. */
  src?: string;
  /** Alt text for the image (also used as the accessible label). */
  alt?: string;
  /** Full name used to generate the initials fallback and the default accessible label. */
  name?: string;
  /** Size of the avatar. */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /** Shape of the avatar. */
  shape?: 'circle' | 'square';
  /** Presence status indicator dot. Empty string hides the dot. */
  status?: 'online' | 'offline' | 'away' | 'busy' | '';
}

const props = withDefaults(defineProps<AtlAvatarProps>(), {
  src: '',
  alt: '',
  name: '',
  size: 'md',
  shape: 'circle',
  status: '',
});

const imgError = ref(false);

watch(
  () => props.src,
  () => {
    imgError.value = false;
  },
);

function getInitials(name: string): string {
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0].toUpperCase())
    .join('');
}

const initials = computed(() => (props.name ? getInitials(props.name) : ''));
const ariaLabel = computed(() => props.alt || props.name || 'Avatar');

const classes = computed(() => [
  'atl-avatar',
  `size-${props.size}`,
  `shape-${props.shape}`,
]);
</script>

<template>
  <div :class="classes" :aria-label="ariaLabel" role="img">
    <img
      v-if="src && !imgError"
      :src="src"
      :alt="alt || name"
      @error="imgError = true"
    />
    <span v-else-if="initials" class="initials">{{ initials }}</span>
    <AtlIcon name="person" size="sm" class="icon" />
    <span
      v-if="status"
      :class="`status-dot status-${status}`"
      aria-hidden="true"
    />
  </div>
</template>
